using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using MBINCompiler;
using MBINCompiler.Models.Structs;
using System.IO;

namespace MBINCompilerTests
{
    [TestClass]
    public class UnitTests
    {
        String baseDir = "C:/NMS";
        String testFile1 = "../../MBINCompilerTestTemplate.MBIN";

        [TestMethod]
        public void template_deserializing_test1()
        {
            var file = new MBINFile(testFile1);
            file.Load();
            Assert.AreEqual(file.Header.GetXMLTemplateName(), "MBINCompilerTestTemplate", testFile1 + " header not using TemplateType MBINCompilerTestTemplate!");

            var data = file.GetData();
            Assert.IsNotNull(data, testFile1 + " deserialized data was null");
            Assert.IsNotNull(data.SerializeEXml(), testFile1 + " xml serialization was null");
            Assert.IsInstanceOfType(data, typeof(MBINCompilerTestTemplate), testFile1 + " template isn't of type MBINCompilerTestTemplate!");

            MBINCompilerTestTemplate test = (MBINCompilerTestTemplate)data;
            Assert.AreEqual(test.TestBoolTrue, true);
            Assert.AreEqual(test.TestBoolFalse, false);
            Assert.AreEqual(test.TestBool3, true);
            Assert.AreEqual(test.TestInt16, 1337);
            Assert.AreEqual(test.TestInt32, 2448);
            Assert.AreEqual(test.TestInt64, 3559);
            Assert.AreEqual(test.TestFloat, 1337.0);
            Assert.AreEqual(test.TestEnumYes, 1);
            Assert.AreEqual(test.TestEnumNo, 0);

            var expectedString = "SixteenByteStrng";
            Assert.AreEqual(test.TestString, expectedString);

            var expectedDynamicString = "NoWayToControlItIt'sTotallyDynamicWheneverYou'reAround";
            Assert.AreEqual(test.TestDynamicString.Value, expectedDynamicString);

            string[] expectedStrings = new[] { "FirstEntry", "SecondEntry", "ThirdEntry" };
            Assert.AreEqual(test.Test0x80ByteStringList.Count, expectedStrings.Length);

            for (int i = 0; i < expectedStrings.Length; i++)
                Assert.AreEqual(test.Test0x80ByteStringList[i].Value, expectedStrings[i]);
        }

        string[] gameTestFiles = new string[] // all of these should decompile fine
        {
            // GcAlienSpeechTable
            "METADATA/REALITY/TABLES/NMS_DIALOG_GCALIENSPEECHTABLE.MBIN",
            "LANGUAGE/NMS_DIALOG.MBIN",

            // GcAtlasGlobals
            "GCATLASGLOBALS.GLOBAL.MBIN",

            // GcAlienPuzzleTable
            "METADATA/REALITY/TABLES/NMS_DIALOG_GCALIENPUZZLETABLE.MBIN",

            // GcBootLogoData
            "METADATA/UI/BOOTLOGOPC.MBIN",
            "METADATA/UI/BOOTLOGOPS4.MBIN",

            // GcCostTable
            "METADATA/REALITY/TABLES/COSTTABLE.MBIN",

            // GcCreatureAudioTable
            "METADATA/SIMULATION/ECOSYSTEM/CREATUREAUDIOTABLE.MBIN",

            // GcCreatureDataTable
            "METADATA/SIMULATION/ECOSYSTEM/CREATUREDATATABLE.MBIN",
            "METADATA/SIMULATION/ECOSYSTEM/ROBOTDATATABLE.MBIN",

            // GcCreatureFilenameTable
            "METADATA/SIMULATION/ECOSYSTEM/CREATUREFILENAMETABLE.MBIN",

            // GcCreatureRoleDescriptionTable tests
            "METADATA/SIMULATION/ECOSYSTEM/ROLEDESCRIPTIONTABLES/AIR/AIRTABLECOMMON.MBIN",
            "METADATA/SIMULATION/ECOSYSTEM/ROLEDESCRIPTIONTABLES/AIR/AIRTABLECOMMONLIZARD.MBIN",
            "METADATA/SIMULATION/ECOSYSTEM/ROLEDESCRIPTIONTABLES/AIR/AIRTABLECOMMONSNAKE.MBIN",
            "METADATA/SIMULATION/ECOSYSTEM/ROLEDESCRIPTIONTABLES/AIR/AIRTABLEDEAD.MBIN",
            "METADATA/SIMULATION/ECOSYSTEM/ROLEDESCRIPTIONTABLES/AIR/AIRTABLEFLYINGLIZARDONLY.MBIN",
            "METADATA/SIMULATION/ECOSYSTEM/ROLEDESCRIPTIONTABLES/AIR/AIRTABLEFLYINGSNAKESONLY.MBIN",
            "METADATA/SIMULATION/ECOSYSTEM/ROLEDESCRIPTIONTABLES/CAVE/CAVETABLECOMMON.MBIN",
            "METADATA/SIMULATION/ECOSYSTEM/ROLEDESCRIPTIONTABLES/CAVE/CAVETABLEEMPTY.MBIN",
            "METADATA/SIMULATION/ECOSYSTEM/ROLEDESCRIPTIONTABLES/GROUND/GROUNDTABLEALLCOW.MBIN",
            "METADATA/SIMULATION/ECOSYSTEM/ROLEDESCRIPTIONTABLES/GROUND/GROUNDTABLEBUSY.MBIN",
            "METADATA/SIMULATION/ECOSYSTEM/ROLEDESCRIPTIONTABLES/GROUND/GROUNDTABLECOMMON.MBIN",
            "METADATA/SIMULATION/ECOSYSTEM/ROLEDESCRIPTIONTABLES/GROUND/GROUNDTABLEDEAD.MBIN",
            "METADATA/SIMULATION/ECOSYSTEM/ROLEDESCRIPTIONTABLES/GROUND/GROUNDTABLEDINOSAURS.MBIN",
            "METADATA/SIMULATION/ECOSYSTEM/ROLEDESCRIPTIONTABLES/GROUND/GROUNDTABLEGIANT.MBIN",
            "METADATA/SIMULATION/ECOSYSTEM/ROLEDESCRIPTIONTABLES/GROUND/GROUNDTABLEGRUNTLAND.MBIN",
            "METADATA/SIMULATION/ECOSYSTEM/ROLEDESCRIPTIONTABLES/GROUND/GROUNDTABLEPREDATORS.MBIN",
            "METADATA/SIMULATION/ECOSYSTEM/ROLEDESCRIPTIONTABLES/GROUND/GROUNDTABLEPREHISTORIC.MBIN",
            "METADATA/SIMULATION/ECOSYSTEM/ROLEDESCRIPTIONTABLES/GROUND/GROUNDTABLEPREYBLOBS.MBIN",
            "METADATA/SIMULATION/ECOSYSTEM/ROLEDESCRIPTIONTABLES/GROUND/GROUNDTABLESMALLPREDATORS.MBIN",
            "METADATA/SIMULATION/ECOSYSTEM/ROLEDESCRIPTIONTABLES/GROUND/GROUNDTABLESPARSE.MBIN",
            "METADATA/SIMULATION/ECOSYSTEM/ROLEDESCRIPTIONTABLES/SENTINELS/GROUNDTABLESENTINELS.MBIN",
            "METADATA/SIMULATION/ECOSYSTEM/ROLEDESCRIPTIONTABLES/UNDERWATER/UNDERWATERTABLE1.MBIN",
            "METADATA/SIMULATION/ECOSYSTEM/ROLEDESCRIPTIONTABLES/UNDERWATER/UNDERWATERTABLECOMMON.MBIN",
            "METADATA/SIMULATION/ECOSYSTEM/ROLEDESCRIPTIONTABLES/UNDERWATER/UNDERWATERTABLEEMPTY.MBIN",
            "METADATA/SIMULATION/ECOSYSTEM/ROLEDESCRIPTIONTABLES/UNDERWATER/UNDERWATERTABLEWHALE.MBIN",

            // GcCreatureStupidNameTable
            "SCENES/CREATURESTUPIDNAMETABLE.MBIN",
            "SCENES/CREATURESTUPIDNAMETABLEPS4.MBIN",

            // GcDebugOptions
            "GCDEBUGOPTIONS.GLOBAL.MBIN",

            // GcEntitlementRewardsTable
            "METADATA/ENTITLEMENTS/GCENTITLEMENTREWARDTABLE.MBIN",
            "METADATA/ENTITLEMENTS/GCENTITLEMENTREWARDTABLEPC.MBIN",

            // GcHUDLayerData
            "METADATA/UI/HUD/PLAYERHUD.MBIN",
            "METADATA/UI/HUD/PLAYERHUDMASKS.MBIN",
            "METADATA/UI/HUD/SHIPHUD.MBIN",
            "METADATA/UI/HUD/COCKPIT/BOTTOMSCREEN1.MBIN",
            "METADATA/UI/HUD/COCKPIT/BOTTOMSCREEN2.MBIN",
            "METADATA/UI/HUD/COCKPIT/MAINSCREEN1.MBIN",
            "METADATA/UI/HUD/COCKPIT/SIDESCREEN1.MBIN",
            "METADATA/UI/HUD/COCKPIT/SIDESCREEN2.MBIN",
            "METADATA/UI/HUD/COCKPIT/SIDESCREEN3.MBIN",
            "METADATA/UI/HUD/COCKPIT/SIDESCREEN4.MBIN",
            "METADATA/UI/HUD/WEAPONS/BULLETGUN.MBIN",
            "METADATA/UI/HUD/WEAPONS/LASER.MBIN",
            "METADATA/UI/HUD/WEAPONS/MISSILE.MBIN",

            // GcJourneyMilestoneTable
            "METADATA/GAMESTATE/STATS/JOURNEYMILESTONETABLE.MBIN",

            // GcPlayerDamageTable
            "METADATA/REALITY/TABLES/DAMAGETABLE.MBIN",
            
            // GcRewardTable
            "METADATA/REALITY/TABLES/REWARDTABLE.MBIN",

            // GcSceneSettings
            "SCENES/COMMON/DEFAULTSETTINGS.MBIN",
            "SCENES/DEMOS/PS4BIOMETEST/BARRENSETTINGS.MBIN",
            "SCENES/DEMOS/PS4BIOMETEST/CAVESETTINGS.MBIN",
            "SCENES/DEMOS/PS4BIOMETEST/FROZENSETTINGS.MBIN",
            "SCENES/DEMOS/PS4BIOMETEST/LUSHSETTINGS.MBIN",
            "SCENES/DEMOS/PS4BIOMETEST/RADIOACTIVESETTINGS.MBIN",
            "SCENES/DEMOS/PS4BIOMETEST/SCORCHEDSETTINGS.MBIN",
            "SCENES/DEMOS/PS4BIOMETEST/TOXICSETTINGS.MBIN",
            "SCENES/DEMOS/PS4BIOMETEST/UNDERWATERSETTINGS.MBIN",
            "SCENES/DEMOS/PS4TEST/MAINSETTINGSPS4TEST.MBIN",
            "SCENES/DEMOS/PS4TEST/MAINSETTINGSPS4TESTALT.MBIN",
            "SCENES/DEMOS/SPRINGEVENT2016/BARRENSETTINGS.MBIN",
            "SCENES/DEMOS/SPRINGEVENT2016/LUSHSETTINGS.MBIN",
            "SCENES/DEMOS/SPRINGEVENT2016/MAINSETTINGS.MBIN",
            "SCENES/DEMOS/SPRINGEVENT2016/MAINSETTINGSPRESS.MBIN",
            "SCENES/DEMOS/SPRINGEVENT2016/SCORCHEDSETTINGS.MBIN",
            "SCENES/DEMOS/SPRINGEVENT2016/TOXICSETTINGS.MBIN",
            "SCENES/DEMOS/USEREXPERIENCE/MAINSETTINGS.MBIN",
            "SCENES/EMPTY/SCENESETTINGS.MBIN",
            "SCENES/SCREENSHOTS/E32015/MAINSETTINGS.MBIN",
            "SCENES/SCREENSHOTS/E32015/MAINSETTINGSSPACE.MBIN",
            "SCENES/SCREENSHOTS/PLANET1/MAINSETTINGS.MBIN",
            "SCENES/SCREENSHOTS/PLANET2/PLANET2SETTINGS.MBIN",
            "SCENES/SCREENSHOTS/PLANET3/PLANET3SETTINGS.MBIN",
            "SCENES/TESTSCENES/ANIMTEST/ANIMTESTSETTINGS.MBIN",
            "SCENES/TESTSCENES/TESTPLANETS/ZOOPLANETSETTINGS.MBIN",

            // GcStatDefinitionTable
            "METADATA/GAMESTATE/STATS/STATDEFINITIONSTABLE.MBIN",

            // GcStatGroupTable
            "METADATA/GAMESTATE/STATS/STATGROUPSTABLE.MBIN",

            // GcTechnologyTable
            "METADATA/REALITY/TABLES/NMS_REALITY_GCTECHNOLOGYTABLE.MBIN",

            // GcTextPresetTable
            "METADATA/FONTS/TEXTPRESETTABLE.MBIN",

            // GcUserSettingsData
            "METADATA/ENGINESETTINGS/GCUSERSETTINGSDATA.MBIN",

            // GcWaterGlobals
            "GCWATERGLOBALS.GLOBAL.MBIN",

            // GcWeatherColourSettingList
            "METADATA/SIMULATION/SOLARSYSTEM/WEATHER/SKYSETTINGS/DAYSKYCOLOURS.MBIN",
            "METADATA/SIMULATION/SOLARSYSTEM/WEATHER/SKYSETTINGS/DUSKSKYCOLOURS.MBIN",
            "METADATA/SIMULATION/SOLARSYSTEM/WEATHER/SKYSETTINGS/NIGHTSKYCOLOURS.MBIN",

            // GcWeatherProperties
            "METADATA/SIMULATION/SOLARSYSTEM/WEATHER/CLEARWEATHER.MBIN",
            "METADATA/SIMULATION/SOLARSYSTEM/WEATHER/DUSTWEATHER.MBIN",
            "METADATA/SIMULATION/SOLARSYSTEM/WEATHER/HUMIDWEATHER.MBIN",
            "METADATA/SIMULATION/SOLARSYSTEM/WEATHER/RADIOACTIVE.MBIN",
            "METADATA/SIMULATION/SOLARSYSTEM/WEATHER/RAINWEATHER.MBIN",
            "METADATA/SIMULATION/SOLARSYSTEM/WEATHER/SCORCHED.MBIN",
            "METADATA/SIMULATION/SOLARSYSTEM/WEATHER/SNOWWEATHER.MBIN",
            "METADATA/SIMULATION/SOLARSYSTEM/WEATHER/TOXIC.MBIN",

            // TkControllerSpecification
            "METADATA/INPUT/GCCONTROLLERSPECKEYBOARD.MBIN",
            "METADATA/INPUT/GCCONTROLLERSPECPS4.MBIN",
            "METADATA/INPUT/GCCONTROLLERSPECREMAPPED.MBIN",
            "METADATA/INPUT/GCCONTROLLERSPECSTEAM.MBIN",
            "METADATA/INPUT/GCCONTROLLERSPECXBOX.MBIN",

            // TkControllerList
            "METADATA/INPUT/GCCONTROLLERLIST.MBIN",

            // TkEngineSettings
            "METADATA/ENGINE/TKENGINESETTINGS.MBIN",

            // TkEngineSettingsMapping
            "METADATA/ENGINESETTINGS/TKENGINESETTINGSMAPPING.MBIN",

            // TkEntitlementList
            "METADATA/ENTITLEMENTS/TKENTITLEMENTLIST.MBIN",
            "METADATA/ENTITLEMENTS/TKENTITLEMENTLISTPC.MBIN",

            // TkGraphicsSettings
            "METADATA/ENGINESETTINGS/TKGRAPHICSSETTINGS.MBIN",
            "METADATA/ENGINESETTINGS/TKGRAPHICSSETTINGSPS4.MBIN",

            // TkLocalisationTable (these take years)
            /*
            "LANGUAGE/NMS_LOC1.MBIN",
            "LANGUAGE/NMS_LOC1_BRAZILIANPORTUGUESE.MBIN",
            "LANGUAGE/NMS_LOC1_DUTCH.MBIN",
            "LANGUAGE/NMS_LOC1_ENGLISH.MBIN",
            "LANGUAGE/NMS_LOC1_FRENCH.MBIN",
            "LANGUAGE/NMS_LOC1_GERMAN.MBIN",
            "LANGUAGE/NMS_LOC1_ITALIAN.MBIN",
            "LANGUAGE/NMS_LOC1_JAPANESE.MBIN",
            "LANGUAGE/NMS_LOC1_KOREAN.MBIN",
            "LANGUAGE/NMS_LOC1_LATINAMERAICANSPANISH.MBIN",
            "LANGUAGE/NMS_LOC1_POLISH.MBIN",
            "LANGUAGE/NMS_LOC1_PORTUGUESE.MBIN",
            "LANGUAGE/NMS_LOC1_RUSSIAN.MBIN",
            "LANGUAGE/NMS_LOC1_SIMPLIFIEDCHINESE.MBIN",
            "LANGUAGE/NMS_LOC1_SPANISH.MBIN",
            "LANGUAGE/NMS_LOC1_TRADITIONALCHINESE.MBIN",
            "LANGUAGE/NMS_LOC1_USENGLISH.MBIN",*/

            // TkProceduralTextureList
            "TEXTURES/COMMON/DECALS/LETTERING/LETTERING.TEXTURE.MBIN",
            "TEXTURES/COMMON/DECALS/LOGO/LOGO.TEXTURE.MBIN",
            "TEXTURES/COMMON/DECALS/NUMBER/NUMBER.TEXTURE.MBIN",
            "TEXTURES/COMMON/DECALS/RECTANGLE/RECTANGLE.TEXTURE.MBIN",
            "TEXTURES/COMMON/DECALS/SMALLSIGN/SMALLSIGN.TEXTURE.MBIN",
            "TEXTURES/COMMON/DECALS/SQAURE/SQAURE.TEXTURE.MBIN",
            "TEXTURES/COMMON/DEMOS/E32015/MODELS/FLOATINGSPHERE.TEXTURE.MBIN",
            "TEXTURES/COMMON/SPACECRAFT/DROPSHIP/COCKPIT/COCKPIT_A.TEXTURE.MBIN",
            "TEXTURES/COMMON/SPACECRAFT/DROPSHIP/COCKPIT/COCKPIT_B.TEXTURE.MBIN",
            "TEXTURES/COMMON/SPACECRAFT/DROPSHIP/DETAILKITS/DETAILKIT_A.TEXTURE.MBIN",
            "TEXTURES/COMMON/SPACECRAFT/DROPSHIP/ENGINE/ENGINE_A.TEXTURE.MBIN",
            "TEXTURES/COMMON/SPACECRAFT/DROPSHIP/ENGINE/ENGINE_B.TEXTURE.MBIN",
            "TEXTURES/COMMON/SPACECRAFT/DROPSHIP/HULL/HULL_A.TEXTURE.MBIN",
            "TEXTURES/COMMON/SPACECRAFT/DROPSHIP/HULL/HULL_B.TEXTURE.MBIN",
            "TEXTURES/COMMON/SPACECRAFT/DROPSHIP/SUBWINGS/SUBWINGS_A.TEXTURE.MBIN",
            "TEXTURES/COMMON/SPACECRAFT/DROPSHIP/SUBWINGS/SUBWINGS_B.TEXTURE.MBIN",
            "TEXTURES/COMMON/SPACECRAFT/DROPSHIP/SUBWINGS/SUBWINGS_C.TEXTURE.MBIN",
            "TEXTURES/COMMON/SPACECRAFT/DROPSHIP/SUBWINGS/SUBWINGS_D.TEXTURE.MBIN",
            "TEXTURES/COMMON/SPACECRAFT/DROPSHIP/SUBWINGS/SUBWINGS_E.TEXTURE.MBIN",
            "TEXTURES/COMMON/SPACECRAFT/DROPSHIP/SUBWINGS/SUBWINGS_F.TEXTURE.MBIN",
            "TEXTURES/COMMON/SPACECRAFT/DROPSHIP/SUBWINGS/SUBWINGS_G.TEXTURE.MBIN",
            "TEXTURES/COMMON/SPACECRAFT/DROPSHIP/THRUSTERS/THRUSTERS_A.TEXTURE.MBIN",
            "TEXTURES/COMMON/SPACECRAFT/DROPSHIP/THRUSTERS/THRUSTERS_B.TEXTURE.MBIN",
            "TEXTURES/COMMON/SPACECRAFT/DROPSHIP/THRUSTERS/THRUSTERS_C.TEXTURE.MBIN",
            "TEXTURES/COMMON/SPACECRAFT/DROPSHIP/WINGS/WINGS_A.TEXTURE.MBIN",
            "TEXTURES/COMMON/SPACECRAFT/DROPSHIP/WINGS/WINGS_B.TEXTURE.MBIN",
            "TEXTURES/COMMON/SPACECRAFT/FIGHTERS/COCKPIT/COCKPITACC_TOPFIN_A.TEXTURE.MBIN",
            "TEXTURES/COMMON/SPACECRAFT/FIGHTERS/COCKPIT/COCKPITACC_TOPFIN_B.TEXTURE.MBIN",
            "TEXTURES/COMMON/SPACECRAFT/FIGHTERS/COCKPIT/COCKPIT_A.TEXTURE.MBIN",
            "TEXTURES/COMMON/SPACECRAFT/FIGHTERS/COCKPIT/COCKPIT_A_NOSEB.TEXTURE.MBIN",
            "TEXTURES/COMMON/SPACECRAFT/FIGHTERS/COCKPIT/COCKPIT_B.TEXTURE.MBIN",
            "TEXTURES/COMMON/SPACECRAFT/FIGHTERS/COCKPIT/COCKPIT_B_NOSEA.TEXTURE.MBIN",
            "TEXTURES/COMMON/SPACECRAFT/FIGHTERS/COCKPIT/COCKPIT_A/COCKPIT_A.TEXTURE.MBIN",
            "TEXTURES/COMMON/SPACECRAFT/FIGHTERS/COCKPIT/COCKPIT_B/COCKPIT_B.TEXTURE.MBIN",
            "TEXTURES/COMMON/SPACECRAFT/FIGHTERS/ENGINES/ENGINES_A.TEXTURE.MBIN",
            "TEXTURES/COMMON/SPACECRAFT/FIGHTERS/ENGINES/ENGINES_B.TEXTURE.MBIN",
            "TEXTURES/COMMON/SPACECRAFT/FIGHTERS/ENGINES/ENGINES_C.TEXTURE.MBIN",
            "TEXTURES/COMMON/SPACECRAFT/FIGHTERS/ENGINES/ENGINE_B/ENGINE_B.TEXTURE.MBIN",
            "TEXTURES/COMMON/SPACECRAFT/FIGHTERS/ENGINES/ENGINE_C/ENGINE_C.TEXTURE.MBIN",
            "TEXTURES/COMMON/SPACECRAFT/FIGHTERS/HULL/HULL_A.TEXTURE.MBIN",
            "TEXTURES/COMMON/SPACECRAFT/FIGHTERS/NOSE/COCKPITA_NOSEB/COCKPITA_NOSEB.TEXTURE.MBIN",
            "TEXTURES/COMMON/SPACECRAFT/FIGHTERS/NOSE/COCKPITB_NOSEA/COCKPITB_NOSEA.TEXTURE.MBIN",
            "TEXTURES/COMMON/SPACECRAFT/FIGHTERS/SHARED/PRIMARY.TEXTURE.MBIN",
            "TEXTURES/COMMON/SPACECRAFT/FIGHTERS/SHARED/SECONDARY.TEXTURE.MBIN",
            "TEXTURES/COMMON/SPACECRAFT/FIGHTERS/SHARED/TERTIARY.TEXTURE.MBIN",
            "TEXTURES/COMMON/SPACECRAFT/FIGHTERS/SHARED/TRIMS.TEXTURE.MBIN",
            "TEXTURES/COMMON/SPACECRAFT/FIGHTERS/SUBWINGS/SUBWINGS_B/SUBWINGS_B.TEXTURE.MBIN",
            "TEXTURES/COMMON/SPACECRAFT/FIGHTERS/WINGS/WINGS_A.TEXTURE.MBIN",
            "TEXTURES/COMMON/SPACECRAFT/FIGHTERS/WINGS/WINGS_B.TEXTURE.MBIN",
            "TEXTURES/COMMON/SPACECRAFT/FIGHTERS/WINGS/WINGS_D.TEXTURE.MBIN",
            "TEXTURES/COMMON/SPACECRAFT/FIGHTERS/WINGS/WINGS_E.TEXTURE.MBIN",
            "TEXTURES/COMMON/SPACECRAFT/FIGHTERS/WINGS/WINGS_F.TEXTURE.MBIN",
            "TEXTURES/COMMON/SPACECRAFT/FIGHTERS/WINGS/WINGS_G.TEXTURE.MBIN",
            "TEXTURES/COMMON/SPACECRAFT/FIGHTERS/WINGS/WINGS_H.TEXTURE.MBIN",
            "TEXTURES/COMMON/SPACECRAFT/FIGHTERS/WINGS/WINGS_I.TEXTURE.MBIN",
            "TEXTURES/COMMON/SPACECRAFT/FIGHTERS/WINGS/WINGS_J.TEXTURE.MBIN",
            "TEXTURES/COMMON/SPACECRAFT/FIGHTERS/WINGS/WINGS_K.TEXTURE.MBIN",
            "TEXTURES/COMMON/SPACECRAFT/FIGHTERS/WINGS/WINGS_L.TEXTURE.MBIN",
            "TEXTURES/COMMON/SPACECRAFT/FIGHTERS/WINGS/WINGS_M.TEXTURE.MBIN",
            "TEXTURES/COMMON/SPACECRAFT/FIGHTERS/WINGS/WINGS_A/WINGS_A.TEXTURE.MBIN",
            "TEXTURES/COMMON/SPACECRAFT/FIGHTERS/WINGS/WINGS_D/WINGS_D.TEXTURE.MBIN",
            "TEXTURES/COMMON/SPACECRAFT/FIGHTERS/WINGS/WINGS_E/WINGS_E.TEXTURE.MBIN",
            "TEXTURES/COMMON/SPACECRAFT/FIGHTERS/WINGS/WINGS_G/WINGS_G.TEXTURE.MBIN",
            "TEXTURES/COMMON/SPACECRAFT/FIGHTERS/WINGS/WINGS_I/WINGS_I.TEXTURE.MBIN",
            "TEXTURES/COMMON/SPACECRAFT/INDUSTRIAL/SHARED/FREIGHTER_PROC.TEXTURE.MBIN",
            "TEXTURES/COMMON/SPACECRAFT/INDUSTRIAL/SHARED/DECALS/SMALL_STRIPES.TEXTURE.MBIN",
            "TEXTURES/COMMON/SPACECRAFT/INDUSTRIAL/SHARED/DECALS/STRIPE_SINGLE.TEXTURE.MBIN",
            "TEXTURES/COMMON/SPACECRAFT/SCIENTIFIC/SHARED/SCIENTIFIC.TEXTURE.MBIN",
            "TEXTURES/COMMON/SPACECRAFT/SHARED/DECALS/DECALPAINT.TEXTURE.MBIN",
            "TEXTURES/COMMON/SPACECRAFT/SHARED/DECALS/LOGO.TEXTURE.MBIN",
            "TEXTURES/COMMON/SPACECRAFT/SHARED/DECALS/PATTERNS.TEXTURE.MBIN",
            "TEXTURES/COMMON/SPACECRAFT/SHARED/DECALS/SMALLDECAL.TEXTURE.MBIN",
            "TEXTURES/COMMON/SPACECRAFT/SHUTTLE/SHARED/SHUTTLE.TEXTURE.MBIN",
            "TEXTURES/COMMON/SPACECRAFT/SHUTTLE/SHARED/SHUTTLEDECALSHEET.TEXTURE.MBIN",
            "TEXTURES/COMMON/WEAPONS/GUNTEXTURE.TEXTURE.MBIN",
            "TEXTURES/COMMON/WEAPONS/LED.TEXTURE.MBIN",
            "TEXTURES/COMMON/WEAPONS/MULTITOOLLED.TEXTURE.MBIN",
            "TEXTURES/COMMON/WEAPONS/MULTITOOLTEXTURE.TEXTURE.MBIN",
            "TEXTURES/COMMON/WEAPONS/SCREEN2.TEXTURE.MBIN",
            "TEXTURES/COMMON/WEAPONS/MULTITOOL/BONETILING.TEXTURE.MBIN",
            "TEXTURES/COMMON/WEAPONS/MULTITOOL/CRYSTAL.TEXTURE.MBIN",
            "TEXTURES/COMMON/WEAPONS/MULTITOOL/FLESHTILING.TEXTURE.MBIN",
            "TEXTURES/COMMON/WEAPONS/MULTITOOL/LAZERMUZZLEFLASH.TEXTURE.MBIN",
            "TEXTURES/COMMON/WEAPONS/MULTITOOL/MULTITOOLALTTRIM.TEXTURE.MBIN",
            "TEXTURES/COMMON/WEAPONS/MULTITOOL/MULTITOOLBASE.TEXTURE.MBIN",
            "TEXTURES/COMMON/WEAPONS/MULTITOOL/MULTITOOLDECALS_1.TEXTURE.MBIN",
            "TEXTURES/COMMON/WEAPONS/MULTITOOL/MULTITOOLOVERLAY.TEXTURE.MBIN",
            "TEXTURES/COMMON/WEAPONS/MULTITOOL/MULTITOOLTRIM.TEXTURE.MBIN",
            "TEXTURES/COMMON/WEAPONS/MULTITOOL/MUZZLEFLASH.TEXTURE.MBIN",
            "TEXTURES/COMMON/WEAPONS/MULTITOOL/PRESTINEDECALS.TEXTURE.MBIN",
            "TEXTURES/COMMON/WEAPONS/MULTITOOL/PRESTINETILED.TEXTURE.MBIN",
            "TEXTURES/COMMON/WEAPONS/MULTITOOL/SCREENGLOW.TEXTURE.MBIN",
            "TEXTURES/COMMON/WEAPONS/MULTITOOL/SCREENLIGHTS.TEXTURE.MBIN",
            "TEXTURES/COMMON/WEAPONS/MULTITOOL/SMALLDECALSHEET.TEXTURE.MBIN",
            "TEXTURES/COMMON/WEAPONS/MULTITOOL/SPINE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/ALIEN/MEDIUMPLANT/MEDIUMPLANT01.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/ALIEN/MEDIUMPLANT/MEDIUMPLANT02.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/ALIEN/MEDIUMPLANT/MEDPLANT02ROOT.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/ALIEN/MEDIUMPROP/MEDPROP01.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/ALIEN/SMALLPLANT/SMALLPLANT02.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/ALPINE/LARGEPLANT/FIR2TEXTURE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/ALPINE/SMALLPLANT/FERN01.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/ALPINE/SMALLPLANT/SMALLWEED01.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/BARREN/PLANTS/BARRENFLOWERS.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/BARREN/PLANTS/CACTUS.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/BARREN/PLANTS/CACTUSBARK.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/BARREN/PLANTS/CACTUSBARKLIGHT.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/BARREN/PLANTS/CACTUSFLAT.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/BARREN/PLANTS/CACTUSTILE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/BARREN/PLANTS/CACTUSTILE2.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/BARREN/PLANTS/FLUFFBUSH.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/BARREN/PLANTS/FLUFFBUSHFLOWER.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/BARREN/PLANTS/FLUFFBUSHLONG.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/BARREN/PLANTS/FLUFFBUSHWEIRDLONG.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/BARREN/PLANTS/GRASSBILLBOARD.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/BARREN/PLANTS/GROUNDUPDECAL.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/BARREN/PLANTS/SCRUBBUSH.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/BARREN/PLANTS/SCRUBGRASS.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/BARREN/PLANTS/SCRUBGRASS2.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/BARREN/PLANTS/SCRUBGRASS3.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/BARREN/PLANTS/SCRUBGRASS4.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/BARREN/PLANTS/SCRUBGRASS5.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/BARREN/PLANTS/SCRUBGRASS6.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/BARREN/PLANTS/SCRUBGRASS7.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/BARREN/PLANTS/SCRUBGRASSBASE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/BARREN/PLANTS/VOLUMEBUSH.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/BARREN/ROCKS/BARRENROCK.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/BARREN/ROCKS/STACKROCKTILING.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/CAVE/LARGEPROP/ANGULARROCK01.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/CAVE/LARGEPROP/FUNGHI1.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/CAVE/LARGEPROP/FUNGHI2.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/CAVE/LARGEPROP/FUNGHI3.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/CAVE/LARGEPROP/FUNGHI4.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/CAVE/LARGEPROP/GIANTSTALAGMITE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/CAVE/LARGEPROP/MINERALROCK.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/CAVE/LARGEPROP/ROCKTOWERSMALL.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/CAVE/LARGEPROP/ROCKTOWERTILING.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/CAVE/LARGEPROP/STALAGMITE01.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/CAVE/LARGEPROP/STALAGMITEMOSS01.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/CAVE/LARGEPROP/STALAGTITE01.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/CAVE/LARGEPROP/TILINGLAVA.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/CAVE/MEDIUMPROP/CAVEPLANTLEAF.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/CAVE/MEDIUMPROP/GLOWINGBULB.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/CAVE/MEDIUMPROP/LIGHTCOLOUR.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/CAVE/MEDIUMPROP/MEDIUMGLOWPLANT.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/CAVE/MEDIUMPROP/MEDIUMPLANT.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/CAVE/MEDIUMPROP/PLANTBASE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/CAVE/MEDIUMPROP/ROCKPOOLTILING.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/CAVE/MEDIUMPROP/ROCKPOOLTILINGA.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/CAVE/MEDIUMPROP/STALAGMITEMED01.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/CAVE/MEDIUMPROP/STALAGMITEMOSSMED01.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/CAVE/SMALLPLANT/CAVEBUSH.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/CAVE/SMALLPROP/CLOVERCLUMP.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/CAVE/SMALLPROP/CLOVERPLANTBASE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/CAVE/SMALLPROP/MOSS01.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/CAVE/SMALLPROP/MUSHROOM01.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/CAVE/SMALLPROP/ROCKPOOL01.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/CAVE/SMALLPROP/SHRUBPLANT.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/CAVE/SMALLPROP/STALAGMITETINY01.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/CAVE/SMALLPROP/TILINGMOSS01.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/BARK/BARKGROUNDDECAL.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/BARK/BARRENBARK.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/BARK/CAPS.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/BARK/WOODLANDBARK.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/BUILDINGS/DISTRESSSIGNAL/FLAG.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/BUILDINGS/DISTRESSSIGNAL/FLAG_2.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/BUILDINGS/LUNAR/LUNARDECAL.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/BUILDINGS/LUNAR/LUNARTILE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/BUILDINGS/PROPS/INTERIORPROPS/CREATURECHAMBER.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/BUILDINGS/PROPS/INTERIORPROPS/FAN.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/BUILDINGS/PROPS/INTERIORPROPS/INTERIORPROPS.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/BUILDINGS/PROPS/INTERIORPROPS/SCREENS.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/BUILDINGS/RUINS/MAINTILE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/BUILDINGS/RUINS/WALLTILE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/BUILDINGS/RUINS/DECALS/PLANTDECAL.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/BUILDINGS/RUINS/DECALS/WALLOVERLAY.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/BUILDINGS/RUINS/TILING/METALTILING.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/BUILDINGS/RUINS/TILING/RUINWALLTILING.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/BUILDINGS/RUINS/TILING/RUINWALLTILING_2.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/BUILDINGS/SHARED/RUINS/RUINTILED.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/BUILDINGS/SHARED/SCIENTIFICBUILDINGS/SCIENTIFICDECALS.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/BUILDINGS/SHARED/SCIENTIFICBUILDINGS/SCIENTIFICFACTORYGLOW.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/BUILDINGS/SHARED/SCIENTIFICBUILDINGS/SCIENTIFICTILED.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/BUILDINGS/SHARED/SCIENTIFICBUILDINGS/SCIENTIFICTILEDINTERIOR.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/BUILDINGS/SHARED/TRADER/TRADERTILLED.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/BUILDINGS/SHARED/WARRIOR/WARRIORTILED.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/BUILDINGS/TERMINAL/INFECTIONDECAL.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/BUILDINGS/TERMINAL/INFECTIONTILE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/BUILDINGS/TERMINAL/MEMBRANE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/CRYSTALS/CRYSTALCUBES.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/GRASS/BLOBBYGRASS01.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/GRASS/GRASSVARIATION01.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/GRASS/LUSHGRASS1.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/GRASS/LUSHGRASS1B.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/GRASS/LUSHGRASS2.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/GRASS/LUSHGRASS2B.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/GRASS/LUSHGRASS3.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/GRASS/LUSHGRASS3B.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/GRASS/LUSHGRASS4.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/GRASS/LUSHGRASS4B.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/GRASS/LUSHGRASS5.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/GRASS/LUSHGRASS5B.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/GRASS/LUSHGRASS6.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/GRASS/LUSHGRASS6B.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/GRASS/LUSHGRASS7.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/GRASS/LUSHGRASS7B.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/GRASS/LUSHGRASS8.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/GRASS/LUSHGRASS8B.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/GRASS/PROCGRASS.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/GRASS/PROCGRASS4.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/GRASS/TALLGRASS1.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/GRASS/TALLGRASS2.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/GRASS/TALLGRASS3.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/GRASS/TALLGRASS4.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/GRASS/TALLGRASS5.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/GRASS/THINGRASS01.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/GRASS/WIDELUSHGRASS01.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/GRASS/WILDGRASS01.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/GRASS/TESTS/CUTOUTGRASS.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/BERRYPLANT.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/COMMODITYPLANT.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/EXPLODEPLANT.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/FLESH.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/FLESHSHELL.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/FRUIT1.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/FRUITA.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/FRUITALEAVES.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/FRUITALTBCOLOUR1.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/FRUITALTBCOLOUR2.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/FRUITALTBCOLOUR3.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/FRUITALTCCOLOUR1.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/FRUITALTCCOLOUR2.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/FRUITALTCCOLOUR3.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/FRUITALTCOLOUR1.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/FRUITALTCOLOUR2.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/FRUITALTCOLOUR3.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/FRUITAPETALS.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/FRUITB.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/FRUITBLUE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/FRUITBLUE2.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/FRUITBLUE3BERRY.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/FRUITSTALK.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/FRUITYELLOW.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/FRUITYELLOW3BERRY.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/LARGEFLOWERHEAD.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/SHELL.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/STALKA.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/TENTACLEPLANT.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/TENTACLEPLANTLEAF.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/COMMODITY/COMFLOWER.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/COMMODITY/COMLEAVES.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/COMMODITY/COMPETALS.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/COMMODITY/COMSTALK.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/FUEL/FUELFLOWER.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/FUEL/FUELFRUIT1.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/FUEL/FUELFRUIT2.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/FUEL/FUELLEAVES.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/FUEL/FUELPETALS.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/FUEL/FUELSTALK.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/FUEL/FUELSTALK2.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/HAZARD/HAZFLOWER.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/HAZARD/HAZLEAVES.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/HAZARD/HAZPETALS.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/HAZARD/HAZSTALK.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/HEALTH/HEALTHFLOWER.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/HEALTH/HEALTHFRUIT.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/HEALTH/HEALTHLEAVES.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/HEALTH/HEALTHPETALS.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/HEALTH/HEALTHPLANT.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/HEALTH/HEALTHSTALK.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/PROXIMITYPLANT/WEIRDBALL.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/SHIELD/SHIELDFLOWER.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/SHIELD/SHIELDFRUIT.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/SHIELD/SHIELDLEAVES.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/SHIELD/SHIELDPETALS.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/SHIELD/SHIELDSTALK.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/TECH/TECHFLOWER.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/TECH/TECHFRUIT.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/TECH/TECHLEAVES.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/TECH/TECHPETALS.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/INTERACTIVEFLORA/TECH/TECHSTALK.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/LEAVES/FRONDS/FROND.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/LEAVES/FRONDS/LEAFFRUIT.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/LEAVES/FRONDS/SQUAREFROND.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/LEAVES/HANGING/HANGINGLEAVESA.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/LEAVES/LEAVES/CROSSLEAF.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/LEAVES/LEAVES/LEAF.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/LEAVES/LEAVES/MEDIUMLEAFA.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/LEAVES/LEAVES/MEDIUMLEAFB.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/LEAVES/LEAVES/SINGLELEAF.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/PLANTS/FLOWERHEAD.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/PLANTS/FLOWERSTALKLEAVES.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/PLANTS/FOLDPLANT.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/PLANTS/MEDIUMBRANCHPLANT.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/PLANTS/PETALCOB.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/PLANTS/SMALLPLANTA.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/PLANTS/SMALLPLANTB.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/RARERESOURCE/CAVE/EGGCORE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/RARERESOURCE/CAVE/EGGSHELL.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/RARERESOURCE/CAVE/SLIME.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/RARERESOURCE/UNDERWATER/SEAURCHIN.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/ROCKS/LARGE/LARGEROCK.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/ROCKS/LARGE/TILINGLUMP.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/ROCKS/MEDIUM/MEDIUMSLATE01.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/ROCKS/MEDIUM/MEDIUMTILINGROCKA.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/ROCKS/MEDIUM/MEDROCKS.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/ROCKS/MEDIUM/ROCKTOWER.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/ROCKS/MEDIUM/SUBSTANCE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/ROCKS/SMALL/SMALLSLATE01.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/COMMON/ROCKS/SMALL/TINYSLATE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/CORAL/LARGEPROP/CORALBASE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/CORAL/LARGEPROP/CORALSPIKE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/CORAL/LARGEPROP/LARGECORAL.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/CORAL/LARGEPROP/LIMPET.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/CORAL/LARGEPROP/SCALLOP.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/CORAL/MEDIUMPROP/CORALDISC.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/CRYSTAL/LARGEPLANT/STRANDS.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/CRYSTAL/LARGEPROP/MINERAL1.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/CRYSTAL/LARGEPROP/MODULARROCKS.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/CRYSTAL/LARGEPROP/TILINGROCK.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/FROZEN/LARGEPROPS/BARKSNOWDECAL.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/FROZEN/LARGEPROPS/FROSTLEAF.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/FROZEN/LARGEPROPS/HANGINGICICLES.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/FROZEN/LARGEPROPS/ICEROCK.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/FROZEN/LARGEPROPS/ICETILING.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/FROZEN/LARGEPROPS/PINELEAF.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/FROZEN/LARGEPROPS/ROCKTILING.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/FROZEN/LARGEPROPS/SMOOTHROCKTILING.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/FROZEN/LARGEPROPS/SNOWBILLLEAF.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/FROZEN/LARGEPROPS/SNOWFROND.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/FROZEN/LARGEPROPS/SNOWTILING.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/FROZEN/LARGEPROPS/SNOWTREEBASE2.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/FROZEN/LARGEPROPS/TILINGROCKA.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/FROZEN/LARGEPROPS/TREEBASE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/FROZEN/MEDIUMPROPS/FROZENLEAF_1.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/FROZEN/MEDIUMPROPS/MEDIUMROCK_1.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/FROZEN/SMALLPROPS/ICEFORMATION.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/GLOWING/LARGEPLANT/GLOWINGTREELEAVES01.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/GLOWING/LARGEPLANT/GLOWINGTREESHAFT.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/GLOWING/SMALLPLANT/SCRUBGRASS01.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/NEVADA/SMALLPLANTS/SMALLBUSH01.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/NEVADA/SMALLPLANTS/SMALLSHRUB_02.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/RADIOACTIVE/LARGE/CURVEDROCK.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/RADIOACTIVE/LARGE/GROWTH.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/RADIOACTIVE/LARGE/RADIOFROND.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/RADIOACTIVE/LARGE/TREEBARK.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/RADIOACTIVE/LARGE/TREEVINES.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/RAINFOREST/GRASS/GRASSSPIKE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/RAINFOREST/LARGEPLANT/BUSHLEAF2.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/RAINFOREST/LARGEPLANT/GIANTLILY.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/RAINFOREST/LARGEPLANT/IVY01.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/RAINFOREST/LARGEPLANT/LARGEPLANT1.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/RAINFOREST/LARGEPLANT/MEDIUMTREE2TRUNK.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/RAINFOREST/LARGEPLANT/PALMLEAF.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/RAINFOREST/LARGEPLANT/PALMLEAF2.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/RAINFOREST/LARGEPLANT/SMALLTREE1TRUNK.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/RAINFOREST/LARGEPLANT/SMALLTREE3.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/RAINFOREST/LARGEPLANT/SOLIDLEAF.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/RAINFOREST/LARGEPLANT/VINEPLANE01.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/RAINFOREST/MEDIUMPLANT/CHEESEPLANTLEAF.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/RAINFOREST/MEDIUMPLANT/FERNSTALK.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/RAINFOREST/MEDIUMPLANT/MEDIUMPLANT2.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/RAINFOREST/MEDIUMPLANT/MEDIUMPLANT6.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/RAINFOREST/MEDIUMPLANT/MEDIUMPLANT6_LEAF.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/RAINFOREST/MEDIUMPLANT/MEDIUMPLANT7.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/RAINFOREST/MEDIUMPLANT/MEDIUMPLANT7_LEAF.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/RAINFOREST/MEDIUMPLANT/MEDPLANT1LEAF.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/RAINFOREST/MEDIUMPLANT/MEDPLANT1TRUNK.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/RAINFOREST/MEDIUMPROP/MEDIUMROCK1.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/RAINFOREST/SMALLPLANT/SMALLFLOWER01.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/RAINFOREST/SMALLPLANT/SMALLPLANT1.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/RAINFOREST/SMALLPLANT/SMALLPLANT2.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/RAINFOREST/SMALLPLANT/SMALLTREE3.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/SCORCHED/LARGE/LARGEROCK.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/SCORCHED/LARGE/LARGESPIRE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/SCORCHED/LARGE/SPIRELEAF.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/SCORCHED/LARGE/SPIRELEAFALT1.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/SCORCHED/MEDIUM/FEELER.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/SCORCHED/MEDIUM/LAVALEAF.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/SCORCHED/MEDIUM/MEDIUMSPIRELEAF.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/SCORCHED/MEDIUM/MEDIUMSPIREPLANT.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/SCORCHED/MEDIUM/VOLCANICPLANT.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/SCORCHED/SMALL/LEAFDROPLET.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/SCORCHED/SMALL/SMALLSPIRELEAF.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/SWAMP/LARGEPROP/BOULDER01.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/SWAMP/LARGEPROP/BOULDER02.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/TOXIC/LARGE/BLOBPETAL.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/TOXIC/LARGE/BLOBSTALK.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/TOXIC/LARGE/FUNGALTREE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/TOXIC/LARGE/MINITILEA.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/TOXIC/LARGE/MUSHROOM.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/TOXIC/LARGE/MUSHROOMB.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/TOXIC/LARGE/SPONGE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/TOXIC/LARGE/TENDRILS.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/TOXIC/LARGE/TILINGA.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/TOXIC/LARGE/TILINGB.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/TOXIC/LARGE/TILINGC.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/TOXIC/LARGE/TILINGTENDRIL.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/TOXIC/MEDIUM/BLOBTEST.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/TOXIC/SMALL/SHROOMGRASS.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/TOXIC/SMALL/TOXICGRASSLEAF.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/UNDERWATER/LARGEPROP/ATTACHMENTSPONGE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/UNDERWATER/LARGEPROP/LARGEPLATFORMROCK.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/UNDERWATER/LARGEPROP/LARGEPLATFORMROCKPLATES.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/UNDERWATER/LARGEPROP/LARGESPIKEROCK.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/UNDERWATER/LARGEPROP/LARGESWIRLPLANT.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/UNDERWATER/LARGEPROP/LARGETUBEROCK.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/UNDERWATER/LARGEPROP/LIQUIDSCROLL.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/UNDERWATER/LARGEPROP/SMALLGROWTHATTACHMENT.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/UNDERWATER/LARGEPROP/TILINGLUMP.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/UNDERWATER/MEDIUMPLANT/ALPHASTRANDSTILE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/UNDERWATER/MEDIUMPLANT/FLOATLEAF.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/UNDERWATER/MEDIUMPLANT/MEDIUMGLOWPLANT.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/UNDERWATER/MEDIUMPLANT/MEDIUMGLOWPLANTSEAWEED.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/UNDERWATER/MEDIUMPLANT/MEDIUMJELLYPLANT.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/UNDERWATER/MEDIUMPLANT/SPHERETILE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/UNDERWATER/MEDIUMPLANT/STRANDTILE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/UNDERWATER/SMALLPLANT/SEABUSH.TEXTURE.MBIN",
            "TEXTURES/PLANETS/BIOMES/UNDERWATER/SMALLPLANT/SMALLGLOWBULB.TEXTURE.MBIN",
            "TEXTURES/PLANETS/COMMON/FLAGS/MARTIANFLAG01.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/ANTELOPERIG/ACC_BACKPLATES.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/ANTELOPERIG/ACC_BLOBS.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/ANTELOPERIG/ACC_BUBBLES.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/ANTELOPERIG/ACC_CLAWS1.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/ANTELOPERIG/ACC_EAR1.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/ANTELOPERIG/ACC_FINS.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/ANTELOPERIG/ACC_FURFEET.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/ANTELOPERIG/ACC_HEADFRILL.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/ANTELOPERIG/ACC_HEADPLATE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/ANTELOPERIG/ACC_HEADTENDTRILLS.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/ANTELOPERIG/ACC_SMALLHORNS1.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/ANTELOPERIG/ACC_TOUGHSKIN.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/ANTELOPERIG/ANTEATEREYE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/ANTELOPERIG/ANTEATER_HEAD.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/ANTELOPERIG/ANTELOPEBODY.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/ANTELOPERIG/ANTELOPEEAR.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/ANTELOPERIG/ANTELOPEHAIR.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/ANTELOPERIG/ANTELOPEHEAD.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/ANTELOPERIG/ANTELOPEHORN.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/ANTELOPERIG/ANTELOPELARGEHORN.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/ANTELOPERIG/BUFFALO_HEAD.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/ANTELOPERIG/FATTAIL.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/ANTELOPERIG/FAT_BODY.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/ANTELOPERIG/GREATDANEHEAD.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/ANTELOPERIG/GREATDANETAIL.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/ANTELOPERIG/GREATDANE_BODY.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/ANTELOPERIG/GREATDANE_HORN.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/ANTELOPERIG/TAIL_1.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/ANTELOPERIG/TAIL_2.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/ANTELOPERIG/TWOLEGANTEATER_HEAD.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/ANTELOPERIG/TWOLEGANTELOPEBODY.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/ANTELOPERIG/TWOLEGANTELOPEHEAD.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/ANTELOPERIG/TWOLEGBUFFALO_HEAD.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/ANTELOPERIG/TWOLEGCHICKENBODY.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/ANTELOPERIG/TWOLEGFAT_BODY.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/ANTELOPERIG/TWOLEGGREATDANE_BODY.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/ANTELOPERIG/TWOLEGROCKBODY.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/BLOBRIG/ANTENNAS.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/BLOBRIG/BLOBEEL.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/BLOBRIG/BLOWFISH.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/BLOBRIG/EYEBALLPLANT.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/BLOBRIG/FRILLFLAP.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/BLOBRIG/GILLS.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/BLOBRIG/HARDSCALPEYES.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/BLOBRIG/OCTO.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/BLOBRIG/OCTOHEAD.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/BLOBRIG/PLANTBASE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/BLOBRIG/ROUNDTEETHMOUTH.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/BLOBRIG/TENTACLE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/BUTTERFLYRIG/BUTTERFLY.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/BUTTERFLYRIG/BUTTERFLY2.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/BUTTERFLYRIG/BUTTERFLY3.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/BUTTERFLYRIG/BUTTERFLYBODY.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/CATRIG/ACCBACKFIN.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/CATRIG/ACCFINS.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/CATRIG/ACCSIDEFINS.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/CATRIG/ACCSMALLFINS.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/CATRIG/CATBODY.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/CATRIG/CATEARS.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/CATRIG/CATHEAD.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/CATRIG/CATTAIL.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/CATRIG/CATTONGUE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/CATRIG/LIONMANE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/CATRIG/LIZARDBODY.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/CATRIG/LIZARDEYE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/CATRIG/LIZARDHEAD.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/CATRIG/LIZARDTAIL.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/CATRIG/PREDATORCAT.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/CATRIG/PREDATORCATHEAD.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/CATRIG/PREDATORCATTAIL.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/CATRIG/PREDATOREYE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/CATRIG/SIXLEGCATBODY.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/CATRIG/SIXLEGLIZARDBODY.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/CATRIG/SIXLEGWOLFBODY.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/CATRIG/WARTHOGBODY.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/CATRIG/WARTHOGEARS.MBIN",
            "TEXTURES/PLANETS/CREATURES/CATRIG/WARTHOGEARS.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/CATRIG/WARTHOGEYE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/CATRIG/WARTHOGTAIL.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/CATRIG/WOLFBODY.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/CATRIG/WOLFHEAD.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/CATRIG/WOLFTAIL.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/COWRIG/ACCBACKSPINES.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/COWRIG/ACCFRILL.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/COWRIG/ACCMINERAL.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/COWRIG/ACCROCKMAIN.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/COWRIG/ACC_LARGELUMP.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/COWRIG/ALIENBIRDHEAD.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/COWRIG/ALIENTAIL.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/COWRIG/BIRDBEAKACC.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/COWRIG/BIRDHAMMERHEAD.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/COWRIG/BIRDHEADBONE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/COWRIG/BUGEYE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/COWRIG/BUGHEAD.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/COWRIG/BUGHEADACC.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/COWRIG/COWBODY.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/COWRIG/COWEARS.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/COWRIG/COWHEAD.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/COWRIG/COWTAIL.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/COWRIG/LORISHEAD.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/COWRIG/ORB.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/COWRIG/ROCKBODY.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/COWRIG/SIXLEGCOWBODY.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/COWRIG/SIXLEGROCKBODY.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/COWRIG/TREXFEET.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/COWRIG/TREXHEAD.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/COWRIG/TURTLETAIL.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/FISH/FISH_1.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/FLYINGLIZARDRIG/ACC_ARMOURPLATES.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/FLYINGLIZARDRIG/ACC_HEADPLATEL.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/FLYINGLIZARDRIG/ACC_HEADTENDRIL.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/FLYINGLIZARDRIG/BIRDHEAD.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/FLYINGLIZARDRIG/BIRDWINGS.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/FLYINGLIZARDRIG/EAGLE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/FLYINGLIZARDRIG/EAGLEEYE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/FLYINGLIZARDRIG/FLYINGLIZARD.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/FLYINGSNAKE/ACCFINS.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/FLYINGSNAKE/EEL.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/FLYINGSNAKE/FLYINGSNAKE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/FLYINGSNAKE/SANDWORM.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/GRUNTRIG/ACCROCKS.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/GRUNTRIG/BACKSHELL.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/GRUNTRIG/BEAK.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/GRUNTRIG/FACEPLATES.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/GRUNTRIG/FEATHER.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/GRUNTRIG/GRUNTBODY.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/GRUNTRIG/GRUNTCLAWS.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/GRUNTRIG/GRUNTEAR.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/GRUNTRIG/GRUNTEAR2.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/GRUNTRIG/GRUNTEYE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/GRUNTRIG/GRUNTFACESMALL.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/GRUNTRIG/GRUNTHAIR.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/GRUNTRIG/GRUNTHEAD.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/GRUNTRIG/GRUNTSCALEACC.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/GRUNTRIG/TURTLEGRUNT.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/GRUNTRIG/TURTLEGRUNTHEAD.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/RODENTRIG/BIRDEYE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/RODENTRIG/BIRDHEAD.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/RODENTRIG/BIRDTAIL.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/RODENTRIG/BODYRODENT.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/RODENTRIG/GREATDANEHEAD.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/RODENTRIG/HEADRODENT.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/RODENTRIG/HEADTAZ.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/RODENTRIG/LIZARD.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/RODENTRIG/LIZARDBODY.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/RODENTRIG/LIZARDHEAD.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/RODENTRIG/LIZARDSHELL.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/RODENTRIG/LIZARDTAIL.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/RODENTRIG/LIZARDTAILACC.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/RODENTRIG/RODENTEARS.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/RODENTRIG/SLOTHBODY_V2.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/RODENTRIG/SLOTHHEAD_V2.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/RODENTRIG/SLOTHTAIL_V2.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/RODENTRIG/TAILRODENT.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/RODENTRIG/TAILRODENTBUM.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/RODENTRIG/TAILRODENTMONKEY.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/RODENTRIG/TAPIRHEAD.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/RODENTRIG/TAZEARS.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/RODENTRIG/TURTLEHEAD.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/SHARED/LITTLEWINGS.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/SHARED/TILINGTENTACLE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/SHARKRIG/ACC_LARGEHORN.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/SHARKRIG/ACC_LARGESCALE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/SHARKRIG/ACC_SHARKHEADFRILL.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/SHARKRIG/ACC_SHARKSHELL.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/SHARKRIG/ACC_SHARKSPINE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/SHARKRIG/ACC_SMALLSPIKE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/SHARKRIG/ACC_SPIKYPLATES.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/SHARKRIG/ALIGATOR.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/SHARKRIG/SHELLSPIKE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/SHARKRIG/SWORDFISH.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/SHARKRIG/SWORDFISHEYE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/SHARKRIG/WHALE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/SMALLBIRD/BIRDBODYHEAD.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/SMALLBIRD/BIRDTAILS.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/SMALLBIRD/WINGS1.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/SMALLBIRD/WINGS2.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/SPIDERRIG/ALTHEADA.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/SPIDERRIG/ALTHEADB.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/SPIDERRIG/ALTLEGS.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/SPIDERRIG/BULBHAT.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/SPIDERRIG/BULBTOP.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/SPIDERRIG/CRAB.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/SPIDERRIG/CRABCLAW.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/SPIDERRIG/CRABHEAD.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/SPIDERRIG/CRABMANDABLE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/SPIDERRIG/FINFLAPS.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/SPIDERRIG/JELLYFINGERS.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/SPIDERRIG/MANTIS.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/SPIDERRIG/MANTISBODY.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/SPIDERRIG/MANTISHEAD.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/SPIDERRIG/MANTISLEGS.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/SPIDERRIG/MANTISNECK.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/SPIDERRIG/MANTISTAIL.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/SPIDERRIG/SHELLPLATE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/SPIDERRIG/SPIDEREYE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/SPIDERRIG/SUNBEETLE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/STRIDERRIG/ACC_BACKFINS.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/STRIDERRIG/ACC_WINGS.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/STRIDERRIG/BACKSPIKES.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/STRIDERRIG/BUGBODY.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/STRIDERRIG/BUGEYE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/STRIDERRIG/BUGHEAD.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/STRIDERRIG/BUGTAIL.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/STRIDERRIG/FISHHEAD.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/STRIDERRIG/FLATHEAD.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/STRIDERRIG/HEADBLOCKACC.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/STRIDERRIG/HEADFINACC.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/STRIDERRIG/JAWPLATEACC.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/STRIDERRIG/LONGTAIL.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/STRIDERRIG/STRIDERBODY.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/STRIDERRIG/STRIDERHEAD.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/STRIDERRIG/STRIDERTAIL.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/STRIDERRIG/STRIDERVARIANT1BODY.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/STRIDERRIG/STRIDERVARIANTHEAD.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/STRIDERRIG/STRIDERVARIANTTAIL.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TREXRIG/ACCKINGHEADPLATE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TREXRIG/ACCREXEAR.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TREXRIG/ACCTUSK.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TREXRIG/ACC_ANTLERSTUSK.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TREXRIG/ACC_EARHEADACCS.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TREXRIG/ACC_REXACCS.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TREXRIG/BIRDREXBODY.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TREXRIG/BIRDREXFEATHERS.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TREXRIG/BIRDREXHEAD.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TREXRIG/BIRDREXTAIL.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TREXRIG/BONEHORNACC.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TREXRIG/CROCHEAD.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TREXRIG/FURTEXTURE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TREXRIG/HEADBONE2ACC.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TREXRIG/HEADBONEACC.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TREXRIG/LIZARDHEAD.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TREXRIG/MOLENOSEACC.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TREXRIG/NOSEBONE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TREXRIG/NOSEBONE2.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TREXRIG/RAT.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TREXRIG/RATBODY.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TREXRIG/RATEARSACC.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TREXRIG/RATHEAD.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TREXRIG/RATTAIL.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TREXRIG/REXHEADPLATE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TREXRIG/REXSPIKEACCS.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TREXRIG/REXSPINESPIKE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TREXRIG/SMALLSPIKEACC.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TREXRIG/TILEABLEB.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TREXRIG/TOUCANBEAK.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TREXRIG/TOUCANHEAD.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TREXRIG/TOUCANTAIL.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TREXRIG/TREXBODY.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TREXRIG/TREXHEAD.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TREXRIG/TREXTAIL.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TREXRIG/TRIHEAD.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TRICERATOPSRIG/ACCFLANGE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TRICERATOPSRIG/ACCFLESHYSPINE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TRICERATOPSRIG/ACCFRILL.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TRICERATOPSRIG/ACCPLATEBODY.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TRICERATOPSRIG/ACCPLATEHEAD.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TRICERATOPSRIG/ACCRHINOHORNS.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TRICERATOPSRIG/ACCSPIKES.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TRICERATOPSRIG/ACCSPINES.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TRICERATOPSRIG/ALIENDIPLO.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TRICERATOPSRIG/ALIENHEADBASE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TRICERATOPSRIG/BONEHORN.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TRICERATOPSRIG/COLLAR.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TRICERATOPSRIG/DIPLO.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TRICERATOPSRIG/DIPLOHEAD.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TRICERATOPSRIG/DIPLOTAIL.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TRICERATOPSRIG/DISHHEAD.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TRICERATOPSRIG/DRAGONSPINEB.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TRICERATOPSRIG/GUMS.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TRICERATOPSRIG/HIPPOEAR.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TRICERATOPSRIG/HIPPOHEAD.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TRICERATOPSRIG/HIPPOHORNS.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TRICERATOPSRIG/HIPPOTAIL.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TRICERATOPSRIG/NOSE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TRICERATOPSRIG/RHINOEAR.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TRICERATOPSRIG/RHINOHEAD.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TRICERATOPSRIG/RHINOSTANDARDBODY.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TRICERATOPSRIG/RHINOTAIL.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TRICERATOPSRIG/STEGHEAD.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TRICERATOPSRIG/TAPIRBODY.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TRICERATOPSRIG/TAPIRHEAD.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TRICERATOPSRIG/TAPIRTAIL.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TRICERATOPSRIG/TILEABLEA.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TRICERATOPSRIG/TILEABLEB.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TRICERATOPSRIG/TILEABLEC.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TRICERATOPSRIG/TILEABLESKIN.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TRICERATOPSRIG/TRIBODY.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TRICERATOPSRIG/TRIHEAD.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TRICERATOPSRIG/TRITAIL.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TRICERATOPSRIG/TURTLEBODY.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TRICERATOPSRIG/TURTLEHEAD.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TRICERATOPSRIG/TURTLESHELL.TEXTURE.MBIN",
            "TEXTURES/PLANETS/CREATURES/TRICERATOPSRIG/TURTLETAIL.TEXTURE.MBIN",
            "TEXTURES/PLANETS/NPCS/EXPLORER/EXPLORER.TEXTURE.MBIN",
            "TEXTURES/PLANETS/NPCS/EXPLORER/EXPLORERDECALS.TEXTURE.MBIN",
            "TEXTURES/PLANETS/NPCS/EXPLORER/EXPLORERTRIM.TEXTURE.MBIN",
            "TEXTURES/PLANETS/NPCS/EXPLORER/EXPLORERVISOR.TEXTURE.MBIN",
            "TEXTURES/PLANETS/NPCS/FOURTHRACE/ALIENMOUTH.TEXTURE.MBIN",
            "TEXTURES/PLANETS/NPCS/FOURTHRACE/ALTALIENMOUTH.TEXTURE.MBIN",
            "TEXTURES/PLANETS/NPCS/FOURTHRACE/CATMOUTH.TEXTURE.MBIN",
            "TEXTURES/PLANETS/NPCS/FOURTHRACE/EAR.TEXTURE.MBIN",
            "TEXTURES/PLANETS/NPCS/FOURTHRACE/FLATEYES.TEXTURE.MBIN",
            "TEXTURES/PLANETS/NPCS/FOURTHRACE/FLATEYESALT.TEXTURE.MBIN",
            "TEXTURES/PLANETS/NPCS/FOURTHRACE/ROUNDEYES.TEXTURE.MBIN",
            "TEXTURES/PLANETS/NPCS/FOURTHRACE/ROUNDEYESLARGE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/NPCS/FOURTHRACE/SKULL.TEXTURE.MBIN",
            "TEXTURES/PLANETS/NPCS/FOURTHRACE/TOP.TEXTURE.MBIN",
            "TEXTURES/PLANETS/NPCS/LOWERORDER/BASEPLATE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/NPCS/LOWERORDER/EYEBASE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/NPCS/LOWERORDER/EYESTALKS.TEXTURE.MBIN",
            "TEXTURES/PLANETS/NPCS/LOWERORDER/LOWERORDER.TEXTURE.MBIN",
            "TEXTURES/PLANETS/NPCS/LOWERORDER/LOWERORDERDECALS.TEXTURE.MBIN",
            "TEXTURES/PLANETS/NPCS/LOWERORDER/LOWERORDEREYE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/NPCS/LOWERORDER/LOWERORDERMATERIALS.TEXTURE.MBIN",
            "TEXTURES/PLANETS/NPCS/LOWERORDER/SNOOD.TEXTURE.MBIN",
            "TEXTURES/PLANETS/NPCS/SHARED/GENERICSUIT.TEXTURE.MBIN",
            "TEXTURES/PLANETS/NPCS/SHARED/WARRIORSUIT.TEXTURE.MBIN",
            "TEXTURES/PLANETS/NPCS/WARRIOR/FACEPLATES.TEXTURE.MBIN",
            "TEXTURES/PLANETS/NPCS/WARRIOR/JAWFACE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/NPCS/WARRIOR/MOUTHCLAW.TEXTURE.MBIN",
            "TEXTURES/PLANETS/NPCS/WARRIOR/WARRIOR.TEXTURE.MBIN",
            "TEXTURES/PLANETS/NPCS/WARRIOR/WARRIOREYE.TEXTURE.MBIN",
            "TEXTURES/PLANETS/NPCS/WARRIOR/WARRIORGEM.TEXTURE.MBIN",
            "TEXTURES/PLANETS/OCEAN/SHRUBS/SEAFUNGI01.TEXTURE.MBIN",
            "TEXTURES/PLANETS/OCEAN/SHRUBS/TALLPLANT01.TEXTURE.MBIN",
            "TEXTURES/PLANETS/OCEAN/SHRUBS/TALLSEAWEED01.TEXTURE.MBIN",
            "TEXTURES/SPACE/ASTEROIDS/ASTEROID03.TEXTURE.MBIN",
            "TEXTURES/SPACE/ASTEROIDS/ASTEROID03LMARKS.TEXTURE.MBIN",
            "TEXTURES/SPACE/ASTEROIDS/CORE.TEXTURE.MBIN",
            "TEXTURES/SPACE/ASTEROIDS/VERTICAL.TEXTURE.MBIN",
            "TEXTURES/SPACE/SPACESTATION/DECALS/LETTERING.TEXTURE.MBIN",
            "TEXTURES/SPACE/SPACESTATION/DECALS/NUMBER.TEXTURE.MBIN",
            "TEXTURES/SPACE/SPACESTATION/SHARED/PRIMARY.TEXTURE.MBIN",
            "TEXTURES/SPACE/SPACESTATION/SHARED/SECONDARY.TEXTURE.MBIN",
            "TEXTURES/SPACE/SPACESTATION/SHARED/SPACESTATION.TEXTURE.MBIN",
            "TEXTURES/SPACE/SPACESTATION/SHARED/SPACESTATIONALT.TEXTURE.MBIN",
            "TEXTURES/SPACE/SPACESTATION/SHARED/TERTIARY.TEXTURE.MBIN",
            "TEXTURES/SPACE/SPACESTATION/SHARED/TRIANGLE_DECALS.TEXTURE.MBIN",
            "TEXTURES/TESTS/METALPROC.TEXTURE.MBIN",
            "TEXTURES/TESTS/PROCTEXTURETEST/FREIGHTER_PROC.TEXTURE.MBIN",
            "TEXTURES/TESTS/STRIDERTEST/LONGTAIL.TEXTURE.MBIN",
            "TEXTURES/TESTS/STRIDERTEST/STRIDERBODY.TEXTURE.MBIN",
            "TEXTURES/TESTS/TRICOLOURTEST/TESTHIPPOHEAD.TEXTURE.MBIN",
            "TEXTURES/TESTS/TRICOLOURTEST/TESTTRIBODY.TEXTURE.MBIN",
            "TEXTURES/TESTS/TRICOLOURTEST/TESTTURTLEBODY.TEXTURE.MBIN",
            "TEXTURES/UI/HUD/MENUS/ELEMENTGRADIENT.TEXTURE.MBIN",
        };

        private void decompileFile(string filePath, string output = "")
        {
            using (var file = new MBINFile(filePath))
            {
                file.Load();

                System.Diagnostics.Debug.WriteLine("testing " + filePath);
                var data = file.GetData();

                Assert.IsNotNull(data, filePath + " deserialized data was null");
                Assert.IsNotNull(data.SerializeEXml(), filePath + " xml serialization was null");
                var xmlString = EXmlFile.WriteTemplate(data);
                Assert.IsNotNull(xmlString, filePath + " xml data is null");

                if (!String.IsNullOrEmpty(output))
                {
                    if (File.Exists(output))
                        File.Delete(output);
                    File.WriteAllText(output, xmlString);
                }
            }
        }

        private void compileFile(string filePath, string output)
        {
            var data = EXmlFile.ReadTemplate(filePath);
            Assert.IsNotNull(data, filePath + " exml failed to deserialize");

            if (File.Exists(output))
                File.Delete(output); // todo: ask for confirmation?

            using (var file = new MBINFile(output))
            {
                file.Header = new MBINCompiler.Models.MBINHeader();
                file.Header.SetDefaults();
                if (data.GetType().Name == "TkGeometryData")
                    file.Header.Magic = 0xDDDDDDDD; // only used by TkGeometryData / .MBIN.PC files, maybe used to signal the file is PC only?

                file.SetData(data);
                file.Save();
            }
        }

        [TestMethod]
        public void should_successfully_decompile()
        {
            if (!Directory.Exists(baseDir))
                return; // fix for appveyor until we figure out how to skip tests

            foreach (var test in gameTestFiles)
            {
                var fullPath = Path.Combine(baseDir, test);
                if (!File.Exists(fullPath))
                    continue; // file might have been removed in an update

                decompileFile(fullPath);
            }
        }


        private string HashFile(string file)
        {
            using (var sha = System.Security.Cryptography.SHA1.Create())
            {
                using (var stream = File.OpenRead(file))
                {
                    return BitConverter.ToString(sha.ComputeHash(stream));
                }
            }
        }

        [TestMethod]
        public void should_successfully_recompile()
        {
            if (!Directory.Exists(baseDir))
                return; // fix for appveyor until we figure out how to skip tests

            foreach (var test in gameTestFiles)
            {
                var fullPath = Path.Combine(baseDir, test);
                if (!File.Exists(fullPath))
                    continue; // file might have been removed in an update

                if (File.Exists(fullPath + ".exml"))
                    File.Delete(fullPath + ".exml");
                if (File.Exists(fullPath + ".test"))
                    File.Delete(fullPath + ".test");
                if (File.Exists(fullPath + ".test.exml"))
                    File.Delete(fullPath + ".test.exml");

                decompileFile(fullPath, fullPath + ".exml");
                compileFile(fullPath + ".exml", fullPath + ".test");
                decompileFile(fullPath + ".test", fullPath + ".test.exml");

                string oldHash = HashFile(fullPath + ".exml");
                string newHash = HashFile(fullPath + ".test.exml");

                // check exml files match
                Assert.AreEqual(newHash, oldHash);

                // delete new files
                File.Delete(fullPath + ".exml");
                File.Delete(fullPath + ".test");
                File.Delete(fullPath + ".test.exml");
            }
        }
    }
}