namespace libMBIN.Models.Structs
{
    public class GcTechnologyTableEnum : NMSTemplate
    {
        public int Technology;
        public string[] TechnologyValues()
        {
            return new[] {"None", "PROTECT", "ENERGY", "JET1","JETBOOST1","JETBOOST2","JETBOOST3","UNW1",
        "UNW2", "UNW3","RAD1","RAD2","RAD3","TOX1","TOX2","TOX3","COLD1","COLD2","COLD3",
        "HOT1","HOT2","HOT3","SHIELDBOOST1","SHIELDBOOST2","SHIELDBOOST3","STAM1","STAM2",
        "STAM3","ENERGYBOOST1","ENERGYBOOST2","ARMOUR1","ARMOUR2","ARMOUR3","POWERGLOVE",
        "ATLASSUIT","SHIPLAS1","SHIPGUN1","SHIPSHOTGUN","SHIPMINIGUN","SHIPROCKETS",
        "SHIPPLASMA","SHIPSHIELD","SHIPJUMP","HYPERDRIVE","SHIPSCAN_ECON","SHIPSCAN_COMBAT",
        "SHIPLASCOOL1","SHIPLASCOOL2","SHIPLASCOOL3","SHIPLDMG1", "SHIPLDMG2","SHIPLDMG3",
        "SHIPGUNCOOL1","SHIPGUNCOOL2","SHIPGUNCOOL3","SHIPGUNRATE1","SHIPGUNRATE2",
        "SHIPGUNRATE3","SHIPGDMG1","SHIPGDMG2","SHIPGDMG3","SHIPSHLDBOOST1","SHIPSHLDBOOST2",
        "SHIPSHLDBOOST3","SHIPJUMP2","SHIPJUMP3","PHOTONIX_CORE","HDRIVEBOOST1","HDRIVEBOOST2","HDRIVEBOOST3",
        "LAUNCHER","F_HYPERDRIVE","F_HDRIVEBOOST1","F_HDRIVEBOOST2","F_HDRIVEBOOST3","LASER",
        "RAILGUN","BOLT","SHOTGUN","SMG","GRENADE","SCANBINOC1","SCAN1","TERRAINEDITOR",
        "STRONGLASER","LASMINERAD1","LASMINERAD2","LASMINERAD3","LASMINESPEED1","LASMINESPEED2",
        "LASMINESPEED3","LASCOOL1","LASCOOL2","LASCOOL3","LASDMG1","LASDMG2","LASDMG3",
        "LASDMG4","BOLTHOMING","BOLT_SM","BOLTDMG1","BOLTDMG2","BOLTDMG3","BOLTDMG4","BOLTRATE1",
        "BOLTRATE2","BOLTRATE3","BOLTCLIP1","BOLTCLIP2","BOLTCLIP3","BOLTREL1","BOLTREL2",
        "BOLTREL3","BOLTSTAB1","BOLTSTAB2","BOLTSTAB3","BOLTBOUNCE1","BOLTBOUNCE2","BOLTBOUNCE3",
        "GRENHOMING1","GRENBOUNCE1","GRENBOUNCE2","GRENSPEED1","GRENSPEED2","GRENRAD1","GRENRAD2",
        "GRENDMG1","GRENDMG2","GRENDMG3","SCAN2","SCAN3","CRESCAN1","CRESCAN2","CRESCAN3",
        "FLORASCAN1","FLORASCAN2","FLORASCAN3","SHIPSGUNDMG1","SHIPSGUNDMG2","SHIPSGUNDMG3",
        "SHIPSGUNRATE1","SHIPSGUNRATE2","SHIPSGUNRATE3","SHIPSGUNCOOL1","SHIPSGUNCOOL2",
        "SHIPSGUNCOOL3","SHIPMGUNDMG1","SHIPMGUNDMG2","SHIPMGUNDMG3","SHIPMGUNRATE1",
        "SHIPMGUNRATE2","SHIPMGUNRATE3","SHIPMGUNCOOL1","SHIPMGUNCOOL2","SHIPMGUNCOOL3",
        "SHIPBLOBDMG1","SHIPBLOBDMG2","SHIPBLOBDMG3","SHIPBLOBRATE1","SHIPBLOBRATE2",
        "SHIPBLOBRATE3","SHIPBLOBCOOL1","SHIPBLOBCOOL2","SHIPBLOBCOOL3","VEHICLE_ENGINE",
        "VEHICLE_SCAN","VEHICLE_SCAN1","VEHICLE_SCAN2","VEHICLE_BOOST","VEHICLE_BOOST1",
        "VEHICLE_BOOST2","VEHICLE_BOOST3","VEHICLE_LASER","VEHICLE_LASER1","VEHICLE_LASER2",
        "VEHICLE_LASER3","VEHICLE_GUN","VEHICLE_TRACT","VEHICLE_GUN1","RAILDMG1","RAILDMG2",
        "RAILDMG3","RAILCOOL1","RAILCOOL2","RAILMINE1","RAILMINE2","RAILMINE3","SHOTGUNDMG1",
        "SHOTGUNDMG2","SHOTGUNDMG3","SHOTGUNCLIP1","SHOTGUNCLIP2","SHOTGUNCLIP3","SHOTGUNREL1",
        "SHOTGUNREL2","SHOTGUNREL3","SHOTGUNACC1","SHOTGUNACC2","SHOTGUNACC3","SMGDMG1",
        "SMGDMG2","SMGDMG3","SMGACC1","SMGACC2","SMGACC3","SMGREL1","SMGREL2","SMGREL3",
        "MAINT_FARM1","MAINT_FARM2","MAINT_FARM3","MAINT_FARM4","MAINT_FARM5","MAINT_FUEL1",
        "MAINT_FUEL2","MAINT_FUEL3","MAINT_FUEL4","MAINT_FUEL5","MAINT_TECHEYE","MAINT_LOCKDOOR",
        "MAINT_TECH1","MAINT_TECH2","MAINT_TECH3","MAINT_TECH4","MAINT_TECH5","MAINT_TECH6",
        "MAINT_TECH7","MAINT_TECH8","MAINT_TECH9","MAINT_TECH10","MAINT_TECH11","MAINT_TECH12",
        "MAINT_TECH13","MAINT_TECH14","MAINT_TECH15","MAINT_TECH16","MAINT_TECH17","MAINT_TECH18",
        "MAINT_TECH19","MAINT_TECH20","MAINT_TECH21","MAINT_TECH22","MAINT_TECH23","MAINT_TECH24",
        "MAINT_TECH25","MAINT_PORTAL1","MAINT_PORTAL2","MAINT_PORTAL3","MAINT_PORTAL4",
        "MAINT_PORTAL5","MAINT_PORTAL6","MAINT_PORTAL7","MAINT_PORTAL8","MAINT_PORTAL9",
        "MAINT_PORTAL10","MAINT_PORTAL11","MAINT_PORTAL12","MAINT_PORTAL13","MAINT_PORTAL14",
        "MAINT_PORTAL15","MAINT_PORTAL16"};
        }
    }
}
