namespace MBINCompiler.Models.Structs.Unfinished
{
    public class GcEnvironmentGlobals : NMSTemplate
    {
        public GcCloudProperties Unknown0;
        public float UnknownF0;
        public float UnknownF4;
        public float UnknownF8;
        public float UnknownFC;
        public float Unknown100;
        public float Unknown104;
        public float Unknown108;
        public float Unknown10C;
        public float Unknown110;
        public float Unknown114;
        public float Unknown118;
        public float Unknown11C;
        public float Unknown120;
        public float Unknown124;
        public float Unknown128;
        public float Unknown12C;
        public float Unknown130;
        public float Unknown134;
        public float Unknown138;
        public float Unknown13C;
        public float Unknown140;
        public float Unknown144;
        public float Unknown148;
        public float Unknown14C;
        public float Unknown150;
        public float Unknown154;
        public int UnknownInt158;
        public float Unknown15C;
        public float Unknown160;
        public float Unknown164;
        public float Unknown168;
        public float Unknown16C;
        public float Unknown170;
        public float Unknown174;
        public float Unknown178;
        public float Unknown17C;
        public float Unknown180;
        public float Unknown184;
        public float Unknown188;
        /* 0x18C */ public float TerrainLODFadeSpeed;
        public float Unknown190;
        public float Unknown194;
        public float Unknown198;
        public float Unknown19C;
        public float Unknown1A0;
        public float Unknown1A4;
        public float Unknown1A8;
        public float Unknown1AC;
        public float Unknown1B0;
        public float Unknown1B4;
        public float Unknown1B8;
        public float Unknown1BC;
        public float Unknown1C0;
        public float Unknown1C4;
        public float Unknown1C8;
        /* 0x1CC */ public float MinCloudHeight;
        /* 0x1D0 */ public float MaxCloudHeight;
        public float Unknown1D4;
        public float Unknown1D8;
        public float Unknown1DC;
        public float Unknown1E0;
        public float Unknown1E4;
        public float Unknown1E8;
        public float Unknown1EC;
        public float Unknown1F0;
        public float Unknown1F4;
        public float Unknown1F8;
        public float Unknown1FC;
        /* 0x200 */ public float HiLODStartHeight;
        public float Unknown204;
        public float Unknown208;
        /* 0x20C */ public float PlanetActiveZoneHeight;
        /* 0x210 */ public float AtmosphericCloudsDrawDistance;
        public float Unknown214;
        public float Unknown218;
        public float Unknown21C;
        public float Unknown220;
        public float Unknown224;
        public float Unknown228;
        public float Unknown22C;
        public float Unknown230;
        public float Unknown234;
        public float Unknown238;
        public float Unknown23C;
        public float Unknown240;
        public float Unknown244;
        public float Unknown248;
        public float Unknown24C;
        public float Unknown250;
        public float Unknown254;
        public float Unknown258;
        public float Unknown25C;
        public float Unknown260;
        /* 0x264 */ public float MinBaseFogIntensity;
        /* 0x268 */ public float MaxBaseFogIntensity;
        public float Unknown26C;
        public float Unknown270;
        public float Unknown274;
        public float Unknown278;
        public float Unknown27C;
        public float Unknown280;
        public float Unknown284;
        public float Unknown288;
        public float Unknown28C;
        public float Unknown290;
        public float Unknown294;
        public float Unknown298;
        public float Unknown29C;
        public float Unknown2A0;
        public float Unknown2A4;
        public float Unknown2A8;
        /* 0x2AC */ public float SurfaceSunlightActiveHeight;
        public float Unknown2B0;
        public float Unknown2B4;
        public float Unknown2B8;
        public float Unknown2BC;
        public float Unknown2C0;
        public float Unknown2C4;
        public float Unknown2C8;
        public bool Unknown2CC;
        [NMS(Size = 0x3, Ignore = true)]
        public byte[] Padding2CD;

        public TkShearWindData WindData;
        public TkShearWindData StringWindData;
        public TkShearWindData UnderwaterWindData;
    }
}
