// generated output for subroutine:
// signed __int64 __fastcall raw_GcUIGlobals(__int64 a1) -----> hash: 21D52E2
// hash of whole input: 8AEA2A75

namespace MBINCompiler.Models.Structs
{
    public class GcUIGlobals : NMSTemplate // 0x3DE0
    {
        public bool Unknown0;
        public float Unknown4;
        public float Unknown8;
        public float UnknownC;
        public float Unknown10;
        public float Unknown14;
        public float Unknown18;
        public float Unknown1C;
        public float Unknown20;
        public float Unknown24;
        public float Unknown28;
        public float Unknown2C;
        public float Unknown30;
        public float Unknown34;
        public float Unknown38;
        public float Unknown3C;
        public float Unknown40;
        public float Unknown44;
        public float Unknown48;
        public float Unknown4C;
        public float Unknown50;
        public float Unknown54;
        public float Unknown58;
        public float Unknown5C;
        public float Unknown60;
        public float Unknown64;
        public float Unknown68;
        public float Unknown6C;
        public float Unknown70;
        public float Unknown74;
        public float Unknown78;
        public float Unknown7C;
        public float Unknown80;
        public float Unknown84;
        public float Unknown88;
        public float Unknown8C;
        public float Unknown90;
        public float Unknown94;
        public float Unknown98;
        public float Unknown9C;
        public float UnknownA0;
        public float UnknownA4;
        public float UnknownA8;
        public float UnknownAC;
        public float UnknownB0;
        public float UnknownB4;
        public int UnknownIntB8;
        public float UnknownBC;
        public float UnknownC0;
        public float UnknownC4;
        public float UnknownC8;
        public float UnknownCC;
        public float UnknownD0;
        public float UnknownD4;
        public float UnknownD8;
        public float UnknownDC;
        public float UnknownE0;
        public float UnknownE4;
        public float UnknownE8;
        public float UnknownEC;
        public float UnknownF0;
        public float UnknownF4;
        public float UnknownF8;
        public float UnknownFC;
        public float Unknown100;
        public float Unknown104;
        public float Unknown108;
        public float Unknown10C;
        public float Unknown110;
        public float Unknown114;
        public float Unknown118;
        public float Unknown11C;
        public float Unknown120;
        public float Unknown124;
        public float Unknown128;
        public float Unknown12C;
        public float Unknown130;
        public float Unknown134;
        public float Unknown138;
        public float Unknown13C;
        public float Unknown140;
        public float Unknown144;
        public float Unknown148;
        public float Unknown14C;
        public float Unknown150;
        public float Unknown154;
        public float Unknown158;
        public float Unknown15C;
        public float Unknown160;
        public float Unknown164;
        public float Unknown168;
        public float Unknown16C;
        public float Unknown170;
        public float Unknown174;
        public float Unknown178;
        public float Unknown17C;
        public float Unknown180;
        public float Unknown184;
        public float Unknown188;
        public float Unknown18C;
        public float Unknown190;
        public float Unknown194;
        public float Unknown198;
        public float Unknown19C;
        public float Unknown1A0;
        public float Unknown1A4;
        public float Unknown1A8;
        public float Unknown1AC;
        public float Unknown1B0;
        public float Unknown1B4;
        public float Unknown1B8;
        public float Unknown1BC;
        public float Unknown1C0;
        public float Unknown1C4;
        public float Unknown1C8;
        public float Unknown1CC;
        public float Unknown1D0;
        public float Unknown1D4;
        public float Unknown1D8;
        public float Unknown1DC;
        public float Unknown1E0;
        public float Unknown1E4;
        public float Unknown1E8;
        public float Unknown1EC;
        public float Unknown1F0;
        public float Unknown1F4;
        public float Unknown1F8;
        public float Unknown1FC;
        public float Unknown200;
        public float Unknown204;
        public float Unknown208;
        public float Unknown20C;
        public float Unknown210;
        public float Unknown214;
        public float Unknown218;
        public float Unknown21C;
        public float Unknown220;
        public float Unknown224;
        public float Unknown228;
        public float Unknown22C;
        public float Unknown230;
        public float Unknown234;
        public float Unknown238;
        public float Unknown23C;
        public float Unknown240;
        public float Unknown244;
        public float Unknown248;
        public float Unknown24C;
        public float Unknown250;
        public float Unknown254;
        public float Unknown258;
        public float Unknown25C;
        public float Unknown260;
        public float Unknown264;
        public float Unknown268;
        public float Unknown26C;
        public int UnknownInt270;
        public float Unknown274;
        public float Unknown278;
        public float Unknown27C;
        public float Unknown280;
        public float Unknown284;
        public float Unknown288;
        public float Unknown28C;
        public float Unknown290;
        public float Unknown294;
        public float Unknown298;
        public float Unknown29C;
        public float Unknown2A0;
        public int UnknownInt2A4;
        public float Unknown2A8;
        public float Unknown2AC;
        public float Unknown2B0;
        public float Unknown2B4;
        public float Unknown2B8;
        public float Unknown2BC;
        public float Unknown2C0;
        public float Unknown2C4;
        public float Unknown2C8;
        public float Unknown2CC;
        public float Unknown2D0;
        public float Unknown2D4;
        public float Unknown2D8;
        public float Unknown2DC;
        public float Unknown2E0;
        public float Unknown2E4;
        public float Unknown2E8;
        public float Unknown2EC;
        public float Unknown2F0;
        public float Unknown2F4;
        public float Unknown2F8;
        public float Unknown2FC;
        public float Unknown300;
        public float Unknown304;
        public float Unknown308;
        public float Unknown30C;
        public float Unknown310;
        public float Unknown314;
        public float Unknown318;
        public float Unknown31C;
        public float Unknown320;
        public float Unknown324;
        public float Unknown328;
        public float Unknown32C;
        public float Unknown330;
        public float Unknown334;
        public float Unknown338;
        public float Unknown33C;
        public float Unknown340;
        public float Unknown344;
        public float Unknown348;
        public float Unknown34C;
        public float Unknown350;
        public float Unknown354;
        public float Unknown358;
        public float Unknown35C;
        public float Unknown360;
        public float Unknown364;
        public float Unknown368;
        public float Unknown36C;
        public float Unknown370;
        public float Unknown374;
        public float Unknown378;
        public TkNGuiRectanglePulseEffect Unknown37C;
        public TkNGuiRectanglePulseEffect Unknown390;
        public float Unknown3A4;
        public float Unknown3A8;
        public float Unknown3AC;
        public float Unknown3B0;
        public float Unknown3B4;
        public float Unknown3B8;
        public float Unknown3BC;
        public float Unknown3C0;
        public float Unknown3C4;
        public float Unknown3C8;
        public float Unknown3CC;
        public float Unknown3D0;
        public float Unknown3D4;
        public int UnknownInt3D8;
        public bool Unknown3DC;
        public float Unknown3E0;
        public float Unknown3E4;
        public float Unknown3E8;
        public float Unknown3EC;
        public float Unknown3F0;
        public float Unknown3F4;
        public float Unknown3F8;
        public float Unknown3FC;
        public float Unknown400;
        public float Unknown404;
        public float Unknown408;
        public float Unknown40C;
        public float Unknown410;
        public float Unknown414;
        public float Unknown418;
        public float Unknown41C;
        public float Unknown420;
        public float Unknown424;
        public float Unknown428;
        public float Unknown42C;
        public float Unknown430;
        public float Unknown434;
        public float Unknown438;
        public float Unknown43C;
        public float Unknown440;
        public float Unknown444;
        public float Unknown448;
        public float Unknown44C;
        public float Unknown450;
        public float Unknown454;
        public float Unknown458;
        public float Unknown45C;
        public float Unknown460;
        public float Unknown464;
        public float Unknown468;
        public float Unknown46C;
        public float Unknown470;
        public float Unknown474;
        public float Unknown478;
        public float Unknown47C;
        public float Unknown480;
        public float Unknown484;
        public float Unknown488;
        public float Unknown48C;
        public float Unknown490;
        public float Unknown494;
        public float Unknown498;
        public float Unknown49C;
        public float Unknown4A0;

        [NMS(Size = 0x80)]
        public string Unknown4A4;
        [NMS(Size = 0x80)]
        public string Unknown524;
        [NMS(Size = 0x80)]
        public string Unknown5A4;
        [NMS(Size = 0x80)]
        public string Unknown624;
        [NMS(Size = 0x80)]
        public string Unknown6A4;
        [NMS(Size = 0x80)]
        public string Unknown724;
        [NMS(Size = 0x80)]
        public string Unknown7A4;
        [NMS(Size = 0x80)]
        public string Unknown824;
        [NMS(Size = 0x80)]
        public string Unknown8A4;
        [NMS(Size = 0x80)]
        public string Unknown924;
        [NMS(Size = 0x80)]
        public string Unknown9A4;
        [NMS(Size = 0x80)]
        public string UnknownA24;
        [NMS(Size = 0x80)]
        public string UnknownAA4;
        [NMS(Size = 0x80)]
        public string UnknownB24;
        [NMS(Size = 0x80)]
        public string UnknownBA4;
        [NMS(Size = 0x80)]
        public string UnknownC24;
        [NMS(Size = 0x80)]
        public string UnknownCA4;
        [NMS(Size = 0x80)]
        public string UnknownD24;
        [NMS(Size = 0x80)]
        public string UnknownDA4;
        [NMS(Size = 0x80)]
        public string UnknownE24;
        [NMS(Size = 0x80)]
        public string UnknownEA4;
        [NMS(Size = 0x80)]
        public string UnknownF24;
        [NMS(Size = 0x80)]
        public string UnknownFA4;
        [NMS(Size = 0x80)]
        public string Unknown1024;
        [NMS(Size = 0x80)]
        public string Unknown10A4;
        [NMS(Size = 0x80)]
        public string Unknown1124;
        [NMS(Size = 0x80)]
        public string Unknown11A4;
        [NMS(Size = 0x80)]
        public string Unknown1224;
        [NMS(Size = 0x80)]
        public string Unknown12A4;
        [NMS(Size = 0x80)]
        public string Unknown1324;
        [NMS(Size = 0x80)]
        public string Unknown13A4;
        [NMS(Size = 0x80)]
        public string Unknown1424;
        [NMS(Size = 0x80)]
        public string Unknown14A4;
        [NMS(Size = 0x80)]
        public string Unknown1524;
        [NMS(Size = 0x80)]
        public string Unknown15A4;
        [NMS(Size = 0x80)]
        public string Unknown1624;
        [NMS(Size = 0x80)]
        public string Unknown16A4;
        [NMS(Size = 0x80)]
        public string Unknown1724;
        [NMS(Size = 0x80)]
        public string Unknown17A4;
        [NMS(Size = 0x80)]
        public string Unknown1824;
        [NMS(Size = 0x80)]
        public string Unknown18A4;
        [NMS(Size = 0x80)]
        public string Unknown1924;
        [NMS(Size = 0x80)]
        public string Unknown19A4;
        [NMS(Size = 0x80)]
        public string Unknown1A24;
        [NMS(Size = 0x80)]
        public string Unknown1AA4;
        [NMS(Size = 0x80)]
        public string Unknown1B24;
        [NMS(Size = 0x80)]
        public string Unknown1BA4;
        [NMS(Size = 0x80)]
        public string Unknown1C24;
        [NMS(Size = 0x80)]
        public string Unknown1CA4;
        [NMS(Size = 0x80)]
        public string Unknown1D24;
        [NMS(Size = 0x80)]
        public string Unknown1DA4;
        [NMS(Size = 0x80)]
        public string Unknown1E24;
        [NMS(Size = 0x80)]
        public string Unknown1EA4;
        [NMS(Size = 0x80)]
        public string Unknown1F24;
        [NMS(Size = 0x80)]
        public string Unknown1FA4;

        public float Unknown2024;
        public int UnknownInt2028;
        public float Unknown202C;
        public float Unknown2030;
        public float Unknown2034;
        public float Unknown2038;
        public float Unknown203C;
        public float Unknown2040;
        public float Unknown2044;
        public float Unknown2048;
        public float Unknown204C;
        public float Unknown2050;
        public float Unknown2054;
        public float Unknown2058;
        public float Unknown205C;
        public float Unknown2060;
        public float Unknown2064;
        public float Unknown2068;
        public float Unknown206C;
        public float Unknown2070;
        public float Unknown2074;
        public float Unknown2078;
        public float Unknown207C;
        public float Unknown2080;
        public float Unknown2084;
        public float Unknown2088;
        public float Unknown208C;
        public float Unknown2090;
        public float Unknown2094;
        public float Unknown2098;
        public float Unknown209C;
        public float Unknown20A0;
        public float Unknown20A4;
        public float Unknown20A8;
        public float Unknown20AC;
        public float Unknown20B0;
        public float Unknown20B4;
        public float Unknown20B8;
        public float Unknown20BC;
        public float Unknown20C0;
        public float Unknown20C4;
        public float Unknown20C8;
        public float Unknown20CC;
        public float Unknown20D0;
        public float Unknown20D4;
        public float Unknown20D8;
        public float Unknown20DC;

        [NMS(Size = 0x20)]
        public string Unknown20E0;

        public float Unknown2100;
        public float Unknown2104;
        public float Unknown2108;
        public float Unknown210C;
        public float Unknown2110;
        public float Unknown2114;
        public float Unknown2118;
        public float Unknown211C;
        public float Unknown2120;
        public float Unknown2124;
        public float Unknown2128;
        public float Unknown212C;
        public float Unknown2130;
        public float Unknown2134;
        public float Unknown2138;
        public float Unknown213C;
        public float Unknown2140;
        public float Unknown2144;
        public float Unknown2148;
        public float Unknown214C;
        public float Unknown2150;
        public float Unknown2154;
        public float Unknown2158;
        public float Unknown215C;
        public float Unknown2160;
        public float Unknown2164;
        public float Unknown2168;
        public float Unknown216C;
        public float Unknown2170;
        public float Unknown2174;
        public float Unknown2178;
        public float Unknown217C;
        public float Unknown2180;
        public float Unknown2184;
        public float Unknown2188;
        public float Unknown218C;
        public float Unknown2190;
        public float Unknown2194;
        public float Unknown2198;
        public float Unknown219C;
        public float Unknown21A0;
        public float Unknown21A4;
        public float Unknown21A8;
        public float Unknown21AC;
        public float Unknown21B0;
        public float Unknown21B4;
        public float Unknown21B8;
        public float Unknown21BC;
        public float Unknown21C0;
        public float Unknown21C4;
        public float Unknown21C8;
        public float Unknown21CC;
        public float Unknown21D0;
        public float Unknown21D4;
        public float Unknown21D8;
        public float Unknown21DC;
        public float Unknown21E0;
        public float Unknown21E4;
        public float Unknown21E8;
        public float Unknown21EC;
        public float Unknown21F0;
        public float Unknown21F4;
        public float Unknown21F8;
        public float Unknown21FC;
        public float Unknown2200;
        public float Unknown2204;
        public float Unknown2208;
        public float Unknown220C;
        public float Unknown2210;
        public float Unknown2214;
        public float Unknown2218;
        public float Unknown221C;
        public float Unknown2220;
        public float Unknown2224;
        public float Unknown2228;
        public float Unknown222C;

        public bool Unknown2230;
        public bool Unknown2231;
        public bool Unknown2232;

        [NMS(Size = 0x20)]
        public string Unknown2233;
        [NMS(Size = 0x20)]
        public string Unknown2253;
        [NMS(Size = 0x1, Ignore = true)]
        public byte[] Padding2273;

        public float Unknown2274;
        public float Unknown2278;
        public float Unknown227C;
        public float Unknown2280;
        public float Unknown2284;
        public float Unknown2288;
        public float Unknown228C;
        public float Unknown2290;
        public float Unknown2294;
        public float Unknown2298;
        public float Unknown229C;
        public float Unknown22A0;
        public float Unknown22A4;

        [NMS(Size = 6, EnumValue = new string[6] { "None", "NoOxygen", "ExtremeHeat", "ExtremeCold", "ToxicGas", "Radiation" })]
        public NMSString0x80[] HazardEffects;

        [NMS(Size = 6, EnumValue = new string[6] { "None", "NoOxygen", "ExtremeHeat", "ExtremeCold", "ToxicGas", "Radiation" })]
        public NMSString0x80[] HazardEffectsNormal;

        [NMS(Size = 6, EnumValue = new string[6] { "None", "NoOxygen", "ExtremeHeat", "ExtremeCold", "ToxicGas", "Radiation" })]
        public NMSString0x80[] HazardEffectsRefraction;

        public float Unknown2BA8;
        public float Unknown2BAC;
        public float Unknown2BB0;
        public float Unknown2BB4;
        public float Unknown2BB8;
        public float Unknown2BBC;
        public float Unknown2BC0;
        public float Unknown2BC4;
        public float Unknown2BC8;
        public float Unknown2BCC;
        public float Unknown2BD0;
        public float Unknown2BD4;
        public float Unknown2BD8;
        public float Unknown2BDC;
        public float Unknown2BE0;
        public float Unknown2BE4;
        public float Unknown2BE8;
        public float Unknown2BEC;
        public float Unknown2BF0;
        public float Unknown2BF4;
        public float Unknown2BF8;
        public float Unknown2BFC;
        public float Unknown2C00;
        public float Unknown2C04;
        public float Unknown2C08;
        public float Unknown2C0C;
        public float Unknown2C10;
        public float Unknown2C14;
        public float Unknown2C18;
        public float Unknown2C1C;
        public float Unknown2C20;
        public float Unknown2C24;
        public float Unknown2C28;
        public float Unknown2C2C;
        public float Unknown2C30;
        public float Unknown2C34;
        public float Unknown2C38;
        public float Unknown2C3C;
        public float Unknown2C40;
        public float Unknown2C44;
        public float Unknown2C48;
        public float Unknown2C4C;
        public float Unknown2C50;
        public float Unknown2C54;
        public float Unknown2C58;
        public float Unknown2C5C;
        public float Unknown2C60;
        public float Unknown2C64;
        public float Unknown2C68;
        public float Unknown2C6C;

        public GcModelViewCollection Unknown2C70;

        public float Unknown3450;
        public float Unknown3454;
        public float Unknown3458;
        public float Unknown345C;
        public float Unknown3460;
        public float Unknown3464;
        public float Unknown3468;
        public float Unknown346C;
        public float Unknown3470;
        public float Unknown3474;
        public float Unknown3478;
        public float Unknown347C;
        public float Unknown3480;
        public float Unknown3484;
        public float Unknown3488;
        public float Unknown348C;
        public float Unknown3490;
        public float Unknown3494;
        public float Unknown3498;
        public float Unknown349C;
        public float Unknown34A0;
        public float Unknown34A4;
        public float Unknown34A8;
        public float Unknown34AC;
        public float Unknown34B0;
        public float Unknown34B4;
        public float Unknown34B8;
        public float Unknown34BC;
        public float Unknown34C0;
        public float Unknown34C4;
        public float Unknown34C8;
        public float Unknown34CC;
        public float Unknown34D0;
        public float Unknown34D4;
        public float Unknown34D8;
        public float Unknown34DC;
        public float Unknown34E0;
        public float Unknown34E4;
        public float Unknown34E8;
        public int UnknownInt34EC;
        public float Unknown34F0;
        public float Unknown34F4;
        public float Unknown34F8;
        public float Unknown34FC;
        public float Unknown3500;
        public float Unknown3504;
        public float Unknown3508;
        public float Unknown350C;
        public float Unknown3510;
        public float Unknown3514;
        public float Unknown3518;
        public float Unknown351C;
        public float Unknown3520;
        public float Unknown3524;
        public float Unknown3528;
        public float Unknown352C;
        public float Unknown3530;
        public float Unknown3534;
        public float Unknown3538;
        public float Unknown353C;
        public float Unknown3540;
        public float Unknown3544;
        public float Unknown3548;
        public float Unknown354C;
        public float Unknown3550;
        public float Unknown3554;
        public float Unknown3558;
        public float Unknown355C;
        public float Unknown3560;
        public float Unknown3564;
        public float Unknown3568;
        public float Unknown356C;
        public float Unknown3570;
        public float Unknown3574;
        public float Unknown3578;
        public float Unknown357C;
        public float Unknown3580;
        public float Unknown3584;
        public float Unknown3588;
        public float Unknown358C;
        public float Unknown3590;
        public float Unknown3594;
        public float Unknown3598;
        public float Unknown359C;
        public float Unknown35A0;
        public float Unknown35A4;
        public float Unknown35A8;
        public float Unknown35AC;
        public float Unknown35B0;
        public float Unknown35B4;
        public float Unknown35B8;
        public float Unknown35BC;
        public float Unknown35C0;
        public float Unknown35C4;
        public float Unknown35C8;
        public float Unknown35CC;
        public float Unknown35D0;
        public float Unknown35D4;
        public float Unknown35D8;
        public float Unknown35DC;
        public float Unknown35E0;
        public float Unknown35E4;
        public float Unknown35E8;
        public float Unknown35EC;
        public float Unknown35F0;
        public float Unknown35F4;
        public float Unknown35F8;
        public float Unknown35FC;
        public float Unknown3600;
        public float Unknown3604;
        public float Unknown3608;
        public float Unknown360C;
        public float Unknown3610;
        public float Unknown3614;
        public float Unknown3618;
        public float Unknown361C;
        public float Unknown3620;
        public float Unknown3624;
        public float Unknown3628;
        public float Unknown362C;
        public float Unknown3630;
        public float Unknown3634;
        public float Unknown3638;
        public float Unknown363C;
        public float Unknown3640;
        public float Unknown3644;
        public float Unknown3648;
        public float Unknown364C;
        public float Unknown3650;
        public float Unknown3654;
        public float Unknown3658;
        public float Unknown365C;

        public GcSpaceMapObjectData Unknown3660;
        public GcSpaceMapObjectData Unknown3690;
        public GcSpaceMapObjectData Unknown36C0;
        public GcSpaceMapObjectData Unknown36F0;
        public GcSpaceMapObjectData Unknown3720;

        public float Unknown3750;
        public float Unknown3754;
        public float Unknown3758;
        public float Unknown375C;
        public float Unknown3760;
        public float Unknown3764;
        public float Unknown3768;
        public float Unknown376C;
        public float Unknown3770;
        public float Unknown3774;
        public float Unknown3778;
        public float Unknown377C;
        public float Unknown3780;
        public float Unknown3784;
        public float Unknown3788;
        public float Unknown378C;
        public float Unknown3790;
        public float Unknown3794;
        public float Unknown3798;
        public float Unknown379C;
        public float Unknown37A0;
        public float Unknown37A4;
        public float Unknown37A8;
        public float Unknown37AC;
        public float Unknown37B0;
        public float Unknown37B4;
        public float Unknown37B8;
        public float Unknown37BC;
        public float Unknown37C0;
        public float Unknown37C4;
        public float Unknown37C8;
        public float Unknown37CC;
        public float Unknown37D0;
        public float Unknown37D4;
        public float Unknown37D8;
        public float Unknown37DC;

        [NMS(Size = 0x100)]
        public string Unknown37E0;
        [NMS(Size = 0x100)]
        public string Unknown38E0;
        [NMS(Size = 0x100)]
        public string Unknown39E0;
        [NMS(Size = 0x100)]
        public string Unknown3AE0;
        [NMS(Size = 0x100)]
        public string Unknown3BE0;
        [NMS(Size = 0x100)]
        public string Unknown3CE0;
        [NMS(Size = 0x100)]
        public string Unknown3DE0;
        [NMS(Size = 0x100)]
        public string Unknown3EE0;

        public float Unknown3FE0;
        public float Unknown3FE4;
        public float Unknown3FE8;
        public float Unknown3FEC;
        public float Unknown3FF0;
        public float Unknown3FF4;
        public float Unknown3FF8;
        public float Unknown3FFC;
        public float Unknown4000;
        public float Unknown4004;
        public float Unknown4008;
        public float Unknown400C;
        public float Unknown4010;
        public float Unknown4014;
        public float Unknown4018;
        public float Unknown401C;
        public float Unknown4020;
        public float Unknown4024;
        public float Unknown4028;
        public float Unknown402C;
        public float Unknown4030;
        public float Unknown4034;
        public float Unknown4038;
        public float Unknown403C;
        public float Unknown4040;
        public float Unknown4044;
        public float Unknown4048;
        public float Unknown404C;
        public float Unknown4050;
        public float Unknown4054;
        public float Unknown4058;
        public float Unknown405C;
        public float Unknown4060;
        public float Unknown4064;
        public float Unknown4068;
        public float Unknown406C;
        public float Unknown4070;
        public float Unknown4074;
        public float Unknown4078;
        public float Unknown407C;
        public float Unknown4080;
        public float Unknown4084;
        public float Unknown4088;
        public float Unknown408C;
        public float Unknown4090;
        public float Unknown4094;
        public float Unknown4098;
        public float Unknown409C;
        public float Unknown40A0;
        public float Unknown40A4;
        public float Unknown40A8;
        public float Unknown40AC;
        public float Unknown40B0;
        public float Unknown40B4;
        public float Unknown40B8;
        public float Unknown40BC;
        public float Unknown40C0;
        public float Unknown40C4;
        public float Unknown40C8;
        public float Unknown40CC;
        public float Unknown40D0;
        public float Unknown40D4;
        public float Unknown40D8;
        public float Unknown40DC;
        public float Unknown40E0;
        public float Unknown40E4;
        public float Unknown40E8;
        public float Unknown40EC;
        public float Unknown40F0;
        public float Unknown40F4;
        public float Unknown40F8;
        public float Unknown40FC;
        public float Unknown4100;
        public float Unknown4104;
        public float Unknown4108;
        public float Unknown410C;
        public float Unknown4110;
        public float Unknown4114;
        public float Unknown4118;
        public float Unknown411C;
        public float Unknown4120;
        public float Unknown4124;
        public float Unknown4128;
        public float Unknown412C;
        public float Unknown4130;
        public float Unknown4134;
        public float Unknown4138;
        public float Unknown413C;
        public float Unknown4140;
        public float Unknown4144;
        public float Unknown4148;
        public float Unknown414C;
        public float Unknown4150;
        public float Unknown4154;
        public float Unknown4158;
        public float Unknown415C;
        public float Unknown4160;
        public bool Unknown4164;
        public GcDiscoveryHelperTimings Unknown4168;

        public GcHUDStartupTable Unknown4174;

        public GcInventorySlotActionData Unknown41F4;
        public GcInventorySlotActionData Unknown4210;
        public GcInventorySlotActionData Unknown422C;
        public GcInventorySlotActionData Unknown4248;
        public GcInventorySlotActionData Unknown4264;
        public GcInventorySlotActionData Unknown4280;
        public float Unknown429C;
        public float Unknown42A0;
        public float Unknown42A4;
        public int UnknownInt42A8;
        public int UnknownInt42AC;
        public float Unknown42B0;
        public float Unknown42B4;
    }
}
