namespace MBINCompiler.Models.Structs
{
    public class GcPlayerGlobals : NMSTemplate
    {
        public bool Unknown0;
        public float Unknown4;
        public float Unknown8;
        public float UnknownC;
        public float Unknown10;
        public float Unknown14;
        public float Unknown18;
        [NMS(Size = 0x4, Ignore = true)]
        public byte[] Padding1C;
        public GcPlayerCommunicatorMessage Unknown20;
        public float Unknown48;
        public float Unknown4C;
        public float Unknown50;
        public float Unknown54;
        public int UnknownInt58;
        public float Unknown5C;
        public float Unknown60;
        public float Unknown64;
        public float Unknown68;
        public float Unknown6C;
        public float Unknown70;
        public float Unknown74;
        public float Unknown78;
        public float Unknown7C;
        public float Unknown80;
        public float Unknown84;
        public float Unknown88;
        public float Unknown8C;
        public float Unknown90;
        public float Unknown94;
        public float Unknown98;
        public float Unknown9C;
        public float UnknownA0;
        public float UnknownA4;
        public float UnknownA8;
        public float UnknownAC;
        public float UnknownB0;
        public float UnknownB4;
        public float UnknownB8;
        public float UnknownBC;
        public float UnknownC0;
        public float UnknownC4;
        public float UnknownC8;
        public float UnknownCC;
        public float UnknownD0;
        public float UnknownD4;
        /* 0xD8 */ public float JetpackSpeed;
        /* 0xDC */ public float JetpackJumpSpeed;
        public float UnknownE0;
        public float UnknownE4;
        public float UnknownE8;
        public float UnknownEC;
        public float UnknownF0;
        public float UnknownF4;
        public bool UnknownF8;
        public bool UnknownF9;      // maybe?
        public float UnknownFC;
        public float Unknown100;
        public float Unknown104;
        public float Unknown108;
        public float Unknown10C;
        public float Unknown110;
        public float Unknown114;
        public float Unknown118;
        public float Unknown11C;
        public float Unknown120;
        public float Unknown124;
        public float Unknown128;
        public float Unknown12C;
        public int UnknownInt130;
        public int UnknownInt134;
        public float Unknown138;
        public float Unknown13C;
        public float Unknown140;
        public float Unknown144;
        public float Unknown148;
        public float Unknown14C;
        public float Unknown150;
        public float Unknown154;
        public float Unknown158;
        public float Unknown15C;
        public float Unknown160;
        public float Unknown164;
        public float Unknown168;
        public float Unknown16C;
        public float Unknown170;
        public float Unknown174;
        public float Unknown178;
        public float Unknown17C;
        public float Unknown180;
        public float Unknown184;
        public float Unknown188;
        public float Unknown18C;
        public int UnknownInt190;       // two bools?
        public float Unknown194;
        public int UnknownInt198;
        public int UnknownInt19C;
        public float Unknown1A0;
        public float Unknown1A4;
        public float Unknown1A8;
        public float Unknown1AC;
        public float Unknown1B0;
        public float Unknown1B4;
        public float Unknown1B8;
        public float Unknown1BC;
        public float Unknown1C0;
        public float Unknown1C4;
        public float Unknown1C8;
        public float Unknown1CC;
        public float Unknown1D0;
        public float Unknown1D4;
        public int UnknownInt1D8;
        public int UnknownInt1DC;
        public float Unknown1E0;
        public float Unknown1E4;
        public int UnknownInt1E8;
        public float Unknown1EC;
        public float Unknown1F0;
        public float Unknown1F4;
        public float Unknown1F8;
        public float Unknown1FC;
        public float Unknown200;
        public float Unknown204;
        public float Unknown208;
        public float Unknown20C;
        public float Unknown210;
        public float Unknown214;
        public float Unknown218;
        public float Unknown21C;
        public float Unknown220;
        public float Unknown224;
        public float Unknown228;
        public float Unknown22C;
        public float Unknown230;
        public int UnknownInt234;
        public float Unknown238;
        public float Unknown23C;
        /* 0x240 */ public int BoltgunBaseAmmo;
        /* 0x244 */ public int DefaultGrenadeCapacity;
        public float Unknown248;
        public float Unknown24C;
        public float Unknown250;
        public int UnknownInt254;
        public float Unknown258;
        public float Unknown25C;
        public float Unknown260;
        public float Unknown264;
        public float Unknown268;
        public float Unknown26C;
        public float Unknown270;
        public float Unknown274;
        public float Unknown278;
        public float Unknown27C;
        public float Unknown280;
        public float Unknown284;
        public float Unknown288;
        public float Unknown28C;
        public float Unknown290;
        public float Unknown294;
        public float Unknown298;
        public float Unknown29C;
        public float Unknown2A0;
        public float Unknown2A4;
        public float Unknown2A8;
        public float Unknown2AC;
        public float Unknown2B0;
        public float Unknown2B4;
        public float Unknown2B8;
        public float Unknown2BC;
        public float Unknown2C0;
        /* 0x2C4 */ public float SprintStaminaDecreaseRate;
        /* 0x2C8 */ public float StaminaIncreaseRate;
        public float Unknown2CC;
        public float Unknown2D0;
        public float Unknown2D4;
        public float Unknown2D8;
        public float Unknown2DC;
        public float Unknown2E0;
        public float Unknown2E4;
        public float Unknown2E8;
        public float Unknown2EC;
        public float Unknown2F0;
        public float Unknown2F4;
        public float Unknown2F8;
        public float Unknown2FC;
        public float Unknown300;
        public float Unknown304;

        public float Unknown308;        // [rcx+308h], esi
        public float Unknown30C;
        public float Unknown310;
        public float Unknown314;
        public float Unknown318;
        public float Unknown31C;
        public float Unknown320;
        public float Unknown324;
        public float Unknown328;
        public float Unknown32C;
        public float Unknown330;
        public float Unknown334;
        public float Unknown338;

        public float Unknown33C;
        public float Unknown340;
        public float Unknown344;
        public float Unknown348;
        public float Unknown34C;
        public float Unknown350;
        public float Unknown354;
        public float Unknown358;
        public float Unknown35C;
        public float Unknown360;
        public float Unknown364;
        public float Unknown368;
        public float Unknown36C;
        public float Unknown370;
        public float Unknown374;
        public float Unknown378;
        public float Unknown37C;
        public float Unknown380;
        public float Unknown384;
        public float Unknown388;
        public float Unknown38C;
        public float Unknown390;
        public float Unknown394;
        public GcResourceCollectEffect Unknown398;
        public GcResourceCollectEffect Unknown3CC;
        public GcResourceCollectEffect Unknown400;
        public GcResourceCollectEffect Unknown434;
        public GcBoidData Unknown468;
        public float Unknown494;
        public float Unknown498;
        public float Unknown49C;
        public float Unknown4A0;
        public float Unknown4A4;
        public float Unknown4A8;
        public float Unknown4AC;
        public bool Unknown4B0;
        public float Unknown4B4;
        public float Unknown4B8;
        public float Unknown4BC;
        public float Unknown4C0;
        public float Unknown4C4;
        public float Unknown4C8;
        public float Unknown4CC;
        public float Unknown4D0;
        public float Unknown4D4;
        public int UnknownInt4D8;
        /* 0x4DC */ public float MiningLaserRange;
        public float Unknown4E0;
        public float Unknown4E4;
        public float Unknown4E8;
        public float Unknown4EC;
        public float Unknown4F0;
        public float Unknown4F4;
        public float Unknown4F8;
        public float Unknown4FC;
        public float Unknown500;
        public int UnknownInt504;
        public float Unknown508;
        public float Unknown50C;
        public float Unknown510;
        public float Unknown514;
        public float Unknown518;
        public float Unknown51C;
        public float Unknown520;
        public float Unknown524;
        public float Unknown528;
        public int UnknownInt52C;
        public float Unknown530;
        public float Unknown534;
        public float Unknown538;
        public float Unknown53C;
        public float Unknown540;
        public float Unknown544;
        public float Unknown548;
        public float Unknown55C;
        public float Unknown550;
        public float Unknown554;
        public float Unknown558;
        public float Padding55C;
        [NMS(Size = 0x80)]
        public string Unknown560;

        public float Unknown5E0;
        public float Unknown5E4;
        public int UnknownInt5E8;
        public float Unknown5EC;
        public float Unknown5F0;
        public float Unknown5F4;
        public float Unknown5F8;
        public float Unknown5FC;
        public float Unknown600;

        public GcCreatureAlertData Unknown604;
        public GcCreatureAlertData Unknown61C;
        public GcCreatureAlertData Unknown634;
        public GcCreatureAlertData Unknown64C;
        public GcCreatureAlertData Unknown664;
        public GcCreatureAlertData Unknown67C;
        public GcCreatureAlertData Unknown694;

        public float Unknown6AC;
        public float Unknown6B0;
        public float Unknown6B4;

        public GcProjectileLineData Unknown6B8;
        public GcProjectileLineData Unknown6E0;
        public GcProjectileLineData Unknown708;

        public float Unknown730;
        /* 0x734 */ public float Unknown734;
        /* 0X738 */ public float Unknown738;
        /* 0X73C */ public float Unknown73C;
        /* 0X740 */ public float Unknown740;
        /* 0X744 */ public float Unknown744;
        /* 0X748 */ public float Unknown748;
        /* 0X74C */ public float Unknown74C;
        /* 0X750 */ public float Unknown750;
        /* 0X754 */ public float Unknown754;
        /* 0X758 */ public float Unknown758;
        /* 0X75C */ public float Unknown75C;
        /* 0X760 */ public float Unknown760;
        /* 0X764 */ public float Unknown764;
        /* 0X768 */ public float Unknown768;
        /* 0X76C */ public float Unknown76C;
        /* 0X770 */ public float Unknown770;
        /* 0X774 */ public float Unknown774;
        /* 0X778 */ public float Unknown778;
        /* 0X77C */ public float Unknown77C;
        /* 0X780 */ public float Unknown780;
        /* 0X784 */ public float Unknown784;
        /* 0X788 */ public float Unknown788;
        /* 0X78C */ public float Unknown78C;
        /* 0X790 */ public float Unknown790;
        /* 0X794 */ public float Unknown794;
        /* 0X798 */ public float Unknown798;
        /* 0X79C */ public float Unknown79C;
        /* 0X7A0 */ public float Unknown7A0;
        /* 0X7A4 */ public float Unknown7A4;
        /* 0X7A8 */ public float Unknown7A8;
        /* 0X7AC */ public float Unknown7AC;
        /* 0X7B0 */ public float Unknown7B0;
        /* 0X7B4 */ public float Unknown7B4;
        /* 0X7B8 */ public float Unknown7B8;
        /* 0X7BC */ public int UnknownInt7BC;
        /* 0X7C0 */ public float Unknown7C0;
        /* 0X7C4 */ public float Unknown7C4;
        /* 0X7C8 */ public float Unknown7C8;
        /* 0X7CC */ public float Unknown7CC;
        /* 0X7D0 */ public int UnknownInt7D0;
        /* 0X7D4 */ public float Unknown7D4;
        /* 0X7D8 */ public float Unknown7D8;
        /* 0X7DC */ public float Unknown7DC;
        /* 0X7E0 */ public float SwimSpeed;
        /* 0X7E4 */ public float Unknown7E4;
        /* 0X7E8 */ public float Unknown7E8;
        /* 0X7EC */ public float Unknown7EC;
        /* 0X7F0 */ public float JetpackWaterSpeed;
        /* 0X7F4 */ public float Unknown7F4;
        /* 0X7F8 */ public float Unknown7F8;
        /* 0X7FC */ public float Unknown7FC;
        /* 0X800 */ public float Unknown800;
        /* 0X804 */ public float Unknown804;
        /* 0X808 */ public float Unknown808;
        /* 0X80C */ public float Unknown80C;
        /* 0X810 */ public float Unknown810;
        /* 0X814 */ public float Unknown814;
        /* 0X818 */ public float Unknown818;
        /* 0X81C */ public float Unknown81C;
        /* 0X820 */ public float Unknown820;
        /* 0X824 */ public float Unknown824;
        /* 0X828 */ public float Unknown828;
        /* 0X82C */ public float Unknown82C;
        /* 0X830 */ public float Unknown830;
        /* 0X834 */ public float Unknown834;
        /* 0X838 */ public float Unknown838;
        /* 0X83C */ public float Unknown83C;
        /* 0X840 */ public float FallDamage;        // maybe per unit of height? as there are multiple height levels of fall damage in the damage table...
        /* 0X844 */ public float Unknown844;
        /* 0X848 */ public float Unknown848;
        /* 0X84C */ public float Unknown84C;
        /* 0X850 */ public float Unknown850;
        /* 0X854 */ public float Unknown854;
        /* 0X858 */ public float Unknown858;
        /* 0X85C */ public int UnknownInt85C;
        /* 0X860 */ public int UnknownInt860;
        /* 0X864 */ public float Unknown864;
        /* 0X868 */ public float Unknown868;
        /* 0X86C */ public float Unknown86C;
        /* 0X870 */ public float Unknown870;
        /* 0X874 */ public float Unknown874;
        /* 0X878 */ public float Unknown878;
        /* 0X87C */ public float Unknown87C;
        /* 0X880 */ public float Unknown880;
        /* 0X884 */ public float Unknown884;
        /* 0X888 */ public float Unknown888;
        /* 0X88C */ public float Unknown88C;
        /* 0X890 */ public float Unknown890;
        /* 0X894 */ public float Unknown894;
        /* 0X898 */ public float Unknown898;
        /* 0X89C */ public float PlayerWalkSpeed;
        /* 0X8A0 */ public float PlayerRunSpeed;
        /* 0X8A4 */ public float Unknown8A4;
        /* 0X8A8 */ public float Unknown8A8;
        /* 0X8AC */ public float Unknown8AC;
        /* 0X8B0 */ public float Unknown8B0;
        /* 0X8B4 */ public float Unknown8B4;
        /* 0X8B8 */ public float Unknown8B8;
        /* 0X8BC */ public float Unknown8BC;
        /* 0X8C0 */ public float Unknown8C0;
        /* 0X8C4 */ public float Unknown8C4;
        /* 0X8C8 */ public float Unknown8C8;
        /* 0X8CC */ public float Unknown8CC;
        /* 0X8D0 */ public float Unknown8D0;
        /* 0X8D4 */ public float Unknown8D4;
        /* 0X8D8 */ public float Unknown8D8;
        /* 0X8DC */ public float Unknown8DC;
        /* 0X8E0 */ public float Gravity;
        /* 0X8E4 */ public float Unknown8E4;
        /* 0X8E8 */ public float Unknown8E8;
        /* 0X8EC */ public float Unknown8EC;
        /* 0X8F0 */ public float Unknown8F0;
        /* 0X8F4 */ public float Unknown8F4;
        /* 0X8F8 */ public float Unknown8F8;
        /* 0X8FC */ public float Unknown8FC;
        /* 0X900 */ public float Unknown900;
        /* 0X904 */ public float Unknown904;
        /* 0X908 */ public float Unknown908;
        /* 0X90C */ public float Unknown90C;
        /* 0X910 */ public float Unknown910;
        /* 0X914 */ public float Unknown914;
        /* 0X918 */ public float Unknown918;
        /* 0X91C */ public float Unknown91C;
        /* 0X920 */ public float Unknown920;
        /* 0X924 */ public float Unknown924;
        /* 0X928 */ public float Unknown928;
        /* 0X92C */ public float Unknown92C;
        /* 0X930 */ public float Unknown930;
        /* 0X934 */ public float Unknown934;
        /* 0X938 */ public float Unknown938;
        public GcPlayerStickData Unknown93C;    // 0x93C
        public GcPlayerStickData Unknown958;    // 0x958
        public int UnknownInt974;
        public float Unknown978;
        public float Unknown97C;
        public float Unknown980;
        public GcCameraSpawnSetupData Unknown984;
        public GcCameraSpawnSetupData Unknown994;

        public GcInventoryValueData Unknown9A4;
        public GcInventoryValueData Unknown9C0;
        public GcInventoryValueData Unknown9DC;

        /* 0X9F8 */ public float Unknown9F8;
        /* 0X9FC */ public float Unknown9FC;
        /* 0XA00 */ public float UnknownA00;
        /* 0XA04 */ public float UnknownA04;
        /* 0XA08 */ public float UnknownA08;
        /* 0XA0C */ public float UnknownA0C;
        /* 0XA10 */ public float UnknownA10;
        /* 0XA14 */ public float UnknownA14;
        /* 0XA18 */ public float UnknownA18;
        /* 0XA1C */ public float UnknownA1C;
        /* 0XA20 */ public float UnknownA20;
        /* 0XA24 */ public float UnknownA24;
        /* 0XA28 */ public float UnknownA28;
        /* 0XA2C */ public int UnknownIntA2C;
        /* 0XA30 */ public float UnknownA30;
        /* 0XA34 */ public float UnknownA34;
        /* 0XA38 */ public float UnknownA38;
        /* 0XA3C */ public float UnknownA3C;
        public GcCameraAnomalySetupData UnknownA40;
        public GcCameraAnomalySetupData UnknownA80;
        public GcCameraAnomalySetupData UnknownAC0;

    }
}
