using libMBIN.NMS.Toolkit;
using libMBIN.NMS.GameComponents;

namespace libMBIN.NMS.GameComponents
{
	[NMS(GUID = 0x8833A623CFB88658, SubGUID = 0x92D4879C17049BD7)]
    public class GcAudioWwiseRTPCs : NMSTemplate
    {
        // 0x4F entries
        public enum AkRTPCEnum { INVALID_RTPC, BASE_BATTERY_CHARGING, BASE_SPHERE_ROLLSPEED, BINOCULARS_EFFECT, BURN_INTENSITY, COMMS_CHATTER_DISTANCE, COMMS_CHATTER_FREIGHTERATTACKED,
            COMMS_CHATTER_PIRATES, COMMS_CHATTER_POLICE, CREATURE_EXISTENCE, CREATURES_STEP_SIZE, DOPPLER_DROID_SMALL, GAMEOBJECT_DISTANCE, GLOBAL_HAZARD_LEVEL, GLOBAL_HEALTH_LEVEL,
            GLOBAL_SHIELD_LEVEL, HG_VA_EMOTE, HG_VA_GAMEOBJECTS, HG_VA_HEADBODYRATIO, HG_VA_SEED, HG_VA_SIZE, INTERACT_TIMER, JETPACK_HEIGHT, MAP_STAR_WOOSH, MASTER_CHAT_LEVEL,
            MASTER_MUSIC_LEVEL, MASTER_SFX_LEVEL, NPC_SHIP_DISTANCE, NPC_SHIP_DOPPLER, NPC_SHIP_SPEED, PL_AMB_HEIGHT, PL_CAVE_ENCLOSED, PL_EXERTION, PL_FALL_SPEED,
            PL_FOLEY_CLOTHING_LOCO_SPEED, PL_HAZARD_PROTECTION, PL_SHIP_HEIGHT, PL_SHIP_LANDINGDISTANCE, PL_SHIP_SPEED, PL_SHIP_SPEED_REV, PL_SHIP_SURFACE_WATER, PL_SHIP_THRUST,
            PL_SHIP_YAW, PL_UNDERWATER_DEPTH, PL_WALK_SPEED, PL_WPN_LASER_RESOURCEGATHER, PL_WPN_LASERPOWER, PL_WPN_NUMBEROFBULLETS, PL_WPN_OVERHEAT, PLANET_TIME, PLAYER_VR_FOLEY_ARMS,
            PULSE_BUS01_MASTER_VOLUME, PULSE_EVENT_PANFR, PULSE_EVENT_PANLR, PULSE_EVENT_PITCH, PULSE_EVENT_SENDBUS_00, PULSE_EVENT_SENDBUS_01, PULSE_EVENT_SENDBUS_02,
            PULSE_EVENT_SENDBUS_03, PULSE_EVENT_VOLUME, QUAD_LASERBUILDUP, RAIN_INTENSITY, RAIN_INTENSITY_BUILDING, RAIN_ROOF, RAIN_SHIP_EXTERIOR, SENTINEL_DETECTOR, SHORELINE,
            STORM, THEREMIN_PITCH, THEREMIN_VOLUME, VEHICLE_EXIT, VEHICLE_IMPACTS, VEHICLE_JUMP, VEHICLE_SKID, VEHICLE_SPEED, VEHICLE_SUSPENSION, VEHICLE_TORQUE, WALKER_MOOD,
            WPN_PL_JAVELIN_CHARGE }
        public AkRTPCEnum AkRTPC;
    }
}
