using libMBIN.NMS.GameComponents;

namespace libMBIN.NMS.GameComponents
{
    [NMS(GUID = 0xE68D87E1532DEDB8, NameHash = 0xA688E4255C8FED76)]
    public class GcDifficultyConfig : NMSTemplate
    {
        /* 0x0000 */ public NMSString0x20A PresetLocId;
        [NMS(Size = 0x7, EnumType = typeof(GcDifficultyPresetType.DifficultyPresetTypeEnum))]
        /* 0x0020 */ public NMSString0x20A[] PresetOptionLocIds;
        [NMS(Size = 0x7, EnumType = typeof(GcDifficultyPresetType.DifficultyPresetTypeEnum))]
        /* 0x0100 */ public GcDifficultySettingsData[] Presets;
        /* 0x0368 */ public GcDifficultySettingsData PermadeathMinSettings;
        [NMS(Size = 0x4, EnumType = typeof(GcDifficultyOptionGroups.DifficultyOptionGroupEnum))]
        /* 0x03C0 */ public GcDifficultyOptionUIGroup[] UILayout;
        [NMS(Size = 0x1C, EnumType = typeof(GcDifficultySettingEnum.DifficultySettingEnum))]
        /* 0x0480 */ public GcDifficultySettingCommonData[] CommonSettingsData;
        /* 0x1440 */ public int AllSlotsUnlockedStartingSuitSlots;
        /* 0x1444 */ public int AllSlotsUnlockedStartingSuitTechSlots;
        /* 0x1448 */ public int AllSlotsUnlockedStartingWeaponSlots;
        /* 0x144C */ public int AllSlotsUnlockedStartingShipSlots;
        /* 0x1450 */ public int AllSlotsUnlockedStartingShipTechSlots;
        /* 0x1458 */ public GcDifficultyStartWithAllItemsKnownOptionData StartWithAllItemsKnownDisabledData;
        /* 0x1768 */ public GcDifficultyStartWithAllItemsKnownOptionData StartWithAllItemsKnownEnabledData;
        [NMS(Size = 0x3, EnumType = typeof(GcCreatureHostilityDifficultyOption.CreatureHostilityDifficultyEnum))]
        /* 0x1A78 */ public NMSString0x20A[] CreatureHostilityOptionLocIds;
        [NMS(Size = 0x4, EnumType = typeof(GcDeathConsequencesDifficultyOption.DeathConsequencesDifficultyEnum))]
        /* 0x1AD8 */ public NMSString0x20A[] DeathConsequencesOptionLocIds;
        [NMS(Size = 0x4, EnumType = typeof(GcDamageReceivedDifficultyOption.DamageReceivedDifficultyEnum))]
        /* 0x1B58 */ public NMSString0x20A[] DamageReceivedOptionLocIds;
        [NMS(Size = 0x4, EnumType = typeof(GcDamageReceivedDifficultyOption.DamageReceivedDifficultyEnum))]
        /* 0x1BD8 */ public float[] DamageReceivedMultipliers;
        [NMS(Size = 0x4, EnumType = typeof(GcDamageReceivedDifficultyOption.DamageReceivedDifficultyEnum))]
        /* 0x1BE8 */ public int[] DamageReceivedAIMechTechDamageHits;
        [NMS(Size = 0x3, EnumType = typeof(GcDamageGivenDifficultyOption.DamageGivenDifficultyEnum))]
        /* 0x1BF8 */ public NMSString0x20A[] DamageGivenOptionLocIds;
        [NMS(Size = 0x3, EnumType = typeof(GcDamageGivenDifficultyOption.DamageGivenDifficultyEnum))]
        /* 0x1C58 */ public float[] DamageGivenMultipliers;
        [NMS(Size = 0x4, EnumType = typeof(GcActiveSurvivalBarsDifficultyOption.ActiveSurvivalBarsDifficultyEnum))]
        /* 0x1C68 */ public NMSString0x20A[] ActiveSurvivalBarsOptionLocIds;
        [NMS(Size = 0x3, EnumType = typeof(GcHazardDrainDifficultyOption.HazardDrainDifficultyEnum))]
        /* 0x1CE8 */ public NMSString0x20A[] HazardDrainOptionLocIds;
        [NMS(Size = 0x3, EnumType = typeof(GcHazardDrainDifficultyOption.HazardDrainDifficultyEnum))]
        /* 0x1D48 */ public float[] HazardDrainMultipliers;
        [NMS(Size = 0x3, EnumType = typeof(GcEnergyDrainDifficultyOption.EnergyDrainDifficultyEnum))]
        /* 0x1D58 */ public NMSString0x20A[] EnergyDrainOptionLocIds;
        [NMS(Size = 0x3, EnumType = typeof(GcEnergyDrainDifficultyOption.EnergyDrainDifficultyEnum))]
        /* 0x1DB8 */ public float[] EnergyDrainMultipliers;
        [NMS(Size = 0x3, EnumType = typeof(GcSubstanceCollectionDifficultyOption.SubstanceCollectionDifficultyEnum))]
        /* 0x1DC8 */ public NMSString0x20A[] SubstanceCollectionOptionLocIds;
        [NMS(Size = 0x3, EnumType = typeof(GcSubstanceCollectionDifficultyOption.SubstanceCollectionDifficultyEnum))]
        /* 0x1E28 */ public float[] SubstanceCollectionMultipliers;
        [NMS(Size = 0x3, EnumType = typeof(GcSubstanceCollectionDifficultyOption.SubstanceCollectionDifficultyEnum))]
        /* 0x1E34 */ public int[] SubstanceCollectionLaserAmount;
        [NMS(Size = 0x3, EnumType = typeof(GcInventoryStackLimitsDifficultyOption.InventoryStackLimitsDifficultyEnum))]
        /* 0x1E40 */ public NMSString0x20A[] InventoryStackLimitsOptionLocIds;
        [NMS(Size = 0x3, EnumType = typeof(GcInventoryStackLimitsDifficultyOption.InventoryStackLimitsDifficultyEnum))]
        /* 0x1EA0 */ public GcDifficultyInventoryStackSizeOptionData[] InventoryStackLimitsOptionData;
        [NMS(Size = 0x4, EnumType = typeof(GcChargingRequirementsDifficultyOption.ChargingRequirementsDifficultyEnum))]
        /* 0x1FF0 */ public NMSString0x20A[] ChargingRequirementsOptionLocIds;
        [NMS(Size = 0x4, EnumType = typeof(GcChargingRequirementsDifficultyOption.ChargingRequirementsDifficultyEnum))]
        /* 0x2070 */ public float[] ChargingRequirementsMultipliers;
        [NMS(Size = 0x4, EnumType = typeof(GcFuelUseDifficultyOption.FuelUseDifficultyEnum))]
        /* 0x2080 */ public NMSString0x20A[] FuelUseOptionLocIds;
        [NMS(Size = 0x4, EnumType = typeof(GcFuelUseDifficultyOption.FuelUseDifficultyEnum))]
        /* 0x2100 */ public GcDifficultyFuelUseOptionData[] FuelUseOptionData;
        [NMS(Size = 0x4, EnumType = typeof(GcLaunchFuelCostDifficultyOption.LaunchFuelCostDifficultyEnum))]
        /* 0x2160 */ public NMSString0x20A[] LaunchFuelCostOptionLocIds;
        [NMS(Size = 0x4, EnumType = typeof(GcLaunchFuelCostDifficultyOption.LaunchFuelCostDifficultyEnum))]
        /* 0x21E0 */ public float[] LaunchFuelCostMultipliers;
        [NMS(Size = 0x4, EnumType = typeof(GcLaunchFuelCostDifficultyOption.LaunchFuelCostDifficultyEnum))]
        /* 0x21F0 */ public float[] ShipSummoningFuelCostMultipliers;
        [NMS(Size = 0x4, EnumType = typeof(GcCurrencyCostDifficultyOption.CurrencyCostDifficultyEnum))]
        /* 0x2200 */ public NMSString0x20A[] CurrencyCostOptionLocIds;
        [NMS(Size = 0x4, EnumType = typeof(GcCurrencyCostDifficultyOption.CurrencyCostDifficultyEnum))]
        /* 0x2280 */ public GcDifficultyCurrencyCostOptionData[] CurrencyCostOptionData;
        [NMS(Size = 0x3, EnumType = typeof(GcItemShopAvailabilityDifficultyOption.ItemShopAvailabilityDifficultyEnum))]
        /* 0x22E0 */ public NMSString0x20A[] ItemShopAvailabilityOptionLocIds;
        [NMS(Size = 0x3, EnumType = typeof(GcItemShopAvailabilityDifficultyOption.ItemShopAvailabilityDifficultyEnum))]
        /* 0x2340 */ public GcItemShopAvailabilityDifficultyOptionData[] ItemShopAvailabilityOptionData;
        [NMS(Size = 0x4, EnumType = typeof(GcScannerRechargeDifficultyOption.ScannerRechargeDifficultyEnum))]
        /* 0x2370 */ public NMSString0x20A[] ScannerRechargeOptionLocIds;
        [NMS(Size = 0x4, EnumType = typeof(GcScannerRechargeDifficultyOption.ScannerRechargeDifficultyEnum))]
        /* 0x23F0 */ public float[] ScannerRechargeMultipliers;
        [NMS(Size = 0x4, EnumType = typeof(GcReputationGainDifficultyOption.ReputationGainDifficultyEnum))]
        /* 0x2400 */ public NMSString0x20A[] ReputationGainOptionLocIds;
        [NMS(Size = 0x4, EnumType = typeof(GcReputationGainDifficultyOption.ReputationGainDifficultyEnum))]
        /* 0x2480 */ public float[] ReputationGainMultipliers;
        [NMS(Size = 0x4, EnumType = typeof(GcCombatTimerDifficultyOption.CombatTimerDifficultyOptionEnum))]
        /* 0x2490 */ public NMSString0x20A[] SpaceCombatOptionLocIds;
        [NMS(Size = 0x4, EnumType = typeof(GcCombatTimerDifficultyOption.CombatTimerDifficultyOptionEnum))]
        /* 0x2510 */ public float[] SpaceCombatMultipliers;
        [NMS(Size = 0x4, EnumType = typeof(GcCombatTimerDifficultyOption.CombatTimerDifficultyOptionEnum))]
        /* 0x2520 */ public float[] SpaceCombatDifficultyMultipliers;
        [NMS(Size = 0x4, EnumType = typeof(GcCombatTimerDifficultyOption.CombatTimerDifficultyOptionEnum))]
        /* 0x2530 */ public NMSString0x20A[] GroundCombatOptionLocIds;
        [NMS(Size = 0x4, EnumType = typeof(GcCombatTimerDifficultyOption.CombatTimerDifficultyOptionEnum))]
        /* 0x25B0 */ public float[] GroundCombatMultipliers;
        [NMS(Size = 0x4, EnumType = typeof(GcCombatTimerDifficultyOption.CombatTimerDifficultyOptionEnum))]
        /* 0x25C0 */ public float[] SentinelTimeOutMultipliers;
        [NMS(Size = 0x3, EnumType = typeof(GcSprintingCostDifficultyOption.SprintingCostDifficultyEnum))]
        /* 0x25D0 */ public NMSString0x20A[] SprintingOptionLocIds;
        [NMS(Size = 0x3, EnumType = typeof(GcSprintingCostDifficultyOption.SprintingCostDifficultyEnum))]
        /* 0x2630 */ public float[] SprintingCostMultipliers;
        [NMS(Size = 0x3, EnumType = typeof(GcBreakTechOnDamageDifficultyOption.BreakTechOnDamageProbabilityEnum))]
        /* 0x2640 */ public NMSString0x20A[] BreakTechOnDamageOptionLocIds;
        [NMS(Size = 0x3, EnumType = typeof(GcBreakTechOnDamageDifficultyOption.BreakTechOnDamageProbabilityEnum))]
        /* 0x26A0 */ public float[] BreakTechOnDamageMultipliers;
    }
}
