using libMBIN.NMS.GameComponents;

namespace libMBIN.NMS.GameComponents
{
    [NMS(GUID = 0x4F7EFF6A2047FBFD, NameHash = 0xDDA2C2271A6ACA0B)]
    public class GcScreenFilterTable : NMSTemplate
    {
        // size: 0x52
        public enum FiltersEnum {
            Default,
            DefaultStorm,
            Frozen,
            FrozenStorm,
            Toxic,
            ToxicStorm,
            Radioactive,
            RadioactiveStorm,
            Scorched,
            ScorchedStorm,
            Barren,
            BarrenStorm,
            Weird1,
            Weird2,
            Weird3,
            Weird4,
            Weird5,
            Weird6,
            Weird7,
            Weird8,
            Vintage,
            HyperReal,
            Desaturated,
            Amber,
            GBGreen,
            Apocalypse,
            Diffusion,
            Green,
            BlackAndWhite,
            Isolation,
            Sepia,
            Filmic,
            GBGrey,
            Binoculars,
            Surveying,
            Nexus,
            SpaceStation,
            Freighter,
            FreighterAbandoned,
            Frigate,
            MissionSurvey,
            NewVibrant,
            NewVibrantBright,
            NewVibrantWarm,
            NewVintageBright,
            NewVintageWash,
            Drama,
            MemoryBold,
            Memory,
            MemoryWash,
            Autumn,
            AutumnFade,
            ClassicBright,
            Classic,
            ClassicWash,
            BlackAndWhiteDream,
            ColourTouchB,
            ColourTouchC,
            NegativePrint,
            SepiaExtreme,
            Solarise,
            TwoToneStrong,
            TwoTone,
            Dramatic,
            Fuchsia,
            Violet,
            Cyan,
            GreenNew,
            AmberNew,
            Red,
            HueShiftA,
            HueShiftB,
            HueShiftC,
            HueShiftD,
            WarmStripe,
            NMSRetroA,
            NMSRetroB,
            NMSRetroC,
            NMSRetroD,
            NMSRetroE,
            NMSRetroF,
            NMSRetroG
        }
        [NMS(Size = 0x52, EnumType = typeof(FiltersEnum))]
        /* 0x0 */ public GcScreenFilterData[] Filters;
    }
}
