using libMBIN.NMS.Toolkit;
using libMBIN.NMS.GameComponents;

namespace libMBIN.NMS.Globals
{
    [NMS(GUID = 0xEAD848A04278304A)]
    public class GcCameraGlobals : NMSTemplate
    {
        /* 0x0000 */ public bool PauseThirdPersonCamInPause;
        [NMS(Size = 0x03, Ignore = true)]
        /* 0x0001 */ public byte[] Padding1;
        /* 0x0004 */ public float DebugPlanetJumpNearHeight;
        /* 0x0008 */ public float DebugPlanetJumpFarHeight;
        /* 0x000C */ public float TogglePerspectiveBlendTime;
        /* 0x0010 */ public float UnderwaterCameraSurfaceOffset;
        /* 0x0014 */ public float ThirdPersonAfterIntroCamBlendTime;
        /* 0x0018 */ public float ThirdPersonSkipIntroCamBlendTime;
        /* 0x001C */ public float VehicleExitFlashTime;
        /* 0x0020 */ public float VehicleExitFlashStrength;
        [NMS(Size = 0xC, Ignore = true)]
        /* 0x0024 */ public byte[] Padding24;
        /* 0x0030 */ public Colour VehicleExitFlashColour;
        /* 0x0040 */ public float VehicleFirstToThirdExitOffsetY;
        /* 0x0044 */ public float VehicleFirstToThirdExitOffsetZ;
        /* 0x0048 */ public float ShipThirdPersonBlendTime;
        /* 0x004C */ public float ShipThirdPersonBlendWithOffsetTime;
        /* 0x0050 */ public float ShipThirdPersonBlendOffset;
        /* 0x0054 */ public float ShipThirdPersonBlendOutTime;
        /* 0x0058 */ public float ShipThirdPersonBlendOutOffset;
        /* 0x005C */ public float ShipFirstPersonBlendTime;
        /* 0x0060 */ public float ShipFirstPersonBlendOffset;
        /* 0x0064 */ public float ShipThirdPersonEnterBlendTime;
        /* 0x0068 */ public float ShipThirdPersonEnterBlendOffset;
        /* 0x006C */ public float FlybyMinRange;
        /* 0x0070 */ public float FlybyRange;
        /* 0x0074 */ public float FlybyMinRelativeSpeed;
        /* 0x0078 */ public float FlybyRelativeSpeedRange;
        /* 0x007C */ public float FlybyInVehicleDamper;
        /* 0x0080 */ public float BinocularFlashTime;
        /* 0x0084 */ public float BinocularFlashStrength;
        /* 0x0088 */ public float MinFirstPersonCameraPitch;
        /* 0x008C */ public float MaxFirstPersonCameraPitch;
        /* 0x0090 */ public GcCameraFollowSettings CharacterUnarmedCam;
        /* 0x0170 */ public GcCameraFollowSettings CharacterRunCam;
        /* 0x0250 */ public GcCameraFollowSettings CharacterCombatCam;
        /* 0x0330 */ public GcCameraFollowSettings CharacterIndoorCam;
        /* 0x0410 */ public GcCameraFollowSettings CharacterAirborneCam;
        /* 0x04F0 */ public GcCameraFollowSettings CharacterMeleeBoostCam;
        /* 0x05D0 */ public GcCameraFollowSettings CharacterRocketBootsCam;
        /* 0x06B0 */ public GcCameraFollowSettings CharacterRocketBootsChargeCam;
        /* 0x0790 */ public GcCameraFollowSettings CharacterFallingCam;
        /* 0x0870 */ public GcCameraFollowSettings CharacterAirborneCombatCam;
        /* 0x0950 */ public GcCameraFollowSettings CharacterSteepSlopeCam;
        /* 0x0A30 */ public GcCameraFollowSettings CharacterUnderwaterCam;
        /* 0x0B10 */ public GcCameraFollowSettings CharacterUnderwaterCombatCam;
        /* 0x0BF0 */ public GcCameraFollowSettings CharacterUnderwaterJetpackCam;
        /* 0x0CD0 */ public GcCameraFollowSettings CharacterGrabbedCam;
        /* 0x0DB0 */ public float ThirdPersonCameraChangeBlendTime;
        [NMS(Size = 0x04, Ignore = true)]
        /* 0x0DB4 */ public byte[] PaddingDB4;
        /* 0x0DB8 */ public GcCameraFollowSettings BuggyFollowCam;
        /* 0x0E98 */ public GcCameraFollowSettings HovercraftFollowCam;
        /* 0x0F78 */ public GcCameraFollowSettings SubmarineFollowCam;
        /* 0x1058 */ public GcCameraFollowSettings BikeFollowCam;
        /* 0x1138 */ public GcCameraFollowSettings WheeledBikeFollowCam;
        /* 0x1218 */ public GcCameraFollowSettings TruckFollowCam;
        /* 0x12F8 */ public GcCameraFollowSettings SpaceshipFollowCam;
        /* 0x13D8 */ public GcCameraFollowSettings DropshipFollowCam;
        /* 0x14B8 */ public GcCameraFollowSettings ShuttleFollowCam;
        /* 0x1598 */ public GcCameraFollowSettings RoyalShipFollowCam;
        /* 0x1678 */ public GcCameraFollowSettings ScienceShipFollowCam;
        /* 0x1758 */ public float FrontendModelCameraSpringTime;
        /* 0x175C */ public float ModelViewFlashTime;
        /* 0x1760 */ public Vector4f ModelViewOffset;
        /* 0x1770 */ public Vector2f ModelViewFocusOffset;
        [NMS(Size = 0x08, Ignore = true)]
        /* 0x1778 */ public byte[] Padding1778;
        /* 0x1780 */ public Vector4f InteractionOffset;
        /* 0x1790 */ public Vector4f InteractionShipFocusOffset;
        /* 0x17A0 */ public float DistanceForFleetInteraction;
        /* 0x17A4 */ public float DistanceForFrigateInteraction;
        /* 0x17A8 */ public float DistanceForFrigatePurchaseInteraction;
        [NMS(Size = 0x04, Ignore = true)]
        /* 0x17AC */ public byte[] Padding17AC;
        /* 0x17B0 */ public Vector4f OffsetForFleetInteraction;
        /* 0x17C0 */ public Vector4f OffsetForFrigateInteraction;
        /* 0x17D0 */ public float FleetUIOrbitRate;
        /* 0x17D4 */ public float FleetUIVerticalMotionDuration;
        /* 0x17D8 */ public float FleetUIVerticalMotionAmplitude;
        /* 0x17DC */ public Vector2f PitchForFrigateInteraction;
        /* 0x17E4 */ public Vector2f RotationForFrigateInteraction;
        /* 0x17EC */ public float InteractionModeBlendTime;
        /* 0x17F0 */ public float InteractionModeFocusCamBlend;
        /* 0x17F4 */ public float InteractionModeFoV;
        /* 0x17F8 */ public float MinInteractFocusAngle;
        /* 0x17FC */ public float ModelViewInterpTime;
        /* 0x1800 */ public float ThirdPersonBlendInTime;
        /* 0x1804 */ public float ThirdPersonBlendOutTime;
        /* 0x1808 */ public float ThirdPersonCollisionPushOffsetReducerStart;
        /* 0x180C */ public float ThirdPersonOffsetSpringTime;
        /* 0x1810 */ public bool MaxBob;
        [NMS(Size = 0x03, Ignore = true)]
        /* 0x1811 */ public byte[] Padding1811;
        /* 0x1814 */ public float PhotoModeMoveSpeed;
        /* 0x1818 */ public float PhotoModeTurnSpeed;
        /* 0x181C */ public float PhotoModeMaxDistance;
        /* 0x1820 */ public float PhotoModeMaxDistanceSpace;
        /* 0x1824 */ public float PhotoModeMaxDistanceClampForce;
        /* 0x1828 */ public float PhotoModeMaxDistanceClampBuffer;
        /* 0x182C */ public float PhotoModeCollisionRadius;
        /* 0x1830 */ public float PhotoModeRollSpeed;
        /* 0x1834 */ public float PhotoModeFlashDuration;
        /* 0x1838 */ public float PhotoModeFlashIntensity;
        [NMS(Size = 0x04, Ignore = true)]
        /* 0x183C */ public byte[] Padding183C;
        /* 0x1840 */ public Vector4f PhotoModeShipOffset;
        /* 0x1850 */ public float RunningFoVAdjust;
        /* 0x1854 */ public float MeleeBoostedFoV;
        /* 0x1858 */ public float MeleeFoV;
        /* 0x185C */ public float AerialViewDownDistance;
        /* 0x1860 */ public float AerialViewPause;
        /* 0x1864 */ public float AerialViewStartTime;
        /* 0x1868 */ public float AerialViewBackTime;
        /* 0x186C */ public float AerialViewBlendTime;
        /* 0x1870 */ public TkCurveType AerialViewCurve;
        /* 0x1874 */ public GcCameraAerialViewData BeaconTransition;
        /* 0x18A4 */ public GcCameraAerialViewData SignalTransition;
        /* 0x18D4 */ public GcCameraAerialViewData WaypointTransition;
        /* 0x1904 */ public GcCameraAerialViewData RadioTowerTransition;
        /* 0x1934 */ public float ScreenshotHorizonHeight;
        /* 0x1938 */ public float ScreenshotHorizonFaceFactor;
        /* 0x193C */ public float ScreenshotBendDownAmount;
        /* 0x1940 */ public float ScreenshotRightDistance;
        /* 0x1944 */ public float ScreenshotBackDistance;
        /* 0x1948 */ public float ScreenshotInTime;
        /* 0x194C */ public float ScreenshotOutTime;
        /* 0x1950 */ public float ShipCamSpringStrengthMin;
        /* 0x1954 */ public float ShipCamSpringStrengthMax;
        /* 0x1958 */ public float ShipCamTurn;
        /* 0x195C */ public float ShipCamPitch;
        /* 0x1960 */ public float ShipCamPitchMod;
        /* 0x1964 */ public float ShipCamLookInterp;
        /* 0x1968 */ public float ShipCamMinReturnTime;
        /* 0x196C */ public float ShipCamReturnTime;
        /* 0x1970 */ public float ShipCamMotionTurn;
        /* 0x1974 */ public float ShipCamMotionPitch;
        /* 0x1978 */ public float ShipCamMotionPitchMod;
        /* 0x197C */ public float ShipCamMotionMaxLagTurnAngle;
        /* 0x1980 */ public float ShipCamMotionMaxLagPitchAngle;
        /* 0x1984 */ public float ShipCamMotionInterp;
        /* 0x1988 */ public float ShipCamRollAmountMin;
        /* 0x198C */ public float ShipCamRollAmountMax;
        /* 0x1990 */ public float ShipCamRollSpeedScaler;
        /* 0x1994 */ public float ShipCamAimFOV;
        /* 0x1998 */ public float MouseSensitivity;
        /* 0x199C */ public float ModelViewRotateSpeed;
        /* 0x19A0 */ public float ModelViewMouseRotateSpeed;
        /* 0x19A4 */ public float ModelViewMouseRotateSnapStrength;
        /* 0x19A8 */ public float ModelViewMouseMoveSpeed;
        /* 0x19AC */ public float ModelViewDistSpeed;
        /* 0x19B0 */ public float ModelViewMinDist;
        /* 0x19B4 */ public float ModelViewMaxDist;
        /* 0x19B8 */ public float ModelViewDefaultPitch;
        /* 0x19BC */ public float ModelViewDefaultYaw;
        /* 0x19C0 */ public bool DebugMoveCam;
        [NMS(Size = 0x03, Ignore = true)]
        /* 0x19C1 */ public byte[] Padding19C1;
        /* 0x19C4 */ public float DebugMoveCamSpeed;
        /* 0x19C8 */ public float DebugMoveCamHeight;
        /* 0x19CC */ public bool DebugAICam;
        [NMS(Size = 0x03, Ignore = true)]
        /* 0x19CD */ public byte[] Padding19CD;
        /* 0x19D0 */ public float DebugAICamUp;
        /* 0x19D4 */ public float DebugAICamAt;
        /* 0x19D8 */ public float PainShakeTime;
        /* 0x19DC */ public float ShipShakeDamper;
        /* 0x19E0 */ public float IndoorCamShakeDamper;
        /* 0x19E4 */ public float FirstPersonSlerpAway;
        /* 0x19E8 */ public float FirstPersonSlerpTowards;
        [NMS(Size = 0x04, Ignore = true)]
        /* 0x19EC */ public byte[] Padding19EC;
        [NMS(Size = 0x23)]
        /* 0x19F0 */ public GcCameraShakeData[] CameraShakeTable;
        /* 0x3430 */ public float BobAmount;
        /* 0x3434 */ public float BobFactor;
        /* 0x3438 */ public float BobFocus;
        /* 0x343C */ public float BobRollFactor;
        /* 0x3440 */ public float BobRollAmount;
        /* 0x3444 */ public float BobRollOffset;
        /* 0x3448 */ public float BobFwdAmount;
        /* 0x344C */ public float CamSeed1;
        /* 0x3450 */ public float CamSeed2;
        /* 0x3454 */ public float CamWander1Phase;
        /* 0x3458 */ public float CamWander2Phase;
        /* 0x345C */ public float CamWander1Amplitude;
        /* 0x3460 */ public float CamWander2Amplitude;
        /* 0x3464 */ public float DebugSpaceStationTeleportOffset;
        /* 0x3468 */ public float DebugCameraSlowFactor;
        /* 0x346C */ public float DebugCameraFastFactor;
        /* 0x3470 */ public float DebugCameraSpaceFastFactor;
        /* 0x3474 */ public float OffsetCamFOV;
        [NMS(Size = 0x08, Ignore = true)]
        /* 0x3478 */ public byte[] Padding3478;
        /* 0x3480 */ public Vector4f OffsetCamOffset;
        /* 0x3490 */ public Vector4f OffsetCamRotation;
        /* 0x34A0 */ public float ObjectFocusTime;
        /* 0x34A4 */ public float CharCamFocusHeight;
        /* 0x34A8 */ public float CharCamMaxDistance;
        /* 0x34AC */ public float CharCamMinDistance;
        /* 0x34B0 */ public float CharCamHeight;
        /* 0x34B4 */ public float CharCamOffsetTime;
        /* 0x34B8 */ public float CharCamAutoDirStartTime;
        /* 0x34BC */ public float CharCamLookOffset;
        /* 0x34C0 */ public float CharCamLookOffsetFactor;
        /* 0x34C4 */ public float CharCamDeflectSpeed;
        /* 0x34C8 */ public float CharCamMinSpeed;
        /* 0x34CC */ public float CharCamRightStickX;
        /* 0x34D0 */ public float CharCamRightStickY;
        /* 0x34D4 */ public float CockpitScale;
        /* 0x34D8 */ public float FirstPersonCamHeight;
        [NMS(Size = 0x04, Ignore = true)]
        /* 0x34DC */ public byte[] Padding34DC;
        [NMS(Size = 0x07)]
        /* 0x34E0 */ public Vector4f[] FirstPersonCamOffset;
        /* 0x3550 */ public Vector4f FirstPersonInShipCamOffset;
        /* 0x3560 */ public float FirstPersonFoV;
        /* 0x3564 */ public float ThirdPersonFoV;
        /* 0x3568 */ public float FirstPersonZoom1FoV;
        /* 0x356C */ public float FirstPersonZoom2FoV;
        /* 0x3570 */ public float ShipFoVMin;
        /* 0x3574 */ public float ShipFoVMin2;
        /* 0x3578 */ public float ShipFoVMax;
        /* 0x357C */ public float ShipWarpFoV;
        /* 0x3580 */ public float ShipFoVMin3rdPerson;
        /* 0x3584 */ public float ShipFoVMax3rdPerson;
        /* 0x3588 */ public float ShipFoVBoost;
        /* 0x358C */ public float ShipFoVMiniJump;
        /* 0x3590 */ public float ShipFoVSpring;
        /* 0x3594 */ public float ShipMiniJumpFoVSpring;
        /* 0x3598 */ public float FoVSpring;
        /* 0x359C */ public float FoVAdjust;
        /* 0x35A0 */ public bool FollowDrawCamProbes;
        [NMS(Size = 0x03, Ignore = true)]
        /* 0x35A1 */ public byte[] Padding35A1;
        /* 0x35A4 */ public GcCameraAnimationData AmbientCameraAnimations;
        /* 0x3628 */ public TkModelResource AmbientDroneAnimations;
        [NMS(Size = 0x80)]
        /* 0x36AC */ public string CameraAmbientAnimationsData;
        /* 0x372C */ public float CameraAmbientAutoSwitchMinTime;
        /* 0x3730 */ public float CameraAmbientAutoSwitchMaxTime;
        [NMS(Size = 0x0C, Ignore = true)]
        /* 0x3734 */ public byte[] Padding3734;
        /* 0x3740 */ public TkModelRendererData CameraNPCShipInteraction;
        /* 0x37F0 */ public TkModelRendererData CameraNPCShopInteraction;
        [NMS(Size = 0x04)]
        /* 0x38A0 */ public TkPhysRelVectorData[] SavedCameraPositions;
        [NMS(Size = 0x04)]
        /* 0x3920 */ public Vector4f[] SavedCameraFacing;
        /* 0x3960 */ public GcCameraWarpSettings WarpSettings;
        [NMS(Size = 0x0C, Ignore = true)]
        /* 0x39A4 */ public byte[] EndPadding;
    }
}
