using libMBIN.NMS.Toolkit;
using libMBIN.NMS.GameComponents;

namespace libMBIN.NMS.Globals
{
    [NMS(GUID = 0x5D17CCC0EA2A7E40)]
    public class GcCameraGlobals : NMSTemplate
    {
        /* 0x0000 */ public bool PauseThirdPersonCamInPause;
                     [NMS(Size = 0x03, Ignore = true)]
        /* 0x0001 */ public byte[] Padding1;
        /* 0x0004 */ public float DebugPlanetJumpNearHeight;
        /* 0x0008 */ public float DebugPlanetJumpFarHeight;
        /* 0x000C */ public float TogglePerspectiveBlendTime;
        /* 0x0010 */ public float UnderwaterCameraSurfaceOffset;
        /* 0x0014 */ public float ThirdPersonAfterIntroCamBlendTime;
        /* 0x0018 */ public float ThirdPersonSkipIntroCamBlendTime;
        /* 0x001C */ public float VehicleExitFlashTime;
        /* 0x0020 */ public float VehicleExitFlashStrength;
        /* 0x0024 */ public float VehicleFirstToThirdExitOffsetY;
        /* 0x0028 */ public float VehicleFirstToThirdExitOffsetZ;
        /* 0x002C */ public float ShipThirdPersonBlendTime;
        /* 0x0030 */ public float ShipThirdPersonBlendWithOffsetTime;
        /* 0x0034 */ public float ShipThirdPersonBlendOffset;
        /* 0x0038 */ public float ShipThirdPersonBlendOutTime;
        /* 0x003C */ public float ShipThirdPersonBlendOutOffset;
        /* 0x0040 */ public float ShipFirstPersonBlendTime;
        /* 0x0044 */ public float ShipFirstPersonBlendOffset;
        /* 0x0048 */ public float ShipThirdPersonEnterBlendTime;
        /* 0x004C */ public float ShipThirdPersonEnterBlendOffset;
        /* 0x0050 */ public float FlybyMinRange;
        /* 0x0054 */ public float FlybyRange;
        /* 0x0058 */ public float FlybyMinRelativeSpeed;
        /* 0x005C */ public float FlybyRelativeSpeedRange;
        /* 0x0060 */ public float FlybyInVehicleDamper;
        /* 0x0064 */ public float BinocularFlashTime;
        /* 0x0068 */ public float BinocularFlashStrength;
        /* 0x006C */ public float MinFirstPersonCameraPitch;
        /* 0x0070 */ public float MaxFirstPersonCameraPitch;
                     [NMS(Size = 0x04, Ignore = true)]
        /* 0x0074 */ public byte[] Padding74;
        /* 0x0078 */ public GcCameraFollowSettings CharacterUnarmedCam;
        /* 0x0158 */ public GcCameraFollowSettings CharacterRunCam;
        /* 0x0238 */ public GcCameraFollowSettings CharacterCombatCam;
        /* 0x0318 */ public GcCameraFollowSettings CharacterIndoorCam;
        /* 0x03F8 */ public GcCameraFollowSettings CharacterAirborneCam;
        /* 0x04D8 */ public GcCameraFollowSettings CharacterMeleeBoostCam;
        /* 0x05B8 */ public GcCameraFollowSettings CharacterRocketBootsCam;
        /* 0x0698 */ public GcCameraFollowSettings CharacterRocketBootsChargeCam;
        /* 0x0778 */ public GcCameraFollowSettings CharacterFallingCam;
        /* 0x0858 */ public GcCameraFollowSettings CharacterAirborneCombatCam;
        /* 0x0938 */ public GcCameraFollowSettings CharacterSteepSlopeCam;
        /* 0x0A18 */ public GcCameraFollowSettings CharacterUnderwaterCam;
        /* 0x0AF8 */ public GcCameraFollowSettings CharacterUnderwaterCombatCam;
        /* 0x0BD8 */ public GcCameraFollowSettings CharacterUnderwaterJetpackCam;
        /* 0x0CB8 */ public GcCameraFollowSettings CharacterGrabbedCam;
        /* 0x0D98 */ public float ThirdPersonCameraChangeBlendTime;
                     [NMS(Size = 0x04, Ignore = true)]
        /* 0x0D9C */ public byte[] PaddingD9C;
        /* 0x0DA0 */ public GcCameraFollowSettings BuggyFollowCam;
        /* 0x0E80 */ public GcCameraFollowSettings HovercraftFollowCam;
        /* 0x0F60 */ public GcCameraFollowSettings SubmarineFollowCam;
        /* 0x1040 */ public GcCameraFollowSettings BikeFollowCam;
        /* 0x1120 */ public GcCameraFollowSettings WheeledBikeFollowCam;
        /* 0x1200 */ public GcCameraFollowSettings TruckFollowCam;
        /* 0x12E0 */ public GcCameraFollowSettings SpaceshipFollowCam;
        /* 0x13C0 */ public GcCameraFollowSettings DropshipFollowCam;
        /* 0x14A0 */ public GcCameraFollowSettings ShuttleFollowCam;
        /* 0x1580 */ public GcCameraFollowSettings RoyalShipFollowCam;
        /* 0x1660 */ public GcCameraFollowSettings ScienceShipFollowCam;
        /* 0x1740 */ public float FrontendModelCameraSpringTime;
        /* 0x1744 */ public float ModelViewFlashTime;
                     [NMS(Size = 0x08, Ignore = true)]
        /* 0x1748 */ public byte[] Padding1748;
        /* 0x1750 */ public Vector4f ModelViewOffset;
        /* 0x1760 */ public Vector2f ModelViewFocusOffset;
                     [NMS(Size = 0x08, Ignore = true)]
        /* 0x1768 */ public byte[] Padding1768;
        /* 0x1770 */ public Vector4f InteractionOffset;
        /* 0x1780 */ public Vector4f InteractionShipFocusOffset;
        /* 0x1790 */ public float DistanceForFleetInteraction;
        /* 0x1794 */ public float DistanceForFrigateInteraction;
        /* 0x1798 */ public float DistanceForFrigatePurchaseInteraction;
                     [NMS(Size = 0x04, Ignore = true)]
        /* 0x179C */ public byte[] Padding179C;
        /* 0x17A0 */ public Vector4f OffsetForFleetInteraction;
        /* 0x17B0 */ public Vector4f OffsetForFrigateInteraction;
        /* 0x17C0 */ public float FleetUIOrbitRate;
        /* 0x17C4 */ public float FleetUIVerticalMotionDuration;
        /* 0x17C8 */ public float FleetUIVerticalMotionAmplitude;
        /* 0x17CC */ public Vector2f PitchForFrigateInteraction;
        /* 0x17D4 */ public Vector2f RotationForFrigateInteraction;
        /* 0x17DC */ public float InteractionModeBlendTime;
        /* 0x17E0 */ public float InteractionModeFocusCamBlend;
        /* 0x17E4 */ public float InteractionModeFoV;
        /* 0x17E8 */ public float MinInteractFocusAngle;
        /* 0x17EC */ public float ModelViewInterpTime;
        /* 0x17F0 */ public float ThirdPersonBlendInTime;
        /* 0x17F4 */ public float ThirdPersonBlendOutTime;
        /* 0x17F8 */ public float ThirdPersonCollisionPushOffsetReducerStart;
        /* 0x17FC */ public float ThirdPersonOffsetSpringTime;
        /* 0x1800 */ public bool MaxBob;
                     [NMS(Size = 0x03, Ignore = true)]
        /* 0x1801 */ public byte[] Padding1801;
        /* 0x1804 */ public float PhotoModeMoveSpeed;
        /* 0x1808 */ public float PhotoModeTurnSpeed;
        /* 0x180C */ public float PhotoModeMaxDistance;
        /* 0x1810 */ public float PhotoModeMaxDistanceSpace;
        /* 0x1814 */ public float PhotoModeMaxDistanceClampForce;
        /* 0x1818 */ public float PhotoModeMaxDistanceClampBuffer;
        /* 0x181C */ public float PhotoModeCollisionRadius;
        /* 0x1820 */ public float PhotoModeRollSpeed;
        /* 0x1824 */ public float PhotoModeFlashDuration;
        /* 0x1828 */ public float PhotoModeFlashIntensity;
                     [NMS(Size = 0x04, Ignore = true)]
        /* 0x182C */ public byte[] Padding182C;
        /* 0x1830 */ public Vector4f PhotoModeShipOffset;
        /* 0x1840 */ public float RunningFoVAdjust;
        /* 0x1844 */ public float MeleeBoostedFoV;
        /* 0x1848 */ public float MeleeFoV;
        /* 0x184C */ public float AerialViewDownDistance;
        /* 0x1850 */ public float AerialViewPause;
        /* 0x1854 */ public float AerialViewStartTime;
        /* 0x1858 */ public float AerialViewBackTime;
        /* 0x185C */ public float AerialViewBlendTime;
        /* 0x1860 */ public TkCurveType AerialViewCurve;
        /* 0x1864 */ public GcCameraAerialViewData BeaconTransition;
        /* 0x1894 */ public GcCameraAerialViewData SignalTransition;
        /* 0x18C4 */ public GcCameraAerialViewData WaypointTransition;
        /* 0x18F4 */ public GcCameraAerialViewData RadioTowerTransition;
        /* 0x1924 */ public float ScreenshotHorizonHeight;
        /* 0x1928 */ public float ScreenshotHorizonFaceFactor;
        /* 0x192C */ public float ScreenshotBendDownAmount;
        /* 0x1930 */ public float ScreenshotRightDistance;
        /* 0x1934 */ public float ScreenshotBackDistance;
        /* 0x1938 */ public float ScreenshotInTime;
        /* 0x193C */ public float ScreenshotOutTime;
        /* 0x1940 */ public float ShipCamSpringStrengthMin;
        /* 0x1944 */ public float ShipCamSpringStrengthMax;
        /* 0x1948 */ public float ShipCamTurn;
        /* 0x194C */ public float ShipCamPitch;
        /* 0x1950 */ public float ShipCamPitchMod;
        /* 0x1954 */ public float ShipCamLookInterp;
        /* 0x1958 */ public float ShipCamMinReturnTime;
        /* 0x195C */ public float ShipCamReturnTime;
        /* 0x1960 */ public float ShipCamMotionTurn;
        /* 0x1964 */ public float ShipCamMotionPitch;
        /* 0x1968 */ public float ShipCamMotionPitchMod;
        /* 0x196C */ public float ShipCamMotionMaxLagTurnAngle;
        /* 0x1970 */ public float ShipCamMotionMaxLagPitchAngle;
        /* 0x1974 */ public float ShipCamMotionInterp;
        /* 0x1978 */ public float ShipCamRollAmountMin;
        /* 0x197C */ public float ShipCamRollAmountMax;
        /* 0x1980 */ public float ShipCamRollSpeedScaler;
        /* 0x1984 */ public float ShipCamAimFOV;
        /* 0x1988 */ public float MouseSensitivity;
        /* 0x198C */ public float ModelViewRotateSpeed;
        /* 0x1990 */ public float ModelViewMouseRotateSpeed;
        /* 0x1994 */ public float ModelViewMouseRotateSnapStrength;
        /* 0x1998 */ public float ModelViewMouseMoveSpeed;
        /* 0x199C */ public float ModelViewDistSpeed;
        /* 0x19A0 */ public float ModelViewMinDist;
        /* 0x19A4 */ public float ModelViewMaxDist;
        /* 0x19A8 */ public float ModelViewDefaultPitch;
        /* 0x19AC */ public float ModelViewDefaultYaw;
        /* 0x19B0 */ public bool DebugMoveCam;
                     [NMS(Size = 0x03, Ignore = true)]
        /* 0x19B1 */ public byte[] Padding19B1;
        /* 0x19B4 */ public float DebugMoveCamSpeed;
        /* 0x19B8 */ public float DebugMoveCamHeight;
        /* 0x19BC */ public bool DebugAICam;
                     [NMS(Size = 0x03, Ignore = true)]
        /* 0x19BD */ public byte[] Padding19BD;
        /* 0x19C0 */ public float DebugAICamUp;
        /* 0x19C4 */ public float DebugAICamAt;
        /* 0x19C8 */ public float PainShakeTime;
        /* 0x19CC */ public float ShipShakeDamper;
        /* 0x19D0 */ public float IndoorCamShakeDamper;
        /* 0x19D4 */ public float FirstPersonSlerpAway;
        /* 0x19D8 */ public float FirstPersonSlerpTowards;
                     [NMS(Size = 0x04, Ignore = true)]
        /* 0x19DC */ public byte[] Padding19DC;
                     [NMS(Size = 0x23)]
        /* 0x19E0 */ public GcCameraShakeData[] CameraShakeTable;
        /* 0x3420 */ public float BobAmount;
        /* 0x3424 */ public float BobFactor;
        /* 0x3428 */ public float BobFocus;
        /* 0x342C */ public float BobRollFactor;
        /* 0x3430 */ public float BobRollAmount;
        /* 0x3434 */ public float BobRollOffset;
        /* 0x3438 */ public float BobFwdAmount;
        /* 0x343C */ public float CamSeed1;
        /* 0x3440 */ public float CamSeed2;
        /* 0x3444 */ public float CamWander1Phase;
        /* 0x3448 */ public float CamWander2Phase;
        /* 0x344C */ public float CamWander1Amplitude;
        /* 0x3450 */ public float CamWander2Amplitude;
        /* 0x3454 */ public float DebugSpaceStationTeleportOffset;
        /* 0x3458 */ public float DebugCameraSlowFactor;
        /* 0x345C */ public float DebugCameraFastFactor;
        /* 0x3460 */ public float DebugCameraSpaceFastFactor;
        /* 0x3464 */ public float OffsetCamFOV;
                     [NMS(Size = 0x08, Ignore = true)]
        /* 0x3468 */ public byte[] Padding3468;
        /* 0x3470 */ public Vector4f OffsetCamOffset;
        /* 0x3480 */ public Vector4f OffsetCamRotation;
        /* 0x3490 */ public float ObjectFocusTime;
        /* 0x3494 */ public float CharCamFocusHeight;
        /* 0x3498 */ public float CharCamMaxDistance;
        /* 0x349C */ public float CharCamMinDistance;
        /* 0x34A0 */ public float CharCamHeight;
        /* 0x34A4 */ public float CharCamOffsetTime;
        /* 0x34A8 */ public float CharCamAutoDirStartTime;
        /* 0x34AC */ public float CharCamLookOffset;
        /* 0x34B0 */ public float CharCamLookOffsetFactor;
        /* 0x34B4 */ public float CharCamDeflectSpeed;
        /* 0x34B8 */ public float CharCamMinSpeed;
        /* 0x34BC */ public float CharCamRightStickX;
        /* 0x34C0 */ public float CharCamRightStickY;
        /* 0x34C4 */ public float CockpitScale;
        /* 0x34C8 */ public float FirstPersonCamHeight;
                     [NMS(Size = 0x04, Ignore = true)]
        /* 0x34CC */ public byte[] Padding34CC;
                     [NMS(Size = 0x07)]
        /* 0x34D0 */ public Vector4f[] FirstPersonCamOffset;
        /* 0x3540 */ public Vector4f FirstPersonInShipCamOffset;
        /* 0x3550 */ public float FirstPersonFoV;
        /* 0x3554 */ public float ThirdPersonFoV;
        /* 0x3558 */ public float FirstPersonZoom1FoV;
        /* 0x355C */ public float FirstPersonZoom2FoV;
        /* 0x3560 */ public float ShipFoVMin;
        /* 0x3564 */ public float ShipFoVMin2;
        /* 0x3568 */ public float ShipFoVMax;
        /* 0x356C */ public float ShipWarpFoV;
        /* 0x3570 */ public float ShipFoVMin3rdPerson;
        /* 0x3574 */ public float ShipFoVMax3rdPerson;
        /* 0x3578 */ public float ShipFoVBoost;
        /* 0x357C */ public float ShipFoVMiniJump;
        /* 0x3580 */ public float ShipFoVSpring;
        /* 0x3584 */ public float ShipMiniJumpFoVSpring;
        /* 0x3588 */ public float FoVSpring;
        /* 0x358C */ public float FoVAdjust;
        /* 0x3590 */ public bool FollowDrawCamProbes;
                     [NMS(Size = 0x03, Ignore = true)]
        /* 0x3591 */ public byte[] Padding3591;
        /* 0x3594 */ public GcCameraAnimationData AmbientCameraAnimations;
        /* 0x3618 */ public TkModelResource AmbientDroneAnimations;
                     [NMS(Size = 0x80)]
        /* 0x369C */ public string CameraAmbientAnimationsData;
        /* 0x371C */ public float CameraAmbientAutoSwitchMinTime;
        /* 0x3720 */ public float CameraAmbientAutoSwitchMaxTime;
                     [NMS(Size = 0x0C, Ignore = true)]
        /* 0x3724 */ public byte[] Padding3724;
        /* 0x3730 */ public TkModelRendererData CameraNPCShipInteraction;
        /* 0x37E0 */ public TkModelRendererData CameraNPCShopInteraction;
                     [NMS(Size = 0x04)]
        /* 0x3890 */ public TkPhysRelVectorData[] SavedCameraPositions;
                     [NMS(Size = 0x04)]
        /* 0x3910 */ public Vector4f[] SavedCameraFacing;
        /* 0x3950 */ public GcCameraWarpSettings WarpSettings;
    }
}
