using libMBIN.NMS.Toolkit;
using libMBIN.NMS.GameComponents;

namespace libMBIN.NMS.Globals
{
    [NMS(Size = 0x3F40, GUID = 0x7D053D861FDE6432)]
    public class GcCreatureGlobals : NMSTemplate
    {
        [NMS(Size = 0x20)]
        /* 0x0000 */ public string PetCarePuzzleOverrideID;
        /* 0x0020 */ public float CreatureInteractionRangeBoostHuge;
        /* 0x0024 */ public float CreatureInteractionRangeBoostLarge;
        /* 0x0028 */ public float CreatureInteractionRangeBoostMedium;
        /* 0x002C */ public float CreatureInteractionRangeBoostSmall;
        /* 0x0030 */ public float CreatureInteractionRangeBoostRun;
        /* 0x0034 */ public float CreatureInteractionRangeBoostSprint;
        /* 0x0038 */ public bool CreatureInteractWithoutRaycasts;
        /* 0x003C */ public float CreatureInteractBaseRange;
        /* 0x0040 */ public float PetInteractBaseRange;
        [NMS(Size = 0x4, Ignore = true)]
        /* 0x0044 */ public byte[] Padding44;
        [NMS(Size = 0xB)]
        /* 0x0048 */ public NMSString0x20[] Temperments;
        [NMS(Size = 0xB)]
        /* 0x01A8 */ public NMSString0x20[] TempermentDescriptions;
        [NMS(Size = 0x4)]
        /* 0x0308 */ public NMSString0x20[] Diets;
        [NMS(Size = 0x4)]
        /* 0x0388 */ public NMSString0x20[] WaterDiets;
        [NMS(Size = 0x10)]
        /* 0x0408 */ public NMSString0x20[] DietMeat;
        [NMS(Size = 0x10)]
        /* 0x0608 */ public NMSString0x20[] DietVeg;
        [NMS(Size = 0x4)]
        /* 0x0808 */ public NMSString0x20[] DietDescriptions;
        [NMS(Size = 0x4)]
        /* 0x0888 */ public NMSString0x20[] WaterDietDescriptions;
        [NMS(Size = 0x10)]
        /* 0x0908 */ public NMSString0x20[] BiomeDescriptions;
        [NMS(Size = 0x10)]
        /* 0x0B08 */ public NMSString0x20[] BiomeWaterDescriptions;
        [NMS(Size = 0x10)]
        /* 0x0D08 */ public NMSString0x20[] BiomeAirDescriptions;
        [NMS(Size = 0x1B)]
        /* 0x0F08 */ public NMSString0x20[] WeirdBiomeDescriptions;
        [NMS(Size = 0x10)]
        /* 0x1268 */ public NMSString0x20[] PetBiomeClimates;
        /* 0x1468 */ public bool OverrideIKParams;
        /* 0x146C */ public float BodyMassWeight;
        /* 0x1470 */ public float Omega;
        /* 0x1474 */ public float OmegaDropOff;
        /* 0x1478 */ public float MovementDamp;
        /* 0x147C */ public bool IsHurtingCreaturesACrime;
        /* 0x147D */ public bool EnableFlyingSnakeTails;
        /* 0x147E */ public bool EnableNewStuff;
        /* 0x147F */ public bool InstantCreatureRide;
        /* 0x1480 */ public bool EnableVRCreatureRide;
        /* 0x1481 */ public bool EnableMPCreatureRide;
        /* 0x1484 */ public float RidingReplicationRangeMultiplier;
        /* 0x1488 */ public float RidingRollAdjustMaxAngle;
        /* 0x148C */ public float RidingRollMaxAngleAt;
        /* 0x1490 */ public float RidingFirstPersonOffsetFwd;
        /* 0x1494 */ public float RidingFirstPersonOffsetUp;
        /* 0x1498 */ public float CreatureScaleMangle;
        /* 0x149C */ public bool CreatureRideDirectControl;
        /* 0x149D */ public bool StaticCreatureRide;
        /* 0x14A0 */ public float RideSpeedSlow;
        /* 0x14A4 */ public float RideSpeedFast;
        /* 0x14A8 */ public float RideSpeedChangeTime;
        /* 0x14AC */ public float RiderLeanTime;
        /* 0x14B0 */ public float PostRideMoveTime;
        /* 0x14B4 */ public float RideIdleTime;
        /* 0x14B8 */ public float MinRideSize;
        /* 0x14BC */ public float MaxCreatureSize;
        /* 0x14C0 */ public float MaxRideLeanCounterRotate;
        /* 0x14C4 */ public float PetMinSummonDistance;
        /* 0x14C8 */ public float PetMaxSummonDistance;
        /* 0x14CC */ public float PetSummonRotation;
        /* 0x14D0 */ public float PlayerDamageTransferScale;
        [NMS(Size = 0x4, Ignore = true)]
        /* 0x14D4 */ public byte[] Padding14D4;
        /* 0x14D8 */ public GcSeed CreatureSeed;
        [NMS(Size = 0x20)]
        /* 0x14E8 */ public string CreatureFilter;
        /* 0x1508 */ public int MaxEcosystemCreaturesNormal;
        /* 0x150C */ public int MaxEcosystemCreaturesLow;
        /* 0x1510 */ public float LowPerfFlockReduce;
        /* 0x1514 */ public bool UncapSpawningforVideo;
        /* 0x1515 */ public bool AllowSpawningOnscreen;
        /* 0x1518 */ public float ResourceSpawnTime;
        /* 0x151C */ public float TurnInPlaceIdleTime;
        /* 0x1520 */ public float TurnInPlaceMaxAngle;
        /* 0x1524 */ public float TurnInPlaceMinTime;
        /* 0x1528 */ public float TurnInPlaceMaxSpeed;
        /* 0x152C */ public float TurnInPlaceMaxSpeedIndoor;
        /* 0x1530 */ public float SceneTerrainSpawnMinDistance;
        /* 0x1534 */ public float CreatureMinAlignSpeed;
        /* 0x1538 */ public float PatrolMinDist;
        /* 0x153C */ public float PatrolMaxDist;
        /* 0x1540 */ public float PatrolHeightOffset;
        /* 0x1544 */ public float PatrolGradientFactor;
        /* 0x1548 */ public float CreatureWaryTime;
        /* 0x154C */ public float CreatureMinRunTime;
        /* 0x1550 */ public float CreatureHearingRange;
        /* 0x1554 */ public float CreatureSightRange;
        /* 0x1558 */ public float CreatureMoveIdle;
        /* 0x155C */ public float CreatureTurnMin;
        /* 0x1560 */ public float CreatureTurnMax;
        /* 0x1564 */ public float CreatureBrakeForce;
        /* 0x1568 */ public float CreatureMinAnimMoveSpeed;
        /* 0x156C */ public float CreatureLookBeforeGoingTime;
        /* 0x1570 */ public float CreatureLookBeforeFleeingTime;
        /* 0x1574 */ public float CreatureLookBeforeFleeingIfShotTime;
        /* 0x1578 */ public float CreatureLookScaryThingTime;
        /* 0x157C */ public float CreatureLookPlayerForceLookTime;
        /* 0x1580 */ public float LookMaxYawMoving;
        /* 0x1584 */ public float LookMaxYawStatic;
        /* 0x1588 */ public float LookPitchAtMaxYaw;
        /* 0x158C */ public float LookMaxPitchWhenMoving;
        /* 0x1590 */ public float LookRollAtMaxYaw;
        /* 0x1594 */ public float LookRollWhenMoving;
        /* 0x1598 */ public float FootPlantError;
        /* 0x159C */ public float RecoverHealthTime;
        /* 0x15A0 */ public GcCameraShakeData PainShake;
        /* 0x1660 */ public float PatrolSwitchMinTime;
        /* 0x1664 */ public float ExtraFollowStrength;
        /* 0x1668 */ public float ExtraFollowFreq1;
        /* 0x166C */ public float ExtraFollowFreq2;
        /* 0x1670 */ public float SandWormChangeDirectionTime;
        /* 0x1674 */ public float SandWormSteerAdjustTime;
        /* 0x1678 */ public float SandWormMaxSteer;
        /* 0x167C */ public float SandWormMaxHeightAdjust;
        /* 0x1680 */ public float SandWormJumpHeight;
        /* 0x1684 */ public float SandWormJumpTime;
        /* 0x1688 */ public float SandWormSubmergeDepth;
        /* 0x168C */ public float SandWormSubmergeTime;
        /* 0x1690 */ public float SandWormSurfaceTime;
        /* 0x1694 */ public int SandWormMaxJumps;
        /* 0x1698 */ public float SandWormDespawnDist;
        /* 0x169C */ public float SandWormSpawnTimer;
        /* 0x16A0 */ public float SandWormSpawnChanceMin;
        /* 0x16A4 */ public float SandWormSpawnChanceMax;
        /* 0x16A8 */ public float ShieldFadeTime;
        /* 0x16AC */ public float SharkAlongPathSpeed;
        /* 0x16B0 */ public float SwarmBrakingForce;
        /* 0x16B4 */ public float SharkToPathYDamp;
        /* 0x16B8 */ public float SharkAttackSpeed;
        /* 0x16BC */ public float SharkAttackAccel;
        /* 0x16C0 */ public float SharkPatrolSpeed;
        /* 0x16C4 */ public float SharkPatrolRadius;
        /* 0x16C8 */ public float SharkPatrolEnd;
        /* 0x16CC */ public float SharkGetToPathSpeed;
        /* 0x16D0 */ public float SharkAlignSpeed;
        /* 0x16D4 */ public float FishBobFrequency;
        /* 0x16D8 */ public float FishBobAmplitude;
        /* 0x16DC */ public float FreighterJellyBobFrequency;
        /* 0x16E0 */ public float FreighterJellyBobAmplitude;
        /* 0x16E4 */ public float InfluenceRadius;
        /* 0x16E8 */ public float InfluenceForce;
        /* 0x16EC */ public float InfluenceThreshold;
        /* 0x16F0 */ public float InfluenceDeflect;
        /* 0x16F4 */ public float TargetSearchTimeout;
        /* 0x16F8 */ public float AttractMinDistance;
        /* 0x16FC */ public float SwarmMoveYFactor;
        /* 0x1700 */ public float DroneExplodeRadius;
        /* 0x1704 */ public float WeaponRepelRange;
        /* 0x1708 */ public float WeaponRepelAmount;
        /* 0x170C */ public float VelocityAlignStrength;
        /* 0x1710 */ public float VelocityAlignSpeed;
        /* 0x1714 */ public float HeightLookAhead;
        /* 0x1718 */ public float MaxHeightTime;
        /* 0x171C */ public float PlayerBirdDistance;
        /* 0x1720 */ public float FishSpeedMin;
        /* 0x1724 */ public float FishSpeedMax;
        /* 0x1728 */ public float FishSwimMaxAcceleration;
        /* 0x172C */ public float AlertDistance;
        /* 0x1730 */ public float RepelRange;
        /* 0x1734 */ public float RepelAmount;
        /* 0x1738 */ public float FishTurn;
        /* 0x173C */ public float TargetReachedDistance;
        /* 0x1740 */ public float MaxSpeed;
        /* 0x1744 */ public float MaxForce;
        /* 0x1748 */ public float MaxTorque;
        /* 0x174C */ public float MinWaterSpawnDepth;
        /* 0x1750 */ public float WaterSpawnOffset;
        /* 0x1754 */ public float SpawnDistanceModifierForUnderwater;
        /* 0x1758 */ public float FootDustGroundTintStrength;
        /* 0x175C */ public float StickToGroundSpeed;
        /* 0x1760 */ public float StickToGroundCastBegin;
        /* 0x1764 */ public float StickToGroundCastEnd;
        /* 0x1768 */ public GcFlyingSnakeData FlyingSnakeData;
        [NMS(Size = 0x4)]
        /* 0x17A8 */ public GcCreatureAlertData[] AlertTable;
        /* 0x1808 */ public bool ShowScale;
        /* 0x180C */ public float PetFootShakeModifier;
        /* 0x1810 */ public float CreatureMedMinSize;
        /* 0x1814 */ public float CreatureLargeMinSize;
        /* 0x1818 */ public float CreatureHugeMinSize;
        /* 0x181C */ public float CreatureRidingMedMinSize;
        /* 0x1820 */ public float CreatureRidingLargeMinSize;
        /* 0x1824 */ public float CreatureRidingHugeMinSize;
        /* 0x1828 */ public float CreatureBlobRidingMedMinSize;
        /* 0x182C */ public float CreatureBlobRidingLargeMinSize;
        /* 0x1830 */ public float CreatureBlobRidingHugeMinSize;
        /* 0x1834 */ public int CreatureSmallHealth;
        /* 0x1838 */ public int CreatureMedHealth;
        /* 0x183C */ public int CreatureLargeHealth;
        /* 0x1840 */ public int CreatureHugeHealth;
        [NMS(Size = 0x4, Ignore = true)]
        /* 0x1844 */ public byte[] Padding1844;
        [NMS(Size = 0x10)]
        /* 0x1848 */ public string CreatureLargeWalkShake;
        /* 0x1858 */ public float CreatureLargeWalkMaxShakeDist;
        [NMS(Size = 0x4, Ignore = true)]
        /* 0x185C */ public byte[] Padding185C;
        [NMS(Size = 0x10)]
        /* 0x1860 */ public string CreatureLargeRunShake;
        /* 0x1870 */ public float CreatureLargeRunMaxShakeDist;
        [NMS(Size = 0x4, Ignore = true)]
        /* 0x1874 */ public byte[] Padding1874;
        [NMS(Size = 0x10)]
        /* 0x1878 */ public string CreatureHugeWalkShake;
        /* 0x1888 */ public float CreatureHugeWalkMaxShakeDist;
        [NMS(Size = 0x4, Ignore = true)]
        /* 0x188C */ public byte[] Padding188C;
        [NMS(Size = 0x10)]
        /* 0x1890 */ public string CreatureHugeRunShake;
        /* 0x18A0 */ public float CreatureHugeRunMaxShakeDist;
        /* 0x18A4 */ public float SmallCreaturePerceptionDistance;
        /* 0x18A8 */ public float largeCreaturePerceptionDistance;
        /* 0x18AC */ public float SmallCreatureFleePlayerDistance;
        /* 0x18B0 */ public float LargeCreatureFleePlayerDistance;
        /* 0x18B4 */ public float SmallCreatureAvoidPlayerDistance;
        /* 0x18B8 */ public float LargeCreatureAvoidPlayerDistance;
        /* 0x18BC */ public float PredatorPerceptionDistance;
        /* 0x18C0 */ public float PredatorFishPerceptionDistance;
        /* 0x18C4 */ public float PassiveFleePlayerDistance;
        /* 0x18C8 */ public float AdultBabyKilledNoticeDistance;
        /* 0x18CC */ public float PercentagePlayerPredators;
        /* 0x18D0 */ public int PredatorSmallHealth;
        /* 0x18D4 */ public int PredatorMedHealth;
        /* 0x18D8 */ public int PredatorLargeHealth;
        /* 0x18DC */ public int PredatorHugeHealth;
        /* 0x18E0 */ public float PlayerPredatorHealthModifier;
        /* 0x18E4 */ public float PredatorApproachTime;
        /* 0x18E8 */ public float PredatorNoticePauseTime;
        /* 0x18EC */ public float PredatorStealthDist;
        /* 0x18F0 */ public float PredatorChargeDist;
        /* 0x18F4 */ public float PredatorChargeDistScale;
        /* 0x18F8 */ public float FishPredatorChargeDist;
        /* 0x18FC */ public float FishPredatorChargeDistScale;
        /* 0x1900 */ public float PredatorBoredomDistance;
        /* 0x1904 */ public float PlayerPredatorBoredomDistance;
        /* 0x1908 */ public float PredatorRegainInterestTime;
        /* 0x190C */ public float PlayerPredatorRegainInterestTime;
        /* 0x1910 */ public float PredatorRunAwayDist;
        /* 0x1914 */ public float PredatorRoarProbAfterHit;
        /* 0x1918 */ public float PredatorRoarProbAfterMiss;
        /* 0x191C */ public float PredatorRunAwayHealthPercent;
        /* 0x1920 */ public float PredatorEnergyRecoverRate;
        /* 0x1924 */ public float PredatorEnergyUseChasing;
        /* 0x1928 */ public bool AggressiveSharks;
        /* 0x192C */ public float DelayAfterRespawnBeforeAttackable;
        /* 0x1930 */ public float IndoorTurnTime;
        /* 0x1934 */ public float IndoorObstacleAvoidStrength;
        /* 0x1938 */ public float IndoorSteeringRayLength;
        /* 0x193C */ public float IndoorSteeringRaySphereSize;
        /* 0x1940 */ public float IndoorSteeringRaySpread;
        /* 0x1944 */ public float FreighterSpawnDist;
        /* 0x1948 */ public float FreighterDespawnDist;
        /* 0x194C */ public bool ScuttlersCanAttack;
        /* 0x1950 */ public int ScuttlerHealth;
        /* 0x1954 */ public float ScuttlerInitialNoAttackTime;
        /* 0x1958 */ public float ScuttlerMoveTimeMin;
        /* 0x195C */ public float ScuttlerMoveTimeMax;
        /* 0x1960 */ public float ScuttlerIdleTimeMin;
        /* 0x1964 */ public float ScuttlerIdleTimeMax;
        /* 0x1968 */ public float ScuttlerZigZagTimeMin;
        /* 0x196C */ public float ScuttlerZigZagTimeMax;
        /* 0x1970 */ public float ScuttlerZigZagStrength;
        /* 0x1974 */ public float ScuttlerSpitDelay;
        /* 0x1978 */ public float ScuttlerSpitChargeTime;
        /* 0x197C */ public float MiniDroneEnergyRecoverRate;
        /* 0x1980 */ public float MiniDroneEnergyUsePerShot;
        /* 0x1984 */ public float MiniDroneShotDelay;
        /* 0x1988 */ public float MiniDroneShotMaxAngle;
        /* 0x198C */ public bool FiendsCanAttack;
        /* 0x198D */ public bool FiendOnscreenMarkers;
        /* 0x1990 */ public int FiendHealth;
        /* 0x1994 */ public float FiendPerceptionDistance;
        /* 0x1998 */ public float FiendSpawnDistance;
        /* 0x199C */ public float FiendDespawnDistance;
        /* 0x19A0 */ public float FiendReplicateStartDistance;
        /* 0x19A4 */ public float FiendReplicateEndDistance;
        /* 0x19A8 */ public float FiendAggroTime;
        /* 0x19AC */ public int FiendMaxEngaged;
        /* 0x19B0 */ public int FiendMaxAttackers;
        /* 0x19B4 */ public float DelayBetweenPounceAttacks;
        /* 0x19B8 */ public float DelayBetweenSpitAttacks;
        /* 0x19BC */ public float FiendMaxVerticalForPounce;
        /* 0x19C0 */ public float FiendZigZagSpeed;
        /* 0x19C4 */ public float FiendZigZagStrength;
        /* 0x19C8 */ public int FiendEggsToUnlockSpit;
        /* 0x19CC */ public int MaxFiendsToSpawn;
        /* 0x19D0 */ public float FiendMinSpawnTime;
        /* 0x19D4 */ public float FiendMaxSpawnTime;
        /* 0x19D8 */ public float FiendAggroIncreaseDamageEgg;
        /* 0x19DC */ public float FiendAggroIncreaseDestroyEgg;
        /* 0x19E0 */ public float FiendAggroDecreasePerSpawn;
        /* 0x19E4 */ public float FiendCritAreaSize;
        /* 0x19E8 */ public float FiendDistToConsiderTargetSwtich;
        /* 0x19EC */ public float FiendDistReduceForBeingShot;
        /* 0x19F0 */ public float FiendBeingShotMemoryTime;
        /* 0x19F4 */ public int MaxFishFiends;
        /* 0x19F8 */ public int FishFiendSmallHealth;
        /* 0x19FC */ public int FishFiendBigHealth;
        /* 0x1A00 */ public float FishFiendSmallBoostStrength;
        /* 0x1A04 */ public float FishFiendSmallBoostTime;
        /* 0x1A08 */ public float FishFiendSmallScale;
        /* 0x1A0C */ public float FishFiendBigBoostStrength;
        /* 0x1A10 */ public float FishFiendBigBoostTime;
        /* 0x1A14 */ public float FishFiendBigScale;
        /* 0x1A18 */ public float RoutineSpeed;
        /* 0x1A1C */ public float RoutineOffset;
        /* 0x1A20 */ public float RagdollTau;
        /* 0x1A24 */ public float RagdollDamping;
        /* 0x1A28 */ public float RagdollConeLimit;
        /* 0x1A2C */ public float RagdollTwistLimit;
        /* 0x1A30 */ public float RagdollMotorFadeStart;
        /* 0x1A34 */ public float RagdollMotorFadeEnd;
        /* 0x1A38 */ public int MaxRagdollsBeforeDespawnOffscreen;
        /* 0x1A3C */ public int MaxRagdollsBeforeDespawnOnscreen;
        /* 0x1A40 */ public float RidingTurnRadiusMultiplier;
        /* 0x1A44 */ public float TurnRadiusMultiplier;
        /* 0x1A48 */ public float PredatorTurnRadiusMultiplier;
        /* 0x1A4C */ public float MaxTurnRadius;
        /* 0x1A50 */ public float TurnSlowAreaCos;
        /* 0x1A54 */ public float BadTurnPercent;
        /* 0x1A58 */ public float BadTurnWeight;
        /* 0x1A5C */ public float MinScaleForNavMap;
        /* 0x1A60 */ public float ImpassabilityBrakeTime;
        /* 0x1A64 */ public float ImpassabilityUnbrakeTime;
        /* 0x1A68 */ public float ImpassabilityTurnSpeedMultiplier;
        /* 0x1A6C */ public float NavMapLookAhead;
        /* 0x1A70 */ public float VelocityAlignYFactorMin;
        /* 0x1A74 */ public float VelocityAlignYFactorMax;
        /* 0x1A78 */ public float BrakingForce;
        /* 0x1A7C */ public float BrakingForceY;
        /* 0x1A80 */ public float FlowFieldWeight;
        /* 0x1A84 */ public float FollowWeight;
        /* 0x1A88 */ public float RidingSteerWeight;
        /* 0x1A8C */ public float AvoidCreaturesWeight;
        /* 0x1A90 */ public float AvoidImpassableWeight;
        /* 0x1A94 */ public float BaseAndTerrainModImpassableStrength;
        /* 0x1A98 */ public float FollowLeaderAlignWeight;
        /* 0x1A9C */ public float FollowLeaderCohereWeight;
        /* 0x1AA0 */ public float SoftenAvoidanceRadiusMod;
        /* 0x1AA4 */ public float FreighterJellySwimSpeed;
        /* 0x1AA8 */ public float DefaultSwimSpeed;
        /* 0x1AAC */ public float FastSwimSpeed;
        /* 0x1AB0 */ public float DefaultWalkMoveSpeed;
        /* 0x1AB4 */ public float DefaultTrotMoveSpeed;
        /* 0x1AB8 */ public float DefaultRunMoveSpeed;
        /* 0x1ABC */ public float PredatorWalkMoveSpeed;
        /* 0x1AC0 */ public float PredatorTrotMoveSpeed;
        /* 0x1AC4 */ public float PredatorRunMoveSpeed;
        /* 0x1AC8 */ public float HeightDiffPenalty;
        /* 0x1ACC */ public float EdgeClosenessPenalty;
        /* 0x1AD0 */ public float PelvisIkStrength;
        /* 0x1AD4 */ public float SteeringUpdateRate;
        /* 0x1AD8 */ public float PathOverestimate;
        /* 0x1ADC */ public float FishWaterSurfaceAnticipate;
        /* 0x1AE0 */ public float FishWaterSurfaceAvoidStrength;
        /* 0x1AE4 */ public float FishDesiredDepth;
        /* 0x1AE8 */ public float FishMinHeightAboveSeaBed;
        /* 0x1AEC */ public float FishSeaBedAvoidStrength;
        /* 0x1AF0 */ public float FishObstacleAvoidStrength;
        /* 0x1AF4 */ public float FishPlayerAttractionFrontDist;
        /* 0x1AF8 */ public float FishPlayerAttractionAhead;
        /* 0x1AFC */ public float FishPlayerAttractionMinDist;
        /* 0x1B00 */ public float FishPlayerAttractionMaxDist;
        /* 0x1B04 */ public float FishPlayerAttractionStrength;
        /* 0x1B08 */ public float AttackPlayerDistance;
        /* 0x1B0C */ public float SpawnCameraAngleCos;
        /* 0x1B10 */ public float SpawnMinDistPercentage;
        /* 0x1B14 */ public float SpawnOnscreenDist;
        /* 0x1B18 */ public float FadeScaleMultiplier;
        /* 0x1B1C */ public float FadeScalePower;
        /* 0x1B20 */ public float FadeDistance;
        /* 0x1B24 */ public float SpawnDistAtMinSize;
        /* 0x1B28 */ public float SpawnDistAtMaxSize;
        /* 0x1B2C */ public float DespawnDistFactor;
        /* 0x1B30 */ public float MinFade;
        /* 0x1B34 */ public float MaxFade;
        /* 0x1B38 */ public bool ProcessPendingSpawnRequests;
        /* 0x1B3C */ public float SpawnsAvoidBaseMultiplier;
        /* 0x1B40 */ public int PerceptionUpdateRate;
        /* 0x1B44 */ public bool AllowSleeping;
        /* 0x1B45 */ public bool DebugDrawTrails;
        /* 0x1B48 */ public float TrailHalfLife;
        /* 0x1B4C */ public bool EnableTrailIk;
        /* 0x1B50 */ public float DetailAnimBlendInTime;
        /* 0x1B54 */ public float DetailAnimBlendOutTime;
        /* 0x1B58 */ public float DetailAnimMinPauseTime;
        /* 0x1B5C */ public float DetailAnimMaxPauseTime;
        /* 0x1B60 */ public bool DetailAnimPlayWhileWalking;
        [NMS(Size = 0x7, Ignore = true)]
        /* 0x1B61 */ public byte[] Padding1B61;
        [NMS(Size = 0x10)]
        /* 0x1B68 */ public string CreatureDeathEffectSmall;
        [NMS(Size = 0x10)]
        /* 0x1B78 */ public string CreatureDeathEffectMedium;
        [NMS(Size = 0x10)]
        /* 0x1B88 */ public string CreatureDeathEffectBig;
        [NMS(Size = 0x10)]
        /* 0x1B98 */ public string FishDeathEffect;
        /* 0x1BA8 */ public float FootParticleTime;
        /* 0x1BAC */ public bool PiedPiper;
        /* 0x1BB0 */ public float PetInteractTurnToFaceMinAngle;
        /* 0x1BB4 */ public float FollowPlayerDistance;
        /* 0x1BB8 */ public float FollowRunPlayerDistance;
        /* 0x1BBC */ public float FollowRange;
        /* 0x1BC0 */ public float PetPlayerSpeedSmoothTime;
        /* 0x1BC4 */ public float PetStickySideBiasAngle;
        /* 0x1BC8 */ public float PetWalkAtHeelChanceDevoted;
        /* 0x1BCC */ public float PetWalkAtHeelChanceIndependent;
        /* 0x1BD0 */ public float PetWalkAtHeelDistMin;
        /* 0x1BD4 */ public float PetWalkAtHeelDistMax;
        /* 0x1BD8 */ public float PetRunAtHeelDistMin;
        /* 0x1BDC */ public float PetRunAtHeelDistMax;
        /* 0x1BE0 */ public float PetHeelDistSwitchTimeMin;
        /* 0x1BE4 */ public float PetHeelDistSwitchTimeMax;
        /* 0x1BE8 */ public float PetRunAtHeelLateralShiftMin;
        /* 0x1BEC */ public float PetRunAtHeelLateralShiftMax;
        /* 0x1BF0 */ public float PetHeelLateralShiftTimeMin;
        /* 0x1BF4 */ public float PetHeelLateralShiftTimeMax;
        /* 0x1BF8 */ public float PetWalkAtHeelLateralShift;
        /* 0x1BFC */ public float PetHeelPosSpringTime;
        /* 0x1C00 */ public GcScanData PetScan;
        /* 0x1C14 */ public float PetRadialCentre;
        /* 0x1C18 */ public float PetRadialRadius;
        /* 0x1C1C */ public float PetRadialWidth;
        /* 0x1C20 */ public float PetRadialPulseMul;
        /* 0x1C24 */ public float PetRadialPulseTime;
        /* 0x1C28 */ public float PetHeartMaxSize;
        /* 0x1C2C */ public float PetHeartChangePerLayer;
        /* 0x1C30 */ public float PetHeartResponseLoopTime;
        /* 0x1C34 */ public float PetHeartResponseTotalTime;
        /* 0x1C38 */ public float PetLastActionReportTime;
        /* 0x1C3C */ public float PetMoodSmoothTime;
        /* 0x1C40 */ public float PetFollowRunPlayerDistance;
        /* 0x1C44 */ public float PetFollowRange;
        /* 0x1C50 */ public Colour PetRadialBadColour;
        /* 0x1C60 */ public Colour PetRadialNeutralColour;
        /* 0x1C70 */ public Colour PetRadialGoodColour;
        /* 0x1C80 */ public Colour PetRadialBoostColour;
        /* 0x1C90 */ public float PetChatCooldown;
        /* 0x1C94 */ public float PetChatUseTraitTemplateChance;
        /* 0x1C98 */ public float PetEffectSpawnOffsetSmall;
        /* 0x1C9C */ public float PetEffectSpawnOffsetMed;
        /* 0x1CA0 */ public float PetEffectSpawnOffsetLarge;
        /* 0x1CA4 */ public float PetEffectSpawnOffsetHuge;
        /* 0x1CA8 */ public float PetTickleChatChance;
        /* 0x1CAC */ public float PetTreatChatChance;
        /* 0x1CB0 */ public bool UseCreatureAdoptOSD;
        /* 0x1CB4 */ public float SearchItemDistance;
        /* 0x1CB8 */ public float SearchItemFrequency;
        /* 0x1CBC */ public float SearchItemGiveUpDistance;
        /* 0x1CC0 */ public float SearchItemGiveUpTime;
        /* 0x1CC4 */ public float SearchItemNotifyTime;
        /* 0x1CC8 */ public float SearchSpawnRandomItemProbability;
        /* 0x1CCC */ public float MiningRandomProbability;
        /* 0x1CD0 */ public bool DebugSearch;
        /* 0x1CD4 */ public int FriendlyCreatureLimit;
        /* 0x1CD8 */ public int FeedingTaskAmount;
        /* 0x1CDC */ public float FeedingFollowTime;
        /* 0x1CE0 */ public float FeedingNoticeTime;
        /* 0x1CE4 */ public float FeedingNoticeDistance;
        /* 0x1CE8 */ public float AttractedMinAvoidCreaturesStrength;
        /* 0x1CEC */ public float AttractedMinAvoidCreaturesDist;
        /* 0x1CF0 */ public float AttractedMaxAvoidCreaturesStrength;
        /* 0x1CF4 */ public float AttractedMaxAvoidCreaturesDist;
        /* 0x1CF8 */ public bool PetsShowTraitClassesAsWords;
        /* 0x1CFC */ public int PetSlotsUnlockedByDefault;
        /* 0x1D00 */ public int PetGrowthTime;
        /* 0x1D04 */ public int PetIncubationTime;
        /* 0x1D08 */ public int PetTrustChangeInterval;
        /* 0x1D0C */ public float PetTrustOnAdoption;
        /* 0x1D10 */ public float PetTrustOnHatch;
        /* 0x1D14 */ public float PetTrustIncreaseStep;
        /* 0x1D18 */ public float PetTrustDecreaseStep;
        /* 0x1D1C */ public float PetTrustIncreaseThreshold;
        /* 0x1D20 */ public float PetTrustDecreaseThreshold;
        /* 0x1D24 */ public float PetMinTrust;
        /* 0x1D28 */ public float PetEggLayingDuration;
        /* 0x1D2C */ public int PetEggLayingInterval;
        /* 0x1D30 */ public int PetEggFirstEggDelay;
        /* 0x1D34 */ public int PetEggModificationTime;
        /* 0x1D38 */ public int PetEggModificationItemLimit;
        [NMS(Size = 0x4, Ignore = true)]
        /* 0x1D3C */ public byte[] Padding1D3C;
        [NMS(Size = 0x10)]
        /* 0x1D40 */ public string PetEggMaxChangeProduct;
        /* 0x1D50 */ public float PetEggSubstanceModifier;
        /* 0x1D54 */ public float PetEggScaleRangeModifier;
        /* 0x1D58 */ public float PetEggScaleRangeMax;
        /* 0x1D5C */ public float PetEggTraitRangeModifier;
        /* 0x1D60 */ public float PetEggTraitRangeMax;
        /* 0x1D64 */ public float PetEggMinDistStep;
        /* 0x1D68 */ public float PetEggMaxDistStep;
        /* 0x1D6C */ public float PetEggOverdosageModifier;
        /* 0x1D70 */ public float PetEggMaxOverdosage;
        /* 0x1D74 */ public float PetEggMaxTopDescriptorChangeChance;
        /* 0x1D78 */ public float PetEggAccessoryChanceModifier;
        /* 0x1D7C */ public float PetEggMaxAccessoriesChangeChance;
        /* 0x1D80 */ public float PetEggColourChanceModifier;
        /* 0x1D84 */ public float PetEggMaxColourChangeChance;
        /* 0x1D88 */ public float PetEggHatchScaleChange;
        /* 0x1D8C */ public float PetEggHatchTraitChange;
        /* 0x1D90 */ public float PetEggHatchColourChangeChance;
        /* 0x1D94 */ public GcBiomeType PetForceBehaviour;
        /* 0x1D98 */ public float PetMaxSizeOffPlanet;
        /* 0x1D9C */ public float PetTeleportDistOffPlanet;
        /* 0x1DA0 */ public float PetTeleportDistOnPlanet;
        /* 0x1DA4 */ public float PetAnimSpeedBoostSmallerThan;
        /* 0x1DA8 */ public float PetAnimSpeedBoostStrength;
        /* 0x1DAC */ public float PetAnimSpeedMax;
        /* 0x1DB0 */ public float PetAnimSpeedMin;
        /* 0x1DB4 */ public float PetNavRadForMinTurn;
        /* 0x1DB8 */ public float PetNavRadForMaxTurn;
        /* 0x1DBC */ public float PetMinTurnRad;
        /* 0x1DC0 */ public float PetMaxTurnRad;
        /* 0x1DC4 */ public float PetMoodCurvePower;
        [NMS(Size = 0x8, Ignore = true)]
        /* 0x1DC8 */ public byte[] Padding1DC8;
        /* 0x1DD0 */ public GcScanEffectData PetOffPlanetEffect;
        [NMS(Size = 0x80)]
        /* 0x1E20 */ public string PetEggResourceFile;
        [NMS(Size = 0x80)]
        /* 0x1EA0 */ public string PetEggHatchResourceFile;
        /* 0x1F20 */ public float PetEggHatchScale;
        /* 0x1F24 */ public float PetEggHatchOffset;
        /* 0x1F28 */ public float PetEggMaxLonely;
        /* 0x1F2C */ public float PetEggMaxHungry;
        /* 0x1F30 */ public float PetEggMinGrowthToLay;
        /* 0x1F34 */ public bool PetForceSummonFromEgg;
        [NMS(Size = 0x3, Ignore = true)]
        /* 0x1F35 */ public byte[] Padding1F35;
        [NMS(Size = 0x10)]
        /* 0x1F38 */ public string PetEggsplosionEffect;
        /* 0x1F48 */ public bool RidingPositionTest;
        /* 0x1F49 */ public bool PetAnimTest;
        /* 0x1F4C */ public float PetThrowArcRange;
        /* 0x1F50 */ public Colour PetThrowArcColour;
        /* 0x1F60 */ public float PetOrderMinRange;
        /* 0x1F64 */ public float PetOrderMaxRange;
        /* 0x1F68 */ public float PetAccessoryMoodDisplayThreshold;
        /* 0x1F6C */ public float PetAccessoryStateInterval;
        /* 0x1F70 */ public float AnimChangeCoolDown;
        /* 0x1F74 */ public float GroupRunProbability;
        /* 0x1F78 */ public float GroupBabyRunProbability;
        /* 0x1F7C */ public float GroupRunStormProbability;
        /* 0x1F80 */ public float GroupLookAtProbability;
        /* 0x1F84 */ public float GroupLookAtDurationMin;
        /* 0x1F88 */ public float GroupLookAtDurationMax;
        /* 0x1F8C */ public float GroupRunDurationMin;
        /* 0x1F90 */ public float GroupRunDurationMax;
        /* 0x1F94 */ public float GroupFemaleProportion;
        /* 0x1F98 */ public float GroupBabyProportion;
        /* 0x1F9C */ public float GroupBabyScale;
        /* 0x1FA0 */ public float GroupBabyHealthMultiplier;
        /* 0x1FA4 */ public float MaxBirdsProportion;
        /* 0x1FA8 */ public float HerdGroupSizeMultiplier;
        /* 0x1FAC */ public bool DrawRoutineFollowDebug;
        /* 0x1FAD */ public bool DrawRoutineInfo;
        /* 0x1FB0 */ public float AdultCorrelationValue;
        /* 0x1FB4 */ public float GrassHeightForMaxPush;
        /* 0x1FB8 */ public float GrassHeightForMinPush;
        /* 0x1FBC */ public float GrassPushMaxStrength;
        /* 0x1FC0 */ public float GrassPushMinStrength;
        /* 0x1FC4 */ public float GrassPushMaxLimit;
        /* 0x1FC8 */ public float GrassPushMinLimit;
        /* 0x1FCC */ public float GrassPushRadius;
        /* 0x1FD0 */ public float GrassPushMaxSize;
        /* 0x1FD4 */ public bool DrawGrassPushRadius;
        /* 0x1FD8 */ public float CreatureIndoorSpeedMultiplier;
        /* 0x1FDC */ public float CreatureSpeedMultiplier;
        /* 0x1FE0 */ public float PredatorSpeedMultiplier;
        [NMS(Size = 0x4, Ignore = true)]
        /* 0x1FE4 */ public byte[] Padding1FE4;
        [NMS(Size = 0x10)]
        /* 0x1FE8 */ public string DefaultKillingSubstance;
        [NMS(Size = 0x10)]
        /* 0x1FF8 */ public string AlienShipQuestKillingSubstance;
        [NMS(Size = 0x10)]
        /* 0x2008 */ public string AlienShipQuestCreatureWeapon;
        [NMS(Size = 0x3)]
        /* 0x2018 */ public NMSString0x10[] KillingSubstances;
        /* 0x2048 */ public int CreatureKillRewardAmountSmall;
        /* 0x204C */ public int CreatureKillRewardAmountMed;
        /* 0x2050 */ public int CreatureKillRewardAmountLarge;
        /* 0x2054 */ public int CreatureKillRewardAmountHuge;
        // This enum is the GcCreatureTypes.CreatureTypeEnum with a few entries removed.
        // Wbertro: not sure it is relevant here?
        public enum CreatureTypesEnum  { Fish, Antelope, Bird, Butterfly, FlyingSnake, FlyingLizard, Diplo, Triceratops, Rodent, Cow, Cat, Strider,
            Trex, Shark, TwoLegAntelope, SixLegCat, SixLegCow, Grunt, Blob, Spider, FloatSpider, SwimCow, SwimRodent, Jellyfish, Crab, RockCreature };
        [NMS(Size = 0x25)]
        /* 0x2058 */ public GcCreatureSubstanceList[] KillingProducts;
        [NMS(Size = 0x1D)]
        /* 0x24F8 */ public GcCreatureHarvestSubstanceList[] HarvestingProducts;
        /* 0x3800 */ public int CreatureHarvestAmountSmall;
        /* 0x3804 */ public int CreatureHarvestAmountMed;
        /* 0x3808 */ public int CreatureHarvestAmountLarge;
        /* 0x380C */ public int CreatureHarvestAmountHuge;
        /* 0x3810 */ public float HarvestCooldownMin;
        /* 0x3814 */ public float HarvestCooldownMax;
        [NMS(Size = 0x10)]
        /* 0x3818 */ public string BasicFeedingProduct;
        [NMS(Size = 0x10)]
        /* 0x3828 */ public string RobotFeedingProduct;
        /* 0x3838 */ public bool AllBaitIsBasic;
        /* 0x3839 */ public bool CanAlwaysLayEgg;
        [NMS(Size = 0x6, Ignore = true)]
        /* 0x383A */ public byte[] Padding383A;
        [NMS(Size = 0x4)]
        /* 0x3840 */ public GcCreatureFoodList[] HerbivoreFeedingProducts;
        [NMS(Size = 0x4)]
        /* 0x3AC0 */ public GcCreatureFoodList[] CarnivoreFeedingProducts;
        /* 0x3D40 */ public GcWeirdCreatureRewardList WeirdKillingRewards;
        [NMS(Size = 0x3)]
        /* 0x3EF0 */ public NMSString0x10[] LootItems;
        /* 0x3F20 */ public float RockTransformGlobalChance;
        [NMS(Size = 0x4)]
        /* 0x3F24 */ public float[] RockTransformChanceModifiers;
        /* 0x3F34 */ public float AngryRockProportionNormal;
        /* 0x3F38 */ public float AngryRockProportionSurvival;
        /* 0x3F3C */ public int PauseBetweenCreatureSpawnRequests;
    }
}
