using System;
using System.Collections.Generic;

using libMBIN.NMS.Toolkit;
using libMBIN.NMS.GameComponents;

namespace libMBIN.NMS.Globals
{
    [NMS(Size = 0x2680, GUID = 0xD32E94DB7E1C41C8, NameHash = 0x013FED27DF728C38)]
    public class GcDebugOptions : NMSTemplate
    {
        /* 0x0000 */ public bool ForceScanEventsToGoPrime;
        /* 0x0001 */ public bool SkipAbandonedFreighterUnlocking;
        /* 0x0002 */ public bool AllowSavingOnAbandonedFreighters;
        /* 0x0003 */ public bool DisableAbandonedFreighterRoomsOptimisation;
        /* 0x0008 */ public ulong OverrideAbandonedFreighterSeed;
        /* 0x0010 */ public bool ThirdPersonIsDefaultCamera;
        /* 0x0011 */ public bool SkipIntro;
        /* 0x0012 */ public bool SkipLogos;
        /* 0x0014 */ public int BootDirectlyIntoSaveSlot;
        /* 0x0018 */ public bool BootDirectlyIntoLastSave;
        /* 0x001C */ public GcGameMode NewSaveGameMode;
        /* 0x0020 */ public bool SkipPlanetDiscoverOnBoot;
        /* 0x0021 */ public bool VideoCaptureMode;
        /* 0x0022 */ public bool GodMode;
        /* 0x0023 */ public bool TakeNoDamage;
        /* 0x0024 */ public bool SuperKillGuns;
        /* 0x0025 */ public bool AlwaysHaveFocus;
        /* 0x0026 */ public bool DisableVibration;
        /* 0x0027 */ public bool DebugGalaxyMapInQuickMenu;
        /* 0x0028 */ public bool MapWarpCheckIgnoreFuel;
        /* 0x0029 */ public bool MapWarpCheckIgnoreDrive;
        /* 0x002A */ public bool EverythingIsFree;
        /* 0x002B */ public bool EverythingIsKnown;
        /* 0x002C */ public bool EverythingIsStar;
        /* 0x002D */ public bool InfiniteStamina;
        /* 0x002E */ public bool DisableHazards;
        /* 0x002F */ public bool IgnoreMissionRank;
        /* 0x0030 */ public bool CanLeaveDialogs;
        /* 0x0031 */ public bool DisableOldMissions;
        /* 0x0032 */ public bool UseScreenEffects;
        /* 0x0033 */ public bool UseGunImpactEffect;
        /* 0x0034 */ public bool RenderCreatureDetails;
        /* 0x0035 */ public bool SkipTutorial;
        /* 0x0036 */ public bool IgnoreFreighterSpawnWarpRequirement;
        /* 0x0037 */ public bool MaximumFreighterSpawns;
        /* 0x0038 */ public bool DisableSaveSlotSorting;
        /* 0x0039 */ public bool DisableSaving;
        /* 0x003A */ public bool DisableStorms;
        /* 0x003B */ public bool ForceEnablePlayerClothComponent;
        /* 0x003C */ public bool ForceDisablePlayerClothComponent;
        /* 0x003D */ public bool ClothForcePositionExtrapolationOff;
        /* 0x003E */ public bool ClothForcePositionExtrapolationOn;
        /* 0x003F */ public bool ClothForcePositionExtrapolationBackOn;
        /* 0x0040 */ public bool ClothForcePositionExtrapolationUpdateOrderDependent;
        /* 0x0041 */ public bool ClothForcePositionExtrapolationSyncWithFpsLock;
        /* 0x0042 */ public bool ClothForcePositionExtrapolationAntiSyncWithFpsLock;
        /* 0x0043 */ public bool ForceEnablePlayerSpringAttachmentComponent;
        /* 0x0044 */ public bool ForceDisablePlayerSpringAttachmentComponent;
        /* 0x0045 */ public bool ForceEnableSplitIkOptimisation;
        /* 0x0046 */ public bool ForceDisableSplitIkOptimisation;
        /* 0x0047 */ public bool DisableNPCs;
        /* 0x0048 */ public bool AlternateControls;
        /* 0x0049 */ public bool AlwaysShowURI;
        /* 0x004A */ public bool MPMissionsAlwaysEPIC;
        /* 0x004B */ public bool ShowFireteamMembersUA;
        /* 0x004C */ public bool RevealAllTitles;
        /* 0x004D */ public bool UnlockAllTitles;
        /* 0x004E */ public bool LockAllTitles;
        /* 0x004F */ public bool AlwaysAllowShipOperations;
        /* 0x0050 */ public bool AlwaysAllowVehicleOperations;
        /* 0x0051 */ public bool AlwaysAllowFreighterInventoryAccess;
        /* 0x0052 */ public NMSString0x200 SeasonalDataOverrideFile;
        /* 0x0252 */ public bool UnlockAllSeasonRewards;
        /* 0x0253 */ public bool UnlockAllTwitchRewards;
        /* 0x0254 */ public NMSString0x400 DebugTwitchRewards;
        /* 0x0654 */ public bool AllowPause;
        /* 0x0655 */ public bool AllSettlementsAreCompleted;
        /* 0x0656 */ public bool DisableSettlements;
        /* 0x0657 */ public bool PlaceOnGroundWhenLeavingDebugCamera;
        /* 0x0658 */ public bool OctahedralImpostersEnable;
        /* 0x0659 */ public bool OctahedralImpostersDisable;
        /* 0x065A */ public bool OctahedralImpostersViewFromSpace;
        /* 0x065C */ public int OctahedralImpostersViewCount;
        /* 0x0660 */ public bool UseDebugScreenSettings;
        /* 0x0664 */ public int ScreenWidth;
        /* 0x0668 */ public int ScreenHeight;
        /* 0x066C */ public bool DisableVSync;
        // size: 0x3
        public enum GameWindowModeEnum { Bordered, Borderless, Fullscreen }
        /* 0x0670 */ public GameWindowModeEnum GameWindowMode;
        /* 0x0674 */ public int Monitor;
        /* 0x0678 */ public int TiledWindowsSplitCount;
        /* 0x067C */ public int TiledWindowsIndex;
        /* 0x0680 */ public NMSString0x100 ForceUniverseAddress;
        /* 0x0780 */ public NMSString0x100 ForcePlayerPosition;
        /* 0x0880 */ public bool ForceInitialShip;
        /* 0x0881 */ public bool ForceInitialWeapon;
        // size: 0x3
        public enum GameStateModeEnum { LoadPreset, UserStorage, FreshStart }
        /* 0x0884 */ public GameStateModeEnum GameStateMode;
        // size: 0x7
        public enum BootModeEnum { MinimalSolarSystem, SolarSystem, GalaxyMap, SmokeTest, SmokeTestGalaxyMap,
            Scratchpad, UnitTest
        }
        /* 0x0888 */ public BootModeEnum BootMode;
        // size: 0x7
        public enum PlayerSpawnLocationOverrideEnum { None, FromSettings, Space, SpaceStation, RandomPlanet, GameStartPlanet, SpecificLocation
        }
        /* 0x088C */ public PlayerSpawnLocationOverrideEnum PlayerSpawnLocationOverride;
        /* 0x0890 */ public NMSString0x80 SceneSettings;
        /* 0x0910 */ public NMSString0x100 WorkingDirectory;
        /* 0x0A10 */ public NMSString0x80 DebugScene;
        // size: 0x2
        public enum SolarSystemBootEnum { FromSettings, Generate }
        /* 0x0A90 */ public SolarSystemBootEnum SolarSystemBoot;
        // size: 0x2
        public enum ShaderPreloadEnum { Off, Full }
        /* 0x0A94 */ public ShaderPreloadEnum ShaderPreload;
        /* 0x0A98 */ public bool ShaderPreloadListExport;
        /* 0x0A99 */ public bool ShaderPreloadListImport;
        /* 0x0A9A */ public bool ShaderCaching;
        // size: 0x3
        public enum BootLoadDelayEnum { LoadAll, WaitForPlanet, WaitForNothing }
        /* 0x0A9C */ public BootLoadDelayEnum BootLoadDelay;
        /* 0x0AA0 */ public bool MemCsv;
        /* 0x0AA4 */ public float ForceTimeOfDay;
        /* 0x0AA8 */ public float ForceInitialTimeOfDay;
        /* 0x0AAC */ public bool ForceSunDirectionFromPhotoMode;
        /* 0x0AB0 */ public float ForceSunAngle;
        /* 0x0AB4 */ public bool ResetForcedSaveSlotOnLoad;
        /* 0x0AB5 */ public bool MissionMessageLoggingEnabled;
        /* 0x0AB6 */ public bool UseParticles;
        /* 0x0AB7 */ public bool UseHeavyAir;
        /* 0x0AB8 */ public bool UseVolumetrics;
        /* 0x0AB9 */ public bool UseClouds;
        /* 0x0ABA */ public bool EnableCloudAnimation;
        /* 0x0ABB */ public bool UseTerrain;
        /* 0x0ABC */ public bool UseInstances;
        /* 0x0ABD */ public bool UseObjects;
        /* 0x0ABE */ public bool UseBuildings;
        /* 0x0ABF */ public bool UseCreatures;
        /* 0x0AC0 */ public bool UseElevation;
        /* 0x0AC1 */ public bool UseLegacyFreighters;
        /* 0x0AC2 */ public bool UseLegacyBuildingTable;
        /* 0x0AC3 */ public bool EnableDayNightCycle;
        /* 0x0AC4 */ public bool SpawnPirates;
        /* 0x0AC5 */ public bool SpawnRobots;
        /* 0x0AC6 */ public bool SpawnShips;
        /* 0x0AC7 */ public bool SpawnPulseEncounters;
        /* 0x0AC8 */ public bool InstanceCollision;
        /* 0x0AC9 */ public bool LoadMissions;
        /* 0x0ACA */ public bool MPMissions;
        /* 0x0ACB */ public bool SpecialsShop;
        /* 0x0ACC */ public bool MultiplePlayerFreightersInASystem;
        /* 0x0ACD */ public bool ForceNexusInQuickMenu;
        /* 0x0ACE */ public bool MissionSurveyEnabled;
        /* 0x0ACF */ public bool AllSeasonMilestonesShowComplete;
        /* 0x0AD0 */ public bool EnableGalaxyRecolouring;
        /* 0x0AD1 */ public bool IgnoreSteamDev;
        /* 0x0AD2 */ public bool EnableBaseBuildingExpandables;
        /* 0x0AD3 */ public bool MouseLookEnabled;
        /* 0x0AD4 */ public bool StartPaused;
        /* 0x0AD5 */ public bool DisableDebugControls;
        /* 0x0AD6 */ public bool FixedFramerate;
        /* 0x0AD7 */ public bool ScreenshotMode;
        /* 0x0AD8 */ public bool RenderHud;
        /* 0x0AD9 */ public bool DisableDiscoveryNaming;
        /* 0x0ADA */ public bool DebugDrawPlayerInteract;
        /* 0x0ADB */ public bool ForceInteractionToSettings;
        /* 0x0ADC */ public int ForceInteractionIndex;
        /* 0x0AE0 */ public bool InteractionsAllwaysGivesTech;
        /* 0x0AE1 */ public bool InfiniteInteractions;
        /* 0x0AE2 */ public bool StopSwitchingToSecondaryInteractions;
        /* 0x0AE4 */ public TkLanguages DebugLanguage;
        /* 0x0AE8 */ public NMSString0x20 AllowedLanguagesFile;
        /* 0x0B08 */ public bool DoAlienLanguage;
        /* 0x0B0C */ public GcAlienRace ForceInteractionRaceTo;
        // size: 0x2
        public enum RealityModeEnum { LoadPreset, Generate }
        /* 0x0B10 */ public RealityModeEnum RealityMode;
        /* 0x0B14 */ public bool DebugPersistentInteractions;
        /* 0x0B15 */ public bool UseHighlightedOptionStyle;
        /* 0x0B16 */ public bool DisableMissionShop;
        /* 0x0B17 */ public NMSString0x80 RealityPresetFile;
        /* 0x0B98 */ public ushort RealityGenerationIteration;
        /* 0x0BA0 */ public List<NMSString0x20> LocTableList;
        /* 0x0BB0 */ public NMSString0x80 DefaultSaveData;
        /* 0x0C30 */ public bool FormatDownloadStorageAreaOnBoot;
        /* 0x0C31 */ public bool ForceBasicLoadScreen;
        /* 0x0C34 */ public float BootLogoFadeRate;
        /* 0x0C38 */ public bool BootMusic;
        /* 0x0C3C */ public float WeaponScale3P;
        /* 0x0C40 */ public bool LogMissingLocalisedText;
        /* 0x0C41 */ public bool FleetDirectorAutoMode;
        /* 0x0C44 */ public float _3dTextDistance;
        /* 0x0C48 */ public float _3dTextMinScale;
        // size: 0x3
        public enum RecordSettingEnum { None, Record, Playback }
        /* 0x0C4C */ public RecordSettingEnum RecordSetting;
        /* 0x0C50 */ public bool DebugBuildingSpawns;
        /* 0x0C51 */ public bool StressTestLongNameDisplay;
        /* 0x0C52 */ public bool ShowLongestStrings;
        /* 0x0C53 */ public NMSString0x20 SaveTestingCommand;
        /* 0x0C73 */ public bool NeverUseBanks;
        /* 0x0C74 */ public bool DisableProfanityFilter;
        /* 0x0C75 */ public bool DisableFileWatcher;
        /* 0x0C76 */ public bool DisableShaderReload;
        /* 0x0C78 */ public int RecurrenceTimeOffset;
        /* 0x0C7C */ public NMSString0x80 CrashDumpPath;
        /* 0x0CFC */ public NMSString0x20 CrashDumpIdentifier;
        /* 0x0D1C */ public bool EnableLivePP;
        /* 0x0D1D */ public bool DebugThreatLevels;
        /* 0x0D1E */ public bool ShowDebugMessages;
        /* 0x0D1F */ public bool ShowFramerate;
        /* 0x0D20 */ public bool PrintAvgFrameTimes;
        /* 0x0D21 */ public bool ShowPositionDebug;
        /* 0x0D22 */ public bool ShowGPUMemory;
        /* 0x0D23 */ public bool ShowMempoolOverlay;
        /* 0x0D24 */ public bool ShowMouseSmoothing;
        /* 0x0D25 */ public NMSString0x100 ShowUniverseAddressOnGalaxyMap;
        /* 0x0E25 */ public bool ShowGraphs;
        /* 0x0E28 */ public int ShowSpecificGraph;
        /* 0x0E2C */ public bool GraphCommandBuffer;
        /* 0x0E2D */ public bool GraphGeneration;
        /* 0x0E2E */ public bool GraphFPS;
        /* 0x0E2F */ public bool GraphTexStreaming;
        /* 0x0E30 */ public bool SmokeTestDumpStatsMode;
        // size: 0x7
        public enum SmokeTestCycleModeEnum { None, TourPlanet, TourSolarSystem, TourGalaxy, TourUDAs, TourShortUDAs, TourRandomWarps
        }
        /* 0x0E34 */ public SmokeTestCycleModeEnum SmokeTestCycleMode;
        // size: 0x8
        public enum SmokeTestScenarioEnum { None, TerrainSnapShotFromAltitude, BelowCloudLayerSnapShot, Flying, UltraBiomeSnapShot,
            Walking, LeakDetector, WalkingSnapshot
        }
        /* 0x0E38 */ public SmokeTestScenarioEnum SmokeTestScenario;
        /* 0x0E3C */ public bool SmokeTestLegacyOutput;
        /* 0x0E40 */ public int SmokeTestConfigPlanetPositionCount;
        /* 0x0E44 */ public float SmokeTestConfigScenarioPreambleLength;
        /* 0x0E48 */ public float SmokeTestConfigScenarioLength;
        /* 0x0E4C */ public bool SmokeTestFastExit;
        /* 0x0E4D */ public bool SmokeTestCameraFly;
        /* 0x0E4E */ public bool SmokeTestOutputOnly;
        /* 0x0E4F */ public bool SmokeTestPureFlight;
        /* 0x0E50 */ public int SmokeTestConfigCaptureCycles;
        /* 0x0E54 */ public float SmokeTestConfigCaptureDurationInSeconds;
        /* 0x0E58 */ public int SmokeTestConfigCaptureFolderNameNumberOffset;
        /* 0x0E5C */ public bool SmokeTestConfigRandomizePlanetSeed;
        /* 0x0E5D */ public bool SmokeTestSmokeBotEnabled;
        /* 0x0E5E */ public bool SmokeTestSmokeBotAutoStart;
        /* 0x0E60 */ public int SmokeTestSmokeBotTargetWarps;
        /* 0x0E64 */ public bool SmokeTestPostBandwidthStats;
        /* 0x0E65 */ public NMSString0x20 SmokeTestForcePlanetDetail;
        /* 0x0E85 */ public NMSString0x20 SmokeTestRunFolder;
        /* 0x0EA5 */ public bool CreatureChatter;
        /* 0x0EA6 */ public bool CreatureErrors;
        /* 0x0EA7 */ public bool CreatureDrawVocals;
        /* 0x0EA8 */ public bool DrawCreaturesInRoutines;
        /* 0x0EA9 */ public bool CompressTextures;
        /* 0x0EAA */ public bool DebugIBL;
        /* 0x0EAB */ public bool DebugSpotlights;
        /* 0x0EAC */ public bool DebugTerrainTextures;
        /* 0x0EAD */ public bool DisableShadowSwitching;
        /* 0x0EAE */ public NMSString0x80 PipelineFile;
        /* 0x0F2E */ public NMSString0x80 PipelineFilePS4;
        /* 0x0FAE */ public NMSString0x80 PipelineFileXboxOne;
        /* 0x102E */ public NMSString0x80 PipelineFileVR;
        /* 0x10AE */ public NMSString0x80 PipelineFileVRPS4;
        /* 0x112E */ public NMSString0x80 PipelineFileFrontend;
        /* 0x11AE */ public NMSString0x80 PipelineFileEditor;
        /* 0x122E */ public bool RenderLowFramerate;
        /* 0x122F */ public bool EnableComputePost;
        /* 0x1230 */ public bool EnableEvenOddRender;
        /* 0x1231 */ public bool MinGPUMode;
        /* 0x1232 */ public bool Proto2DevKit;
        /* 0x1233 */ public bool SimulateDisabledParticleRefractions;
        /* 0x1234 */ public bool AlwaysIncludeLocalPlayerInChatMessage;
        /* 0x1235 */ public bool SimulateNoNetworkConnection;
        // size: 0x3
        public enum ProxyTypeEnum { None, ManualURI, InetProxy }
        /* 0x1238 */ public ProxyTypeEnum ProxyType;
        /* 0x123C */ public NMSString0x80 ProxyURI;
        // size: 0x8
        public enum ServerEnvEnum { Default, dev, qa, prodqa, prod, custom, pentest, merged }
        /* 0x12BC */ public ServerEnvEnum ServerEnv;
        /* 0x12C0 */ public NMSString0x80 AuthBaseUrl;
        /* 0x1340 */ public bool CertificateSecurityBypass;
        /* 0x1341 */ public NMSString0x20 OverrideUsernameForDev;
        /* 0x1364 */ public int DiscoveryAutoSyncIntervalSeconds;
        /* 0x1368 */ public bool DisableSpaceStationSpawnOnJoin;
        /* 0x1369 */ public bool AutoJoinUserEnabled;
        /* 0x136A */ public NMSString0x800 AutoJoinUserNames;
        /* 0x1B6A */ public bool AlwaysSaveGameAsClient;
        /* 0x1B6B */ public bool DisableMonumentDownloads;
        /* 0x1B6C */ public bool UsePadOnUnfocusedWindow;
        /* 0x1B70 */ public int OverrideMatchmakingVersion;
        /* 0x1B74 */ public NMSString0x200 LoadToBase;
        /* 0x1D74 */ public bool IgnoreTransactionTimeouts;
        /* 0x1D75 */ public bool AutoJoinRandomGames;
        /* 0x1D76 */ public NMSString0x100 GOGLogin;
        /* 0x1E76 */ public bool RecordNetworkStatsOnBoot;
        /* 0x1E77 */ public bool FakeHandsInMultiplayer;
        /* 0x1E78 */ public bool ForceSmallLobby;
        /* 0x1E7C */ public int OverrideServerSeasonNumber;
        /* 0x1E80 */ public int OverrideServerSeasonEndTime;
        /* 0x1E84 */ public bool EnableSynergy;
        /* 0x1E85 */ public NMSString0x20 SynergyServer;
        /* 0x1EA8 */ public int SynergyPort;
        /* 0x1EAC */ public bool ShowEditorPlacementPreview;
        /* 0x1EB0 */ public int MaxNumDebugMessages;
        /* 0x1EB4 */ public bool PreloadToolbox;
        /* 0x1EB8 */ public int DebugTextureSize;
        /* 0x1EBC */ public bool UseProcTextureDebugger;
        /* 0x1EC0 */ public int ProceduralModelsShown;
        /* 0x1EC4 */ public int ProceduralModelBatchSize;
        /* 0x1EC8 */ public int ProceduralModelFilterMatchretryCount;
        /* 0x1ECC */ public bool ProceduralModelsDeterministicSequence;
        /* 0x1ED0 */ public int ProceduralModelsThumbnailSize;
        /* 0x1ED4 */ public NMSString0x80 DebugFont;
        /* 0x1F54 */ public NMSString0x80 DebugFontTexture;
        /* 0x1FD4 */ public NMSString0x80 CursorTexture;
        /* 0x2054 */ public NMSString0x80 PauseTexture;
        /* 0x20D4 */ public NMSString0x80 PlayTexture;
        /* 0x2154 */ public NMSString0x80 StepTexture;
        /* 0x21D4 */ public NMSString0x80 RenderToTexture;
        /* 0x2254 */ public bool HmdEnable;
        /* 0x2258 */ public int HmdPreviewScale;
        /* 0x225C */ public bool HmdTracking;
        /* 0x225D */ public bool HmdStereoRender;
        /* 0x225E */ public bool HmdDistortionPassthru;
        /* 0x2260 */ public int HmdMonitor;
        /* 0x2264 */ public int HmdEyeBufferWidth;
        /* 0x2268 */ public int HmdEyeBufferHeight;
        /* 0x226C */ public float HmdEyeScalePos;
        /* 0x2270 */ public float HmdHeadScalePos;
        /* 0x2274 */ public bool HmdFrameShiftEnabled;
        /* 0x2275 */ public bool HmdUseSolidGuiPointer;
        /* 0x2276 */ public bool BodyTurning;
        /* 0x2278 */ public float HmdImmersionFactor;
        /* 0x227C */ public bool ShowHmdHandControllers;
        /* 0x227D */ public bool ShowTeleportEffectLocally;
        /* 0x227E */ public bool DisableLeftHand;
        /* 0x227F */ public bool DisableHeadConstraints;
        /* 0x2280 */ public bool EnablePhotomodeVR;
        /* 0x2281 */ public bool AllowNGuiVR;
        /* 0x2282 */ public bool ForceExtremeWeather;
        /* 0x2283 */ public bool ForceExtremeSentinels;
        /* 0x2284 */ public bool ForceStarType;
        /* 0x2285 */ public bool ForceLoadAllWeather;
        /* 0x2288 */ public GcGalaxyStarTypes ForceStarTypeTo;
        /* 0x228C */ public bool ForceBiome;
        /* 0x2290 */ public GcBiomeType ForceBiomeTo;
        /* 0x2294 */ public bool ForceScreenFilter;
        /* 0x2298 */ public GcScreenFilters ForceScreenFilterTo;
        /* 0x229C */ public GcBiomeSubType ForceBiomeSubTypeTo;
        /* 0x22A0 */ public bool ForceBuildingRace;
        /* 0x22A4 */ public GcAlienRace ForceBuildingRaceTo;
        /* 0x22A8 */ public bool ForceLifeLevel;
        /* 0x22AC */ public GcPlanetLife ForceLifeLevelTo;
        /* 0x22B0 */ public bool ForceCreatureLifeLevel;
        /* 0x22B1 */ public bool ForceDefaultCreatureFile;
        /* 0x22B8 */ public NMSString0x10 DefaultGroundCreatureTable;
        /* 0x22C8 */ public NMSString0x10 DefaultAirCreatureTable;
        /* 0x22D8 */ public NMSString0x10 DefaultWaterCreatureTable;
        /* 0x22E8 */ public NMSString0x10 DefaultCaveCreatureTable;
        /* 0x22F8 */ public GcPlanetLife ForceCreatureLifeLevelTo;
        /* 0x22FC */ public GcPlanetLife ForceTerrainSettings;
        /* 0x2300 */ public bool ForceTerrainType;
        /* 0x2304 */ public TkVoxelGeneratorSettingsTypes ForceTerrainTypeTo;
        /* 0x2308 */ public bool ForcePirateSystem;
        /* 0x2309 */ public bool ForcePrimeTerrain;
        /* 0x230A */ public bool ForceBinaryStar;
        /* 0x230B */ public bool ForceTernaryStar;
        /* 0x230C */ public GcGalaxyStarAnomaly ForceAnomalyTo;
        /* 0x2310 */ public bool ForcePlanetsToHaveWater;
        /* 0x2314 */ public int ForceWaterObjectFileIndex;
        /* 0x2318 */ public int ForceSkyColourIndex;
        /* 0x231C */ public int ForceSpaceSkyColourIndex;
        /* 0x2320 */ public bool ForceSpaceSkyColourRare;
        /* 0x2324 */ public int ForceWaterColourIndex;
        /* 0x2328 */ public int ForceGrassColourIndex;
        /* 0x232C */ public bool ModifyPlanetsInInitialSystems;
        /* 0x232D */ public bool ForcePlanetsToHaveNoWater;
        /* 0x232E */ public bool ForcePlanetsToHaveNoCaves;
        /* 0x232F */ public bool ForcePlanetsToHaveNoNoiseLayers;
        /* 0x2330 */ public bool ForcePlanetsToHaveNoTerrainFeatures;
        /* 0x2331 */ public bool ForceRareAsteroidSystem;
        /* 0x2334 */ public int ForceAsteroidSystemIndex;
        /* 0x2338 */ public bool DisableLimits;
        /* 0x2339 */ public bool LimitPerRegionInstances;
        /* 0x233A */ public bool LimitPerRegionBodies;
        /* 0x233B */ public bool LimitGlobalInstances;
        /* 0x233C */ public bool LimitGlobalBodies;
        /* 0x2340 */ public int GenerateFarLodBuildingDist;
        /* 0x2344 */ public bool DeferRegionBodies;
        /* 0x2348 */ public float GenerateCostDistance;
        /* 0x234C */ public float GenerateCostAngle;
        /* 0x2350 */ public float GenerateCostLOD;
        /* 0x2354 */ public float GenerateCostWait;
        /* 0x2358 */ public bool DChecksEnabled;
        /* 0x2359 */ public bool DChecksOutputJson;
        /* 0x235A */ public bool DChecksOutputBinary;
        /* 0x235B */ public bool DChecksOutputFileLine;
        /* 0x235C */ public int FrameFlipRateDefault;
        /* 0x2360 */ public int FrameFlipRateLoad;
        /* 0x2364 */ public int FrameFlipRateGame;
        /* 0x2368 */ public float MaxFrameRate;
        /* 0x236C */ public bool DisableBaseBuilding;
        /* 0x236D */ public bool DisableBaseBuildingLimits;
        /* 0x236E */ public bool AllowGlobalPartSnapping;
        /* 0x2370 */ public float BaseDownloadTimeout;
        /* 0x2374 */ public bool DisableBasePowerRequirements;
        /* 0x2375 */ public bool EnableBaseMovingOption;
        /* 0x2378 */ public int MoveBaseIndex;
        /* 0x237C */ public NMSString0x20 AutomaticPartSpawnID;
        /* 0x239C */ public GcBaseBuildingPartStyle AutomaticPartSpawnStyle;
        /* 0x23A0 */ public bool AutomaticPartSpawnInactive;
        /* 0x23A4 */ public int ProfilerPartIndexPhase;
        /* 0x23A8 */ public int ProfilerPartIndexStride;
        /* 0x23AC */ public int ProfilerPartIteration;
        /* 0x23B0 */ public bool BaseAdmin;
        /* 0x23B1 */ public NMSString0x20 BaseServerPlatform;       // "pc"
        /* 0x23D4 */ public uint BasePayloadMultiplier;
        /* 0x23D8 */ public bool CrossPlatformFeaturedBases;
        /* 0x23D9 */ public bool ShowMissionIdInTitle;
        /* 0x23DC */ public TkGlobals ToolkitGlobals;
        /* 0x25FC */ public bool AllowOverrideSettlementOwnership;
        /* 0x25FD */ public NMSString0x40 OverrideSettlementOwnershipUsername;
        /* 0x263D */ public NMSString0x40 OverrideSettlementOwnershipOnlineId;
        /* 0x267D */ public bool BlockSettlementsNetwork;
        /* 0x267E */ public bool EnableAccessibleUI;
        /* 0x267F */ public bool UnlockAllStories;
    }
}
