using libMBIN.NMS.GameComponents;
using System.Collections.Generic;

namespace libMBIN.NMS.Globals
{
    [NMS(GUID = 0x19AC494C0B929E4B, NameHash = 0x8652A1B779227539)]
    public class GcSettlementGlobals : NMSTemplate
    {
        /* 0x0000 */ public List<NMSString0x20A> ScanEventsThatPreventSentinelAlert;
        /* 0x0010 */ public ulong BuildingUpgradeTimeInSeconds;
        /* 0x0018 */ public ulong BuildingFreeUpgradeTimeInSeconds;
        /* 0x0020 */ public int JudgementWaitTimeMin;
        /* 0x0024 */ public int JudgementWaitTimeMax;
        /* 0x0028 */ public float BuildingJudgementPriorityChance;
        /* 0x002C */ public float VisitorJudgementSelector;
        /* 0x0030 */ public float PolicyJudgementSelector;
        /* 0x0034 */ public float RequestJudgementSelector;
        /* 0x0038 */ public float ConflictJudgementSelector;
        /* 0x003C */ public int MaxNPCPopulation;
        /* 0x0040 */ public bool DebugForceShowHiddenPerks;
        /* 0x0044 */ public float SettlementEntryMessageDistance;
        /* 0x0048 */ public NMSString0x10 SettlementMiniExpeditionMissionID;
        /* 0x0058 */ public float SettlementMiniExpeditionSuccessChance;
        [NMS(Size = 0x37, EnumType = typeof(GcBuildingClassification.BuildingClassEnum))]
        /* 0x0060 */ public ulong[] SettlementBuildingTimes;
        [NMS(Size = 0x37, EnumType = typeof(GcBuildingClassification.BuildingClassEnum))]
        /* 0x0218 */ public GcSettlementBuildingCost[] SettlementBuildingCosts;
        /* 0x3FF8 */ public List<GcSettlementJudgementData> Judgements;
        /* 0x4008 */ public List<GcSettlementCustomJudgement> CustomJudgements;
        [NMS(Size = 0x37, EnumType = typeof(GcBuildingClassification.BuildingClassEnum))]
        /* 0x4018 */ public GcSettlementStatChangeArray[] SettlementBuildingStatRewards;
        /* 0x4388 */ public NMSString0x10 SettlementCostGek;
        /* 0x4398 */ public NMSString0x10 SettlementCostKorvax;
        /* 0x43A8 */ public NMSString0x10 SettlementCostVykeen;
        /* 0x43B8 */ public int MaxPerksCount;
        /* 0x43BC */ public int MinInitialPositivePerksCount;
        /* 0x43C0 */ public int MaxInitialPositivePerksCount;
        /* 0x43C4 */ public int MinInitialNegativePerksCount;
        /* 0x43C8 */ public int MaxInitialNegativePerksCount;
        [NMS(Size = 0x7, EnumType = typeof(GcSettlementStatType.SettlementStatTypeEnum))]
        /* 0x43CC */ public int[] StatsMinValues;
        [NMS(Size = 0x7, EnumType = typeof(GcSettlementStatType.SettlementStatTypeEnum))]
        /* 0x43E8 */ public int[] StatsMaxValues;
        [NMS(Size = 0x7, EnumType = typeof(GcSettlementStatType.SettlementStatTypeEnum))]
        /* 0x4404 */ public int[] InitialStatsMinValues;
        /* 0x4420 */ public int InitialBuildingCountMin;
        /* 0x4424 */ public int InitialBuildingCountMax;
        [NMS(Size = 0x7, EnumType = typeof(GcSettlementStatType.SettlementStatTypeEnum))]
        /* 0x4428 */ public int[] InitialStatsMaxValues;
        [NMS(Size = 0x7, EnumType = typeof(GcSettlementStatType.SettlementStatTypeEnum))]
        /* 0x4444 */ public bool[] StatIsGoodWhenPositive;
        [NMS(Size = 0x7, EnumType = typeof(GcSettlementStatType.SettlementStatTypeEnum))]
        /* 0x444C */ public float[] NormalisedStatBadThresholds;
        [NMS(Size = 0x7, EnumType = typeof(GcSettlementStatType.SettlementStatTypeEnum))]
        /* 0x4468 */ public float[] NormalisedStatGoodThresholds;
        /* 0x4490 */ public Colour PositiveStatColour;
        /* 0x44A0 */ public Colour NegativeStatColour;
        /* 0x44B0 */ public ulong ProductionSlotTimerOffsetInSeconds;
        /* 0x44B8 */ public ulong ProductionCycleDurationInSeconds;
        /* 0x44C0 */ public ulong AlertCycleDurationInSeconds;
        /* 0x44C8 */ public int MaxProductionSlotUnits;
        /* 0x44CC */ public int ProductUnitsPerCycleRateModifier;
        /* 0x44D0 */ public int SubstanceUnitsPerCycleRateModifier;
        /* 0x44D4 */ public int InitialDebtCycles;
        /* 0x44D8 */ public int DailyDebtPaymentModifier;
        /* 0x44DC */ public int AlertUnitsPerCycleRateModifier;
        [NMS(Size = 0x7, EnumType = typeof(GcSettlementStatType.SettlementStatTypeEnum))]
        /* 0x44E0 */ public int[] StatProductivityContributionModifiers;
        [NMS(Size = 0x7, EnumType = typeof(GcSettlementStatType.SettlementStatTypeEnum))]
        /* 0x44FC */ public bool[] StatProductionIsNegativeWhenBad;
        [NMS(Size = 0x7, EnumType = typeof(GcSettlementStatType.SettlementStatTypeEnum))]
        /* 0x4508 */ public NMSString0x10[] PolicyPerks;
        [NMS(Size = 0x7, EnumType = typeof(GcSettlementStatType.SettlementStatTypeEnum))]
        /* 0x4578 */ public NMSString0x10[] ResearchPerks;
        [NMS(Size = 0x7, EnumType = typeof(GcSettlementStatType.SettlementStatTypeEnum))]
        /* 0x45E8 */ public NMSString0x10[] AltResearchPerks;
        [NMS(Size = 0x7, EnumType = typeof(GcSettlementStatType.SettlementStatTypeEnum))]
        /* 0x4658 */ public GcSettlementStatStrengthData[] PerkStatStrengthValues;
        /* 0x47E0 */ public List<NMSString0x10> GekProductionElements;
        /* 0x47F0 */ public List<NMSString0x10> KorvaxProductionElements;
        /* 0x4800 */ public List<NMSString0x10> VykeenProductionElements;
        /* 0x4810 */ public List<NMSString0x10> PoorProductionElements;
        /* 0x4820 */ public List<NMSString0x10> NeutralProductionElements;
        /* 0x4830 */ public List<NMSString0x10> RichProductionElements;
        [NMS(Size = 0x7, EnumType = typeof(GcSettlementJudgementType.SettlementJudgementTypeEnum))]
        /* 0x4840 */ public NMSString0x20A[] JudgementUpdateTitles;
        [NMS(Size = 0x7, EnumType = typeof(GcSettlementJudgementType.SettlementJudgementTypeEnum))]
        /* 0x4920 */ public NMSString0x20A[] JudgementUpdateMainText;
        [NMS(Size = 0x7, EnumType = typeof(GcSettlementJudgementType.SettlementJudgementTypeEnum))]
        /* 0x4A00 */ public NMSString0x20A[] JudgementUpdateSubtitles;
        [NMS(Size = 0x7, EnumType = typeof(GcSettlementStatType.SettlementStatTypeEnum))]
        /* 0x4AE0 */ public NMSString0x20A[] PositiveStatChangeOSDLocIDs;
        [NMS(Size = 0x7, EnumType = typeof(GcSettlementStatType.SettlementStatTypeEnum))]
        /* 0x4BC0 */ public NMSString0x20A[] NegativeStatChangeOSDLocIDs;
        [NMS(Size = 0x7, EnumType = typeof(GcSettlementStatType.SettlementStatTypeEnum))]
        /* 0x4CA0 */ public NMSString0x10[] PositiveStatChangeSubstances;
        [NMS(Size = 0x7, EnumType = typeof(GcSettlementStatType.SettlementStatTypeEnum))]
        /* 0x4D10 */ public NMSString0x10[] NegativeStatChangeSubstances;
        [NMS(Size = 0x7, EnumType = typeof(GcSettlementStatType.SettlementStatTypeEnum))]
        /* 0x4D80 */ public NMSString0x20A[] PositiveFakePerkOSDLocIDs;
        [NMS(Size = 0x7, EnumType = typeof(GcSettlementStatType.SettlementStatTypeEnum))]
        /* 0x4E60 */ public NMSString0x20A[] NegativeFakePerkOSDLocIDs;
        [NMS(Size = 0x7, EnumType = typeof(GcSettlementStatType.SettlementStatTypeEnum))]
        /* 0x4F40 */ public NMSString0x20A[] ProcPerkDescriptions;
        [NMS(Size = 0x7, EnumType = typeof(GcSettlementStatType.SettlementStatTypeEnum))]
        /* 0x5020 */ public NMSString0x20A[] ShortPolicyLocIDs;
        [NMS(Size = 0x7, EnumType = typeof(GcSettlementStatType.SettlementStatTypeEnum))]
        /* 0x5100 */ public NMSString0x20A[] LongPolicyLocIDs;
        [NMS(Size = 0x7, EnumType = typeof(GcSettlementStatType.SettlementStatTypeEnum))]
        /* 0x51E0 */ public NMSString0x20A[] ShortResearchLocIDs;
        [NMS(Size = 0x7, EnumType = typeof(GcSettlementStatType.SettlementStatTypeEnum))]
        /* 0x52C0 */ public NMSString0x20A[] LongResearchLocIDs;
        [NMS(Size = 0x7, EnumType = typeof(GcSettlementStatType.SettlementStatTypeEnum))]
        /* 0x53A0 */ public NMSString0x20A[] ShortAltResearchLocIDs;
        [NMS(Size = 0x7, EnumType = typeof(GcSettlementStatType.SettlementStatTypeEnum))]
        /* 0x5480 */ public NMSString0x20A[] LongAltResearchLocIDs;
        /* 0x5560 */ public List<GcSettlementGiftDetails> GekGifts;
        /* 0x5570 */ public List<GcSettlementGiftDetails> KorvaxGifts;
        /* 0x5580 */ public List<GcSettlementGiftDetails> VykeenGifts;
        /* 0x5590 */ public List<GcSettlementGiftDetails> Gifts;
        /* 0x55A0 */ public List<NMSString0x10> TechGiftPerks;
        /* 0x55B0 */ public List<GcSettlementJobDetails> JobTypes;
    }
}
