using libMBIN.NMS.GameComponents;
using System.Collections.Generic;

namespace libMBIN.NMS.Globals
{
    [NMS(GUID = 0x61BB4E398201BB9, NameHash = 0x8652A1B779227539)]
    public class GcSettlementGlobals : NMSTemplate
    {
        /* 0x0000 */ public List<NMSString0x20A> ScanEventsThatPreventSentinelAlert;
        /* 0x0010 */ public ulong BuildingUpgradeTimeInSeconds;
        /* 0x0018 */ public ulong BuildingFreeUpgradeTimeInSeconds;
        /* 0x0020 */ public int JudgementWaitTimeMin;
        /* 0x0024 */ public int JudgementWaitTimeMax;
        /* 0x0028 */ public float BuildingJudgementPriorityChance;
        /* 0x002C */ public float VisitorJudgementSelector;
        /* 0x0030 */ public float PolicyJudgementSelector;
        /* 0x0034 */ public float RequestJudgementSelector;
        /* 0x0038 */ public float ConflictJudgementSelector;
        /* 0x003C */ public int MaxNPCPopulation;
        /* 0x0040 */ public bool DebugForceShowHiddenPerks;
        /* 0x0044 */ public float SettlementEntryMessageDistance;
        /* 0x0048 */ public NMSString0x10 SettlementMiniExpeditionMissionID;
        /* 0x0058 */ public float SettlementMiniExpeditionSuccessChance;
        [NMS(Size = 0x36, EnumType = typeof(GcBuildingClassification.BuildingClassEnum))]
        /* 0x0060 */ public ulong[] SettlementBuildingTimes;
        [NMS(Size = 0x36, EnumType = typeof(GcBuildingClassification.BuildingClassEnum))]
        /* 0x0210 */ public GcSettlementBuildingCost[] SettlementBuildingCosts;
        /* 0x3ED0 */ public List<GcSettlementJudgementData> Judgements;
        /* 0x3EE0 */ public List<GcSettlementCustomJudgement> CustomJudgements;
        [NMS(Size = 0x36, EnumType = typeof(GcBuildingClassification.BuildingClassEnum))]
        /* 0x3EF0 */ public GcSettlementStatChangeArray[] SettlementBuildingStatRewards;
        /* 0x4250 */ public NMSString0x10 SettlementCostGek;
        /* 0x4260 */ public NMSString0x10 SettlementCostKorvax;
        /* 0x4270 */ public NMSString0x10 SettlementCostVykeen;
        /* 0x4280 */ public int MaxPerksCount;
        /* 0x4284 */ public int MinInitialPositivePerksCount;
        /* 0x4288 */ public int MaxInitialPositivePerksCount;
        /* 0x428C */ public int MinInitialNegativePerksCount;
        /* 0x4290 */ public int MaxInitialNegativePerksCount;
        [NMS(Size = 0x7, EnumType = typeof(GcSettlementStatType.SettlementStatTypeEnum))]
        /* 0x4294 */ public int[] StatsMinValues;
        [NMS(Size = 0x7, EnumType = typeof(GcSettlementStatType.SettlementStatTypeEnum))]
        /* 0x42B0 */ public int[] StatsMaxValues;
        [NMS(Size = 0x7, EnumType = typeof(GcSettlementStatType.SettlementStatTypeEnum))]
        /* 0x42CC */ public int[] InitialStatsMinValues;
        /* 0x42E8 */ public int InitialBuildingCountMin;
        /* 0x42EC */ public int InitialBuildingCountMax;
        [NMS(Size = 0x7, EnumType = typeof(GcSettlementStatType.SettlementStatTypeEnum))]
        /* 0x42F0 */ public int[] InitialStatsMaxValues;
        [NMS(Size = 0x7, EnumType = typeof(GcSettlementStatType.SettlementStatTypeEnum))]
        /* 0x430C */ public bool[] StatIsGoodWhenPositive;
        [NMS(Size = 0x7, EnumType = typeof(GcSettlementStatType.SettlementStatTypeEnum))]
        /* 0x4314 */ public float[] NormalisedStatBadThresholds;
        [NMS(Size = 0x7, EnumType = typeof(GcSettlementStatType.SettlementStatTypeEnum))]
        /* 0x4330 */ public float[] NormalisedStatGoodThresholds;
        /* 0x4350 */ public Colour PositiveStatColour;
        /* 0x4360 */ public Colour NegativeStatColour;
        /* 0x4370 */ public ulong ProductionSlotTimerOffsetInSeconds;
        /* 0x4378 */ public ulong ProductionCycleDurationInSeconds;
        /* 0x4380 */ public ulong AlertCycleDurationInSeconds;
        /* 0x4388 */ public int MaxProductionSlotUnits;
        /* 0x438C */ public int ProductUnitsPerCycleRateModifier;
        /* 0x4390 */ public int SubstanceUnitsPerCycleRateModifier;
        /* 0x4394 */ public int InitialDebtCycles;
        /* 0x4398 */ public int DailyDebtPaymentModifier;
        /* 0x439C */ public int AlertUnitsPerCycleRateModifier;
        [NMS(Size = 0x7, EnumType = typeof(GcSettlementStatType.SettlementStatTypeEnum))]
        /* 0x43A0 */ public int[] StatProductivityContributionModifiers;
        [NMS(Size = 0x7, EnumType = typeof(GcSettlementStatType.SettlementStatTypeEnum))]
        /* 0x43BC */ public bool[] StatProductionIsNegativeWhenBad;
        [NMS(Size = 0x7, EnumType = typeof(GcSettlementStatType.SettlementStatTypeEnum))]
        /* 0x43C8 */ public NMSString0x10[] PolicyPerks;
        [NMS(Size = 0x7, EnumType = typeof(GcSettlementStatType.SettlementStatTypeEnum))]
        /* 0x4438 */ public NMSString0x10[] ResearchPerks;
        [NMS(Size = 0x7, EnumType = typeof(GcSettlementStatType.SettlementStatTypeEnum))]
        /* 0x44A8 */ public NMSString0x10[] AltResearchPerks;
        [NMS(Size = 0x7, EnumType = typeof(GcSettlementStatType.SettlementStatTypeEnum))]
        /* 0x4518 */ public GcSettlementStatStrengthData[] PerkStatStrengthValues;
        /* 0x46A0 */ public List<NMSString0x10> GekProductionElements;
        /* 0x46B0 */ public List<NMSString0x10> KorvaxProductionElements;
        /* 0x46C0 */ public List<NMSString0x10> VykeenProductionElements;
        /* 0x46D0 */ public List<NMSString0x10> PoorProductionElements;
        /* 0x46E0 */ public List<NMSString0x10> NeutralProductionElements;
        /* 0x46F0 */ public List<NMSString0x10> RichProductionElements;
        [NMS(Size = 0x7, EnumType = typeof(GcSettlementJudgementType.SettlementJudgementTypeEnum))]
        /* 0x4700 */ public NMSString0x20A[] JudgementUpdateTitles;
        [NMS(Size = 0x7, EnumType = typeof(GcSettlementJudgementType.SettlementJudgementTypeEnum))]
        /* 0x47E0 */ public NMSString0x20A[] JudgementUpdateMainText;
        [NMS(Size = 0x7, EnumType = typeof(GcSettlementJudgementType.SettlementJudgementTypeEnum))]
        /* 0x48C0 */ public NMSString0x20A[] JudgementUpdateSubtitles;
        [NMS(Size = 0x7, EnumType = typeof(GcSettlementStatType.SettlementStatTypeEnum))]
        /* 0x49A0 */ public NMSString0x20A[] PositiveStatChangeOSDLocIDs;
        [NMS(Size = 0x7, EnumType = typeof(GcSettlementStatType.SettlementStatTypeEnum))]
        /* 0x4A80 */ public NMSString0x20A[] NegativeStatChangeOSDLocIDs;
        [NMS(Size = 0x7, EnumType = typeof(GcSettlementStatType.SettlementStatTypeEnum))]
        /* 0x4B60 */ public NMSString0x10[] PositiveStatChangeSubstances;
        [NMS(Size = 0x7, EnumType = typeof(GcSettlementStatType.SettlementStatTypeEnum))]
        /* 0x4BD0 */ public NMSString0x10[] NegativeStatChangeSubstances;
        [NMS(Size = 0x7, EnumType = typeof(GcSettlementStatType.SettlementStatTypeEnum))]
        /* 0x4C40 */ public NMSString0x20A[] PositiveFakePerkOSDLocIDs;
        [NMS(Size = 0x7, EnumType = typeof(GcSettlementStatType.SettlementStatTypeEnum))]
        /* 0x4D20 */ public NMSString0x20A[] NegativeFakePerkOSDLocIDs;
        [NMS(Size = 0x7, EnumType = typeof(GcSettlementStatType.SettlementStatTypeEnum))]
        /* 0x4E00 */ public NMSString0x20A[] ProcPerkDescriptions;
        [NMS(Size = 0x7, EnumType = typeof(GcSettlementStatType.SettlementStatTypeEnum))]
        /* 0x4EE0 */ public NMSString0x20A[] ShortPolicyLocIDs;
        [NMS(Size = 0x7, EnumType = typeof(GcSettlementStatType.SettlementStatTypeEnum))]
        /* 0x4FC0 */ public NMSString0x20A[] LongPolicyLocIDs;
        [NMS(Size = 0x7, EnumType = typeof(GcSettlementStatType.SettlementStatTypeEnum))]
        /* 0x50A0 */ public NMSString0x20A[] ShortResearchLocIDs;
        [NMS(Size = 0x7, EnumType = typeof(GcSettlementStatType.SettlementStatTypeEnum))]
        /* 0x5180 */ public NMSString0x20A[] LongResearchLocIDs;
        [NMS(Size = 0x7, EnumType = typeof(GcSettlementStatType.SettlementStatTypeEnum))]
        /* 0x5260 */ public NMSString0x20A[] ShortAltResearchLocIDs;
        [NMS(Size = 0x7, EnumType = typeof(GcSettlementStatType.SettlementStatTypeEnum))]
        /* 0x5340 */ public NMSString0x20A[] LongAltResearchLocIDs;
        /* 0x5420 */ public List<GcSettlementGiftDetails> GekGifts;
        /* 0x5430 */ public List<GcSettlementGiftDetails> KorvaxGifts;
        /* 0x5440 */ public List<GcSettlementGiftDetails> VykeenGifts;
        /* 0x5450 */ public List<GcSettlementGiftDetails> Gifts;
        /* 0x5460 */ public List<NMSString0x10> TechGiftPerks;
        /* 0x5470 */ public List<GcSettlementJobDetails> JobTypes;
    }
}
