namespace libMBIN.Models.Structs
{
    [NMS( GUID = 0xD25256FB1959D22E )]
    public class GcUIGlobals : NMSTemplate
    {
        /* 0x0 */ public bool LoadPagesFromMetadataCache;
        /* 0x1 */ public bool AlwaysCloseQuickMenu;
        /* 0x2 */ public bool UseWorldNodesForRepair;
        /* 0x3 */ public bool RepairTechUseTechIcon;
        /* 0x4 */ public bool DebugMissionLogText;
        /* 0x5 */ public bool DebugShowMaintenanceScreenCentre;
        /* 0x6 */ public bool DebugPopupSizes;
        /* 0x7 */ public bool DebugInventoryIndices;
        /* 0x8 */ public bool FixedInventoryIconPositions;
        [NMS(Size = 0x3)]
        /* 0xC */ public Vector2f[] InventoryIconPositions;
        /* 0x30 */ public Colour PickedItemBorderColour;
        /* 0x40 */ public Colour MultiplayerMissionParticipantsColour;
        [NMS(Size = 0x10)]
        /* 0x50 */ public string MultiplayerMissionInteractStartTrigger;
        [NMS(Size = 0x10)]
        /* 0x60 */ public string MultiplayerMissionInteractEndTrigger;
		/* 0x70 */ public float NotificationHazardMinTimeAfterRecharge;
		/* 0x74 */ public float LoadFadeInDefaultTime;
		/* 0x78 */ public float DroneIndicatorRadius;
		/* 0x7C */ public float DroneIndicatorCentreRadiusMax;
		/* 0x80 */ public float DroneIndicatorCentreRadiusMin;
		/* 0x84 */ public float DroneIndicatorFadeRange;
		/* 0x88 */ public float WantedDetectMessageTime;
		/* 0x8C */ public float WantedDetectMinTimeout;
		/* 0x90 */ public float TakeoffFuelMessageTime;
		/* 0x94 */ public float MarkerHorizonOffsetAngle;
		/* 0x98 */ public float MarkerHorizonMinOffset;
		/* 0x9C */ public float MarkerHorizonApproachAngle;
		/* 0xA0 */ public float MarkerOffsetTypeAngle;
		/* 0xA4 */ public float MarkerOffsetTypeAngleBattle;
		/* 0xA8 */ public float MarkerOffsetTypeAngleBounty;
		/* 0xAC */ public float MarkerOffsetTypeAnglePlayerShip;
		/* 0xB0 */ public float MarkerHorizonOffPlanetLightBeamAngle;
		/* 0xB4 */ public float MarkerHorizonShipApproachOffset;
		/* 0xB8 */ public float TransferPopupCursorOffsetFactor;
		/* 0xBC */ public float ScannableIconMergeAngle;
		/* 0xC0 */ public float MissionObjectiveBaseHeight;
		/* 0xC4 */ public float MarkerTagAppearDelay;
		/* 0xC8 */ public Vector2f CompassCentre;
		/* 0xD0 */ public float CompassHeight;
		/* 0xD4 */ public float CompassWidth;
		/* 0xD8 */ public float CompassDistanceScaleMin;
		/* 0xDC */ public float CompassDistanceScaleRange;
		/* 0xE0 */ public float CompassDistanceScale;
		/* 0xE4 */ public float CompassDistanceMaxAngle;
		/* 0xE8 */ public float CompassDistanceYOffset;
		/* 0xEC */ public float CompassAngleClamp;
		/* 0xF0 */ public float CompassAngleFade;
        /* 0xF4 */ public TkCurveType CompassCurve;

        /* 0xF8 */ public float BaseComplexityDangerFactor;
        /* 0xFC */ public float BaseComplexityWarningFactor;
        /* 0x100 */ public Colour BaseComplexityDefaultColour;
        /* 0x110 */ public Colour BaseComplexityWarningColour;
        /* 0x120 */ public Colour BaseComplexityDangerColour;
        /* 0x130 */ public float MarkerRingInnerRadius;
        /* 0x134 */ public float MarkerRingOuterRadius;
        /* 0x140 */ public Colour MarkerRingBGColour;

        /* 0x150 */ public float RepairTechRepairedWaitTime1;
        /* 0x154 */ public float RepairTechRepairedWaitTime2;
        /* 0x158 */ public float RepairTechRepairedMessageTime;
        /* 0x15C */ public float TechPopupRepairLayerHeight;
        /* 0x160 */ public float TechPopupBuildLayerHeight;
        /* 0x164 */ public float TechPopupRequirementHeight;
        /* 0x168 */ public float DamageTrackArrowTime;
        /* 0x16C */ public float HUDMarkerObjectMinScreenDistance;
        /* 0x170 */ public float HUDMarkerDistanceOrTimeDistance;
        /* 0x174 */ public float MarkerComponentOffset;
        /* 0x178 */ public float RepairTechLabelOffset;
        /* 0x17C */ public float MaintenanceIconFadeStart;
        /* 0x180 */ public float MaintenanceIconFadeTime;


        [NMS(Size = 0xC, Ignore = true)]
        /* 0x184 */ public byte[] Padding184;
        /* 0x190 */ public TkModelRendererData RepairCamera;
        /* 0x240 */ public TkModelRendererData RepairWeaponCamera;
        /* 0x2F0 */ public TkModelRendererData RepairBackpackCamera;
        /* 0x3A0 */ public TkModelRendererData RepairShipCamera;
        /* 0x450 */ public Vector2f BinocularsDiscoveryPos;
        /* 0x460 */ public Colour InteractionLabelCostColour;

        /* 0x470 */ public Colour InteractionLabelPickupColour;
        /* 0x480 */ public Colour InteractionLabelPickupFillColour;
        /* 0x490 */ public float RefinerPadStartTime;
        /* 0x494 */ public float RefinerPadStartDecayTime;
        /* 0x498 */ public float RefinerBeginDialInnerRadius;
        /* 0x49C */ public float RefinerProgressDialInnerRadius;
        /* 0x4A0 */ public Vector4f DefaultRefinerOffsetIn;
        /* 0x4B0 */ public Vector4f DefaultRefinerOffsetOut;
        /* 0x4C0 */ public Vector2f RefinerParallax;
        /* 0x4C8 */ public Vector2f ModelViewWorldParallax;
        /* 0x4D0 */ public Vector2f HUDPlayerSentinelPulseFreq;
        /* 0x4D8 */ public Vector2f HUDPlayerSentinelPulseSize;
        /* 0x4E0 */ public float HUDPlayerSentinelPulseWidth;
        /* 0x4E4 */ public float HUDPlayerSentinelRangeFactor;
        /* 0x4E8 */ public float HUDPlayerSentinelPulseScanFreq;
        /* 0x4EC */ public float HUDPlayerPhonePulseScanFreq;
        /* 0x4F0 */ public float RefinerAutoCloseTime;
        /* 0x500 */ public Colour RefinerBackgroundColour;

        /* 0x510 */ public Colour RefinerErrorBackgroundColour;
        /* 0x520 */ public Colour TransferSendPopupColour;
        /* 0x530 */ public float BountyMarkerOffset;
        /* 0x534 */ public float TransitionOffset;
        /* 0x538 */ public float PageTurnTime;
        /* 0x53C */ public TkCurveType PageTurnCurve;
        /* 0x540 */ public TkCurveType PageTurnFadeCurve;
        /* 0x544 */ public float LowHealthShieldMin;
        /* 0x548 */ public float LowHealthShieldFactor;
        /* 0x54C */ public int MaxDialogCharSizeRoman;
        [NMS(Size = 0x20)]
        /* 0x550 */ public string MaxDialogCharSizeRomanString;
        /* 0x570 */ public int MaxDialogCharSizeIdeographic;
        [NMS(Size = 0x20)]
        /* 0x574 */ public string MaxDialogCharSizeIdeographicString;
        /* 0x594 */ public float ShipOverheatSwitchMessageWait;
        /* 0x598 */ public float ShipOverheatSwitchMessageTime;
        /* 0x59C */ public bool LeadTargetEnabled;
        [NMS(Size = 0x3, Ignore = true)]
        /* 0x59D */ public byte[] Padding59D;
        /* 0x5A0 */ public Vector2f SaveIconPosition;
        /* 0x5A8 */ public float MissionStartEndTime;
        /* 0x5AC */ public float MissionStartEndOSDTime;
        /* 0x5B0 */ public float MissionStartEndOSDTimeProcedural;
        /* 0x5B4 */ public float StandingRewardOSDTime;
        /* 0x5C0 */ public Colour MissionOSDMessageBarColour;

        /* 0x5D0 */ public Colour NotificationDefaultColour;
        /* 0x5E0 */ public Colour NotificationDangerColour;
        /* 0x5F0 */ public Colour NotificationInfoColour;
        /* 0x600 */ public Colour NotificationUrgentColour;
        /* 0x610 */ public float ShipDamageDirectionIndicatorRadius;
        /* 0x614 */ public float ShipDamageDirectionIndicatorFadeRange;
        /* 0x618 */ public float OnFootDamageDirectionIndicatorRadius;
        /* 0x61C */ public float OnFootDamageDirectionIndicatorFadeRange;
        /* 0x620 */ public float DamageDirectionIndicatorOnScreenRadiusMultiplier;
        /* 0x624 */ public Vector2f DialogPageCursorOffset;
        /* 0x62C */ public int MissionSpecificMissionPercent;
        /* 0x630 */ public int MissionLoopCount;
        /* 0x634 */ public int MissionSeedOffset;


        [NMS(Size = 0x8, Ignore = true)]
        /* 0x638 */ public byte[] Padding638;
        /* 0x640 */ public Vector4f SpaceMapCockpitOffset;
        /* 0x650 */ public float SpaceMapCockpitScale;
        /* 0x654 */ public float SpaceMapCockpitAngle;
        /* 0x658 */ public float TargetDisplayScale;
        /* 0x65C */ public float TargetDisplayShipScale;
        [NMS(Size = 0x10)]
        /* 0x660 */ public string TargetDisplayShipOffset;
        /* 0x670 */ public float TargetDisplayDamageFlashTime;


        [NMS(Size = 0xC, Ignore = true)]
        /* 0x674 */ public byte[] Padding674;
        /* 0x680 */ public GcScanEffectData TargetDisplayScanEffect;
        /* 0x6D0 */ public bool ProgressiveDialogStyle;
        /* 0x6D4 */ public float CommunicatorMessageTime;
        /* 0x6E0 */ public Colour CommunicatorMessageColour;

        /* 0x6F0 */ public float GridFlickerBaseAlpha;
        /* 0x6F4 */ public float GridFlickerFreq;
        /* 0x6F8 */ public float GridFlickerAmp;
        /* 0x6FC */ public float HUDMarkerLabelWidthMultiplier;
        /* 0x700 */ public float HUDMarkerLabelBaseWidth;
        /* 0x704 */ public float HUDMarkerLabelArriveDistance;
        /* 0x708 */ public float HUDMarkerLabelDisplayDistance;
        /* 0x70C */ public float HUDMarkerNonActiveMissionAlpha;
        /* 0x710 */ public bool DebugMarkerLabels;
        [NMS(Size = 0xF, Ignore = true)]
        /* 0x711 */ public byte[] Padding711;
        /* 0x720 */ public GcScanEffectData DebugEditorPreviewEffect;
        /* 0x770 */ public bool ShowDamageNumbers;
        /* 0x774 */ public float QuickMenuCloseTime;
        /* 0x778 */ public float QuickMenuErrorTime;
        /* 0x77C */ public float FrontendWaitResponse;
        /* 0x780 */ public float FrontendWaitInitial;
        /* 0x784 */ public float FrontendWaitInitialTerminal;
        /* 0x788 */ public float FrontendWaitFadeTextOut;
        /* 0x78C */ public float FrontendWaitFadeTextFrameOut;
        /* 0x790 */ public float FrontendWaitFadeProgressiveDialogOut;
        /* 0x794 */ public float FrontendWaitResponseOffset;
        /* 0x798 */ public float TalkBoxAlienTextSpeed;
        /* 0x79C */ public float TalkBoxAlienTextTimeMin;
        /* 0x7A0 */ public float TalkBoxAlienTextTimeMax;
        /* 0x7A4 */ public float DescriptionTextDelay;
        /* 0x7A8 */ public float DescriptionTextSpeed;
        /* 0x7AC */ public float DescriptionTextSpeedProgressive;
        /* 0x7B0 */ public float DescriptionTextTimeMin;
        /* 0x7B4 */ public float DescriptionTextTimeMax;
        /* 0x7B8 */ public float ConsoleTextSpeed;
        /* 0x7BC */ public float ConsoleTextTimeMin;
        /* 0x7C0 */ public float ConsoleTextTimeMax;
        /* 0x7C4 */ public float HoverOffscreenBorder;
        /* 0x7C8 */ public float TimedEventLookTime;
        /* 0x7CC */ public float DamageImpactMergeTime;
        /* 0x7D0 */ public float DamageImpactTimeBetweenNumbers;
        /* 0x7D4 */ public float DamageImpactMinDistance;
        /* 0x7D8 */ public float DamagePerSecondSampleTime;
        /* 0x7DC */ public float DamageNumberTime;
        /* 0x7E0 */ public float DamageNumberSizeInShip;
        /* 0x7E4 */ public float DamageNumberSize;
        /* 0x7E8 */ public float DamageNumberSizeCritMultiplier;
        /* 0x7EC */ public float DamageNumberBlackAlpha;
        /* 0x7F0 */ public float DamageNumberOutline;
        /* 0x7F4 */ public float DamageNumberOutline2;
        /* 0x7F8 */ public float DamageNumberOffsetX;
        /* 0x7FC */ public float DamageNumberOffsetY;
        /* 0x800 */ public Vector2f DamageNumberSideSpeed;
        /* 0x808 */ public float DamageNumberFadeIn;
        /* 0x80C */ public float DamageNumberFadeOut;
        /* 0x810 */ public float DamageNumberUpOffset;
        /* 0x814 */ public TkCurveType DamageNumberUpCurve;
        /* 0x820 */ public Colour DamageNumberCriticalColour;

        /* 0x830 */ public Colour DamageNumberIneffectiveColour;
        /* 0x840 */ public Colour PhotoModeSelectedColour;
        /* 0x850 */ public Colour PhotoModeUnselectedColour;
        /* 0x860 */ public Colour FuelBgColour;
        /* 0x870 */ public float PhotoModeValueAlpha;
        /* 0x874 */ public float PhotoModeTimeofDayChange;
        /* 0x878 */ public float FrigateIconOffset;
        /* 0x87C */ public float DelayBeforeHidingHangarAfterGalaxyMap;
        /* 0x880 */ public float DelayBeforeShowingHangarIntoGalaxyMap;
        /* 0x884 */ public float FreighterSummonTurn;
        /* 0x888 */ public float FreighterSummonPitch;
        /* 0x88C */ public float FreighterSummonOffset;
        /* 0x890 */ public float FreighterSummonDelay;
        /* 0x894 */ public int FreighterSummonTurnNumTries;
        /* 0x898 */ public float FreighterSummonTurnAngleIncrement;
        /* 0x89C */ public float FreighterSummonGridSize;
        /* 0x8A0 */ public float FreighterCommanderMarkerMinDistance;
        /* 0x8A4 */ public float FreighterBaseIconOffset;
        /* 0x8A8 */ public float FreighterSurfaceMinAngle;
        /* 0x8AC */ public float FreighterSummonPulseRate;
        /* 0x8B0 */ public float FreighterSummonPulseFadeAmount;
        /* 0x8B4 */ public float FreighterSummonPlanetOffset;
        /* 0x8B8 */ public float FreighterSummonLookTime;
        /* 0x8BC */ public float FreighterHighlightRange;
        /* 0x8C0 */ public GcScanEffectData FreighterSummonScanEffect;
        /* 0x910 */ public Colour FreighterSummonScanEffectColourBlocked;
        /* 0x920 */ public Colour FreighterSummonScanEffectColourHighlight;
        /* 0x930 */ public float PirateCountdownTime;
        /* 0x934 */ public float PirateAttackIndicatorWidth;
        /* 0x938 */ public float PirateAttackIndicatorRadius;
        /* 0x93C */ public float PirateAttackProbeDisplayFinishFactor;
        /* 0x940 */ public float HazardArrowsLevel2Threshold;
        /* 0x944 */ public float HazardArrowsLevel3Threshold;
        /* 0x948 */ public float ArrowBounceLength;
        /* 0x94C */ public float ArrowBounceRate;
        /* 0x950 */ public float ArrowBounceRightRate1;
        /* 0x954 */ public float ArrowBounceRightRate2;
        /* 0x958 */ public TkCurveType ArrowBounceRightCurve;
        /* 0x95C */ public float ArrowBounceLeftRate1;
        /* 0x960 */ public float ArrowBounceLeftRate2;
        /* 0x964 */ public float ArrowBounceLeftRate3;
        /* 0x968 */ public TkCurveType ArrowBounceLeftCurve;
        /* 0x96C */ public float PlanetScanDelayTime;
        /* 0x970 */ public float AlwaysShowIconFadeDistance;
        /* 0x974 */ public float AlwaysShowIconFadeRange;
        /* 0x978 */ public float FrigatePurchaseNotificationResetDistanceMultiplier;
        /* 0x97C */ public float FreighterLeaderIconDistance;
        /* 0x980 */ public float FreighterEntranceOffset;
        /* 0x984 */ public float ShipHeadsUpDisplayDistance;
        /* 0x988 */ public float ShipHeadsUpLineFadeTime;
        /* 0x98C */ public float CrosshairAimTime;
        /* 0x990 */ public float CrosshairAimOffTime;
        /* 0x994 */ public float CrosshairInnerMinFade;
        /* 0x998 */ public float CrosshairInnerMinFadeRange;
        /* 0x99C */ public float CrosshairLeadScaleIn;
        /* 0x9A0 */ public float CrosshairLeadInDelay;
        /* 0x9A4 */ public float CrosshairLeadInTime;
        /* 0x9A8 */ public float CrosshairLeadCornerOffset;
        /* 0x9AC */ public float CrosshairLeadTopOffset;
        /* 0x9B0 */ public float CrosshairLeadTopLock;
        /* 0x9B4 */ public float CrosshairLeadPulseSize;
        /* 0x9B8 */ public TkCurveType CrosshairLeadScaleCurve;
        /* 0x9BC */ public float CrosshairSpringTime;
        /* 0x9C0 */ public float CrosshairSpringAimTime;
        /* 0x9C4 */ public float CrosshairLeadSpring;
        /* 0x9C8 */ public float CrosshairLeadSpringOff;
        /* 0x9CC */ public float CrosshairLeadFadeRange;
        /* 0x9D0 */ public float CrosshairLeadFadeSize;
        /* 0x9E0 */ public Colour CrosshairLeadThreatColour;

        /* 0x9F0 */ public Colour CrosshairLeadPassiveColour;
        /* 0xA00 */ public float CrosshairInterceptSize;
        /* 0xA04 */ public float CrosshairInterceptBaseSize;
        /* 0xA08 */ public float CrosshairInterceptCentreBaseSize;
        /* 0xA0C */ public float CrosshairInterceptSpringTime;
        /* 0xA10 */ public float CrosshairInterceptAlpha;
        /* 0xA14 */ public float CrosshairInterceptLockRange;
        /* 0xA18 */ public float CrosshairTargetLockSize;
        /* 0xA1C */ public TkCurveType CrosshairTargetLockCurve;
        /* 0xA20 */ public TkCurveType CrosshairTargetLockAlphaCurve;
        /* 0xA30 */ public Colour CrosshairColour;


        /* 0xA40 */ public TkHitCurveData CrosshairLeadHitCurve;

        /* 0xA50 */ public TkHitCurveData ShootableHitCurve;
        /* 0xA60 */ public int ControlScrollSteps;
        /* 0xA64 */ public float ControlScrollDistance;
        /* 0xA70 */ public Colour SelectedControlColour;

        /* 0xA80 */ public Colour RemappedControlColour;
        /* 0xA90 */ public float CreatureRoutineMarkerTime;
        /* 0xA94 */ public int CreatureRoutineRegionsPerFrame;
        /* 0xA98 */ public float SpaceMarkersOffset;
        /* 0xA9C */ public float SpaceMarkersBattleOffset;
        /* 0xAA0 */ public float LargeSpaceIconSize;
        /* 0xAA4 */ public float SmallSpaceIconSize;
        /* 0xAA8 */ public Vector2f TrackTypeIconOffset;
        /* 0xAB0 */ public float TrackTypeIconSize;
        /* 0xAB4 */ public float TrackPrimaryCentreOffset;
        /* 0xAB8 */ public float TrackTimerAlpha;
        /* 0xABC */ public float TrackTimerRadarPulseSize;
        /* 0xAC0 */ public float TrackTimerIconOuterRadius;
        /* 0xAC4 */ public float TrackTimerIconInnerRadius;
        /* 0xAC8 */ public float TrackTimerIconExclaimRadius;
        /* 0xACC */ public float TrackGlowBase;
        /* 0xAD0 */ public float TrackHitPulseTime;
        /* 0xAD4 */ public float TrackGlowCritical;
        /* 0xAD8 */ public float TrackGlowHit;
        /* 0xADC */ public float MissileCentreOffset;
        /* 0xAE0 */ public float TrackMissileTargetPulseRate;
        /* 0xAE4 */ public float TrackScaleCritical;
        /* 0xAE8 */ public float TrackScaleHit;
        /* 0xAEC */ public float TrackLeadTargetInScale;
        /* 0xAF0 */ public float TrackReticuleScale;
        /* 0xAF4 */ public float TrackReticuleAngle;
        /* 0xAF8 */ public float TrackReticuleInTime;
        /* 0xAFC */ public float TrackReticuleInactiveTime;
        /* 0xB00 */ public float TrackReticuleRandomTime;
        /* 0xB04 */ public float TrackReticuleRandomDelay;
        /* 0xB08 */ public TkCurveType TrackReticuleInCurve;
        /* 0xB0C */ public TkCurveType TrackReticuleInAngleCurve;
        /* 0xB10 */ public float CreatureReticuleScale;
        /* 0xB14 */ public TkCurveType CreatureReticuleScaleCurve;
        /* 0xB18 */ public TkCurveType CreatureReticuleAlphaCurve;
        /* 0xB1C */ public float HUDPlayerTrackNoSightPulse;
        /* 0xB20 */ public float HUDPlayerTrackTimerStart;
        /* 0xB24 */ public float HUDPlayerTrackTimerStartFade;
        /* 0xB28 */ public float HUDPlayerTrackTimerEnd;
        /* 0xB2C */ public float HUDPlayerTrackTimerPulseRate;
        /* 0xB30 */ public float TrackCritCurve;
        /* 0xB34 */ public Vector2f TrackCriticalHitOffset;
        /* 0xB3C */ public float TrackCriticalHitSize;
        /* 0xB40 */ public float TrackCriticalPulseTime;
        /* 0xB44 */ public float ThirdPersonCrosshairDistance;
        /* 0xB48 */ public float ThirdPersonCrosshairCircle1Distance;
        /* 0xB4C */ public float ThirdPersonCrosshairCircle2Distance;
        /* 0xB50 */ public float HUDPlayerTrackArrowShipLabelOffset;
        /* 0xB54 */ public float HUDPlayerTrackArrowIconPulseTime;
        /* 0xB58 */ public float HUDPlayerTrackArrowIconShowTime;
        /* 0xB5C */ public float HUDPlayerTrackArrowIconFadeTime;
        /* 0xB60 */ public Vector2f HUDPlayerTrackArrowIconPulseSize;
        /* 0xB68 */ public float HUDPlayerTrackArrowIconPulseWidth1;
        /* 0xB6C */ public float HUDPlayerTrackArrowIconPulseWidth2;
        /* 0xB70 */ public float HUDPlayerTrackArrowIconPulse2Alpha;
        /* 0xB74 */ public float HUDPlayerTrackArrowIconFadeDist;
        /* 0xB78 */ public float HUDPlayerTrackArrowIconFadeRange;
        /* 0xB7C */ public float HUDPlayerTrackArrowPulseOffset;
        /* 0xB80 */ public float HUDPlayerTrackArrowPulseRate;
        /* 0xB84 */ public Vector2f HUDPlayerTrackIconOffset;
        /* 0xB8C */ public float ShipFullscreenDamper;
        /* 0xB90 */ public float ShipDesatDamper;
        /* 0xB94 */ public float ScanEventArrowShipFadeRange;
        /* 0xB98 */ public float ScanEventArrowShipFadeDistance;
        /* 0xB9C */ public float ScanEventArrowPlayerFadeRange;
        /* 0xBA0 */ public float ScanEventArrowPlayerFadeDistance;
        /* 0xBA4 */ public float ScanEventArrowOffsetMultiplier;
        /* 0xBA8 */ public float ScanEventArrowOffsetMultiplierOneEvent;
        /* 0xBAC */ public float ScanEventArrowSecondaryAlpha;
        /* 0xBB0 */ public float ScanEventIconAudio;
        /* 0xBB4 */ public TkNGuiRectanglePulseEffect PulseBarData;
        /* 0xBC8 */ public TkNGuiRectanglePulseEffect PulseIconData;
        /* 0xBE0 */ public Colour PulseDamageColour;

        /* 0xBF0 */ public Colour PulseAlertColour;
        /* 0xC00 */ public float TechDisplayDelayTime;
        /* 0xC04 */ public float CriticalMessageTime;
        /* 0xC08 */ public int NumDeathQuotes;
        /* 0xC0C */ public bool EnableKanaConversion;
        /* 0xC10 */ public float HUDDisplayTime;
        /* 0xC14 */ public float HUDPlayerTrackDangerPulse;
        /* 0xC18 */ public float HUDPlayerTrackArrowTextOffset;
        /* 0xC1C */ public float HUDPlayerTrackArrowTextHeight;
        /* 0xC20 */ public Colour HUDPlayerTrackArrowTextColour;
        /* 0xC30 */ public float HUDPlayerTrackArrowHealthOffset;
        /* 0xC34 */ public Vector2f HUDPlayerTrackArrowHealthSize;
        /* 0xC3C */ public float HUDPlayerTrackArrowHealthGlowOffset;
        /* 0xC40 */ public Vector2f HUDPlayerTrackArrowHealthGlowSize;
        /* 0xC48 */ public float HUDPlayerTrackArrowTargetDist;
        /* 0xC4C */ public float HUDPlayerTrackArrowOffset;
        /* 0xC50 */ public float HUDPlayerTrackArrowScreenBorder;
        /* 0xC54 */ public float HUDPlayerTrackArrowSize;
        /* 0xC58 */ public float HUDPlayerTrackArrowSizeMin;
        /* 0xC5C */ public float HUDPlayerTrackArrowSizeMax;
        /* 0xC60 */ public float HUDPlayerTrackArrowIconSize;
        /* 0xC64 */ public float HUDPlayerTrackArrowArrowSize;
        /* 0xC68 */ public float HUDPlayerTrackArrowDotSize;
        /* 0xC70 */ public Colour HUDPlayerTrackArrowDotColour;

        /* 0xC80 */ public Colour HUDPlayerTrackArrowDotColourPolice;
        /* 0xC90 */ public Colour HUDPlayerTrackArrowDotColourPirate;
        /* 0xCA0 */ public Colour HUDWarningColour;
        /* 0xCB0 */ public Colour HUDNotifyColour;
        /* 0xCC0 */ public float HUDPlayerTrackArrowMinFadeDist;
        /* 0xCC4 */ public float HUDPlayerTrackArrowFadeRange;
        /* 0xCC8 */ public float IconBackgroundAlpha;
        /* 0xCCC */ public float WantedLevelWitnessPulseRate;
        /* 0xCD0 */ public float WantedLevelWitnessOffset;
        /* 0xCD4 */ public float WantedLevelTimeoutPulseRate;
        /* 0xCD8 */ public float WantedLevelWitnessAlpha;
        /* 0xCDC */ public float WantedLevelScanAlpha;
        /* 0xCE0 */ public float WantedLevelScannedRate;
        [NMS(Size = 0x37)]
        /* 0xCE4 */ public NMSString0x80[] StatIcons;
        /* 0x2864 */ public bool ShowJetpackNotificationForNonTerrain;

        /* 0x2868 */ public float StatsMessageDelayTime;
        /* 0x286C */ public int NotificationsResourceExtractHintCount;
        /* 0x2870 */ public float NotificationStaminaHintDistanceWalked;
        /* 0x2874 */ public float NotificationMinVisibleTime;
        /* 0x2878 */ public float NotificationHazardSafeThreshold;
        /* 0x287C */ public float NotificationHazardTimer;
        /* 0x2880 */ public float NotificationInteractHintStartTime;
        /* 0x2884 */ public float NotificationBuildHintStartTime;
        /* 0x2888 */ public float NotificationJetpackTime;
        /* 0x288C */ public float NotificationShieldTime;
        /* 0x2890 */ public float NotificationShipBoostTime;
        /* 0x2894 */ public float NotificationCantFireTime;
        /* 0x2898 */ public float NotificationDangerTime;
        /* 0x289C */ public float NotificationScanTime;
        /* 0x28A0 */ public float NotificationScanTimeCutoff;
        /* 0x28A4 */ public float NotificationMessageCycleTime;
        /* 0x28A8 */ public float NotificationMaxPageHintTime;
        /* 0x28AC */ public float NotificationShipJumpMinTime;
        /* 0x28B0 */ public float NotificationShipJumpReminderTime;
        /* 0x28B4 */ public float NotificationShipJumpReminderTutorial;
        /* 0x28B8 */ public float NotificationShipBoostMinTime;
        /* 0x28BC */ public float NotificationShipBoostReminderTime;
        /* 0x28C0 */ public float NotificationShipBoostReminderTimeTutorial;
        /* 0x28C4 */ public float LandNotifySpeedThreshold;
        /* 0x28C8 */ public float LandNotifyHeightThreshold;
        /* 0x28CC */ public float NotificationTimeBeforeHeridiumMarker;
        /* 0x28D0 */ public float NotificationUrgentMessageTime;
        /* 0x28D4 */ public float NotificationGoToSpaceStationWait;
        /* 0x28D8 */ public float NotificationMonolithMissionWait;
        /* 0x28DC */ public float NotificationFinalMissionWait;
        /* 0x28E0 */ public float NotificationWaypointReachDistance;
        /* 0x28E4 */ public float NotificationBridgeReachDistance;
        /* 0x28E8 */ public float NotificationDiscoveryIdleTime;
        /* 0x28EC */ public float NotificationInfoIdleTime;
        /* 0x28F0 */ public float NotificationNewTechIdleTime;
        /* 0x28F4 */ public float NotificationScanEventMissionIdleTime;
        /* 0x28F8 */ public float NotificationDeviceIdleTime;
        /* 0x28FC */ public float NotificationMissionHintTime;
        /* 0x2900 */ public float NotificationMissionHintTimeCritical;
        /* 0x2904 */ public float NotificationMissionHintTimeSecondary;
        /* 0x2908 */ public Vector2f NotificationMissionHintPauseTime;
        /* 0x2910 */ public Vector2f NotificationMissionHintPauseTimeCritical;
        /* 0x2918 */ public Vector2f NotificationMissionHintPauseTimeSecondary;
        /* 0x2920 */ public float TooltipTime;
        /* 0x2924 */ public float InventoryIconTime;
        /* 0x2928 */ public float MessageNotificationTime;
        /* 0x292C */ public float MessageTimeQuick;
        /* 0x2930 */ public float DeathMessageSwitchTime;
        /* 0x2934 */ public float DeathMessageTotalTime;
        /* 0x2940 */ public Colour DeathMessageColour;

        /* 0x2950 */ public Colour PinnedRecipeBorder;
        [NMS(Size = 0x20)]
        /* 0x2960 */ public string DistanceUnitM;
        [NMS(Size = 0x20)]
        /* 0x2980 */ public string DistanceUnitKM;
        [NMS(Size = 0x20)]
        /* 0x29A0 */ public string DistanceUnitMpS;
        /* 0x29C0 */ public float ZoomHUDElementsOffsetX;
        /* 0x29C4 */ public float ZoomHUDElementsOffsetY;
        /* 0x29C8 */ public float ZoomHUDElementTime;
        /* 0x29CC */ public Vector2f PlanetLabelOffset;
        /* 0x29D4 */ public Vector2f PlanetMeasureOffset;
        /* 0x29DC */ public Vector2f PlanetLineOffset;
        /* 0x29E4 */ public float PlanetLabelTime;
        /* 0x29E8 */ public float PlanetLabelAngle;
        /* 0x29F0 */ public Colour ItemSlotColourSubstance;

        /* 0x2A00 */ public Colour ItemSlotColourTech;
        /* 0x2A10 */ public Colour ItemSlotColourTechCharge;
        /* 0x2A20 */ public Colour ItemSlotColourTechDamage;
        /* 0x2A30 */ public float ItemSlotColourTechChargeRate;
        /* 0x2A40 */ public Colour ItemSlotColourProduct;

        /* 0x2A50 */ public Colour ItemSlotTextColourSubstance;
        /* 0x2A60 */ public Colour ItemSlotTextColourTech;
        /* 0x2A70 */ public Colour ItemSlotTextColourProduct;
        /* 0x2A80 */ public float InteractionScanScanTime;
        /* 0x2A84 */ public float InteractionScanMinTime;
        /* 0x2A88 */ public float InteractionScanDisplayTime;
        /* 0x2A8C */ public float InteractionScanSlapTime;
        /* 0x2A90 */ public float InteractionScanSlapScale;
        /* 0x2A94 */ public float InteractionScanSlapOverallTime;
        /* 0x2A98 */ public TkCurveType InteractionScanSlapCurve;
        /* 0x2A9C */ public float ShipHUDMissileLockSizeMin;
        /* 0x2AA0 */ public float ShipHUDMissileLockSizeMax;
        /* 0x2AA4 */ public float ShipHUDMissileLockSpringSlow;
        /* 0x2AA8 */ public float ShipHUDMissileLockSpringFast;
        /* 0x2AAC */ public float ShipHUDMaxOffscreenTargetDist;
        /* 0x2AB0 */ public float ShipHUDTargetRadius;
        /* 0x2AB4 */ public float ShipHUDTargetTriangleRadius;
        /* 0x2AB8 */ public float ShipHUDTargetAlpha;
        /* 0x2ABC */ public float ShipHUDTargetArrowLength;
        /* 0x2AC0 */ public float ShipHUDTargetMinDist;
        /* 0x2AC4 */ public float ShipHUDTargetRange;
        /* 0x2AC8 */ public float ShipHUDTargetScale;
        /* 0x2ACC */ public float ShipHUDTargetArrowsRotationRate;
        /* 0x2AD0 */ public Colour ShipHUDTargetArrowsColourOutOfRange;
        /* 0x2AE0 */ public Colour ShipHUDTargetArrowsColourThreat;
        /* 0x2AF0 */ public Colour ShipHUDTargetArrowsColourLocal;
        [NMS(Size = 0x4)]
        /* 0x2B00 */ public Colour[] ShipHUDTargetArrowsColour;
        /* 0x2B40 */ public Colour ShipHUDAimTargetColour;

        /* 0x2B50 */ public Colour ShipHUDAimTargetCritColour;
        /* 0x2B60 */ public float ShipHUDHitPointTime;
        /* 0x2B64 */ public float ShipHUDHitPointSize;
        /* 0x2B68 */ public float TargetScreenFoV;
        /* 0x2B6C */ public float TargetScreenDistance;
        /* 0x2B70 */ public Vector2f TargetScreenCamOffset;
        /* 0x2B78 */ public float InventoryFullMessageRepeatTime;
        /* 0x2B7C */ public float HoldTimerResetTime;
        /* 0x2B80 */ public bool ModelRendererBGPass;
        /* 0x2B81 */ public bool ModelRendererPass1;
        /* 0x2B82 */ public bool ModelRendererPass2;
        [NMS(Size = 0x20)]
        /* 0x2B83 */ public string HUDTimeSunrise;
        [NMS(Size = 0x20)]
        /* 0x2BA3 */ public string HUDTimeSunset;
        /* 0x2BC4 */ public float HeatSpringTime;

        /* 0x2BC8 */ public float HeatAlertTime;
        /* 0x2BCC */ public float HeatAlertFixedTime;
        /* 0x2BD0 */ public float HeatAlertSpringTime;
        /* 0x2BD4 */ public float HazardScreenEffectPulseRate;
        /* 0x2BD8 */ public float KeepHazardBarActiveTime;
        /* 0x2BDC */ public float KeepSecondHazardBarActiveTime;
        /* 0x2BE0 */ public float HazardBarPulseTime;
        /* 0x2BE4 */ public float HazardScreenEffectPulseTime;
        /* 0x2BE8 */ public float HazardScreenEffectStrength;
        /* 0x2BEC */ public float ShieldSpringTime;
        /* 0x2BF0 */ public float ShieldPulseTime;
        /* 0x2BF4 */ public float ShieldHazardPulseRate;
        /* 0x2BF8 */ public float ShieldHazardPulseThreshold;
        /* 0x2BFC */ public float AlwaysOnHazardThreshold;
        /* 0x2C00 */ public float AlwaysOnHazardStrengthTox;
        /* 0x2C04 */ public float AlwaysOnHazardStrengthHeat;
        /* 0x2C08 */ public float AlwaysOnHazardStrengthRad;
        /* 0x2C0C */ public float AlwaysOnHazardStrengthCold;
        /* 0x2C10 */ public float AlwaysOnHazardMultiplierTox;
        /* 0x2C14 */ public float AlwaysOnHazardMultiplierHeat;
        /* 0x2C18 */ public float AlwaysOnHazardMultiplierRad;
        /* 0x2C1C */ public float AlwaysOnHazardMultiplierCold;
        /* 0x2C20 */ public float HazardPulseRate;
        [NMS(Size = 0x6, EnumValue = new string[6] { "None", "NoOxygen", "ExtremeHeat", "ExtremeCold", "ToxicGas", "Radiation" })]
        /* 0x2C24 */ public NMSString0x80[] HazardTextures;
        [NMS(Size = 0x6, EnumValue = new string[6] { "None", "NoOxygen", "ExtremeHeat", "ExtremeCold", "ToxicGas", "Radiation" })]


        /* 0x2F24 */ public NMSString0x80[] HazardNormalMaps;
        [NMS(Size = 0x6, EnumValue = new string[6] { "None", "NoOxygen", "ExtremeHeat", "ExtremeCold", "ToxicGas", "Radiation" })]




        /* 0x3224 */ public NMSString0x80[] HazardHeightmaps;
        /* 0x3524 */ public float IconPulseRate;
        /* 0x3530 */ public Colour EnergyBgColour;

        /* 0x3540 */ public Colour EnergyBgPulseColour;
        /* 0x3550 */ public Colour HazardBgPulseColour;
        /* 0x3560 */ public Colour HazardDamagePulseColour;
        /* 0x3570 */ public Colour ShieldColour;
        /* 0x3580 */ public Colour ShieldDamageColour;
        /* 0x3590 */ public Colour ShieldBgColour;
        /* 0x35A0 */ public Colour ShieldDamageBgColour;
        /* 0x35B0 */ public Vector2f ScanLabelOffset;
        /* 0x35B8 */ public Vector2f InteractionLabelOffset;
        /* 0x35C0 */ public Vector2f InteractionLabelSize;
        /* 0x35C8 */ public Vector2f InteractionLabelLineOffset;
        /* 0x35D0 */ public float InteractionLabelRadiusScaler;
        /* 0x35D4 */ public float InteractionLabelHeight;
        /* 0x35D8 */ public float InteractionLabelLineAlpha;
        /* 0x35DC */ public float InteractionIconInnerRadius;
        /* 0x35E0 */ public float InteractionIconOuterRadius;
        /* 0x35E4 */ public float InteractionLabelPixelHeightMin;
        /* 0x35E8 */ public float InteractionLabelPixelHeightMax;
        /* 0x35EC */ public float ScanTime;
        /* 0x35F0 */ public GcModelViewCollection ModelViews;
        /* 0x43B0 */ public Colour CursorColour;
        /* 0x43C0 */ public Colour CursorConfirmColour;
        /* 0x43D0 */ public Colour CursorDeleteColour;
        /* 0x43E0 */ public float CursorHoverSlowFactor;
        /* 0x43E4 */ public float FrontendBGAlpha;
        /* 0x43E8 */ public float FrontendConfirmTimeMouseMultiplier;
        /* 0x43EC */ public float FrontendConfirmTimeFast;
        /* 0x43F0 */ public float FrontendConfirmTime;
        /* 0x43F4 */ public TkCurveType FrontendConfirmCurve;
        /* 0x43F8 */ public float FrontendCursorSize;
        /* 0x43FC */ public float FrontendCursorOffset;
        /* 0x4400 */ public float PopupXClampOffset;
        /* 0x4404 */ public float PopupSlotWidthOffset;
        /* 0x4408 */ public float FrontendCursorWidth;
        /* 0x440C */ public float FrontendDeactivateTime;
        /* 0x4410 */ public float FrontendDeactivateSplit;
        /* 0x4414 */ public float FrontendActivateTime;
        /* 0x4418 */ public float FrontendActivateSplit;
        /* 0x441C */ public float FrontendStatCircleWidth;
        /* 0x4420 */ public float FrontendStatCircleWidthExtra;
        /* 0x4424 */ public float FrontendBootTime;
        /* 0x4428 */ public float FrontendBootBarTime;
        /* 0x442C */ public TkCurveType FrontendBootBarCurve;
        /* 0x4430 */ public float PopupDebounceTime;
        /* 0x4434 */ public float PopupActivateTime;
        /* 0x4438 */ public float PopupDeactivateTime;
        /* 0x443C */ public TkCurveType PopupActivateCurve1;
        /* 0x4440 */ public TkCurveType PopupActivateCurve2;
        /* 0x4444 */ public float HatchPulseSpeed;
        /* 0x4448 */ public float HatchPulseWidth;
        /* 0x444C */ public float HatchPulsePauseTime;
        /* 0x4450 */ public int HatchCount;
        /* 0x4454 */ public float HatchCursorRadius;
        /* 0x4458 */ public float HatchAlphaMain;
        /* 0x445C */ public float HatchAlphaBase;
        /* 0x4460 */ public float HatchAlphaCursor;
        /* 0x4464 */ public float FrontendDoFNearPlaneMin;
        /* 0x4468 */ public float FrontendDoFNearPlaneMax;
        /* 0x446C */ public float FrontendDoFFarPlaneMin;
        /* 0x4470 */ public float FrontendDoFFarPlaneMax;
        /* 0x4474 */ public float FrontendDoFFarPlaneFadeMin;
        /* 0x4478 */ public float FrontendDoFFarPlaneFadeMax;
        /* 0x447C */ public float FrontendDoFBlurMultiplier;
        /* 0x4480 */ public bool FrontendDoFEnableBokeh;
        /* 0x4484 */ public TkCurveType FrontendDoFCurve;
        /* 0x4488 */ public float FrontendShineSpeed;
        /* 0x448C */ public float FrontendToolbarTextHeight;
        /* 0x4490 */ public float FrontendToolbarTextHeightSelected;
        /* 0x4494 */ public float FrontendTitleFontSpacing;
        /* 0x4498 */ public float NGuiPadSensitivity;
        /* 0x449C */ public float NGuiMouseSensitivity;
        /* 0x44A0 */ public Vector2f NGuiTouchPadSensitivity;
        /* 0x44B0 */ public Colour TargetMarkerColour;

        /* 0x44C0 */ public Colour TargetMarkerHighlightColour;
        /* 0x44D0 */ public float TargetMarkerScaleStart;
        /* 0x44D4 */ public float TargetMarkerScaleEnd;
        /* 0x44D8 */ public float TargetMarkerFadeAngleMin;
        /* 0x44DC */ public float TargetMarkerFadeAngleRange;
        /* 0x44E0 */ public float HitMarkerPulseSize;
        /* 0x44E4 */ public float HitMarkerPulseTime;
        /* 0x44F0 */ public Colour WantedColour;

        /* 0x4500 */ public float PlanetPoleMaxDotProduct;
        /* 0x4504 */ public float SpaceMapFoV;
        /* 0x4508 */ public float SpaceMapAspectRatio;
        /* 0x450C */ public float SpaceMapDistanceScale;
        /* 0x4510 */ public float SpaceMapDistanceLogScaler;
        /* 0x4514 */ public float SpaceMapScaleMin;
        /* 0x4518 */ public float SpaceMapScaleRangeMin;
        /* 0x451C */ public float SpaceMapScaleRangeMax;
        /* 0x4520 */ public float SpaceMapObjectScale;
        /* 0x4524 */ public float SpaceMapFreighterScale;
        /* 0x4528 */ public float SpaceMapStationScale;
        /* 0x452C */ public float SpaceMapPlanetScale;
        /* 0x4530 */ public float SpaceMapMoonScale;
        /* 0x4534 */ public float SpaceMapShipScale;
        /* 0x4538 */ public float SpaceMapOtherPlayerScale;
        /* 0x453C */ public float SpaceMapActionScale;
        /* 0x4540 */ public float SpaceMapPlayerScale;
        /* 0x4544 */ public float SpaceMapMarkerScale;
        /* 0x4548 */ public float SpaceMapDistance;
        /* 0x454C */ public float SpaceMapDistanceMultiplier;
        /* 0x4550 */ public float SpaceMapHorizonThickness;
        /* 0x4554 */ public float SpaceMapFadeAngleMin;
        /* 0x4558 */ public float SpaceMapFadeAngleMax;
        /* 0x455C */ public float SpaceMapCamHeight;
        /* 0x4560 */ public float SpaceMapCamAngle;
        /* 0x4564 */ public float SpaceMapCamDistance;
        /* 0x4568 */ public float SpaceMapShipScaleMin;
        /* 0x456C */ public float SpaceMapLightPitch;
        /* 0x4570 */ public float SpaceMapLightYaw;


        [NMS(Size = 0xC, Ignore = true)]
        /* 0x4574 */ public byte[] Padding4574;
        /* 0x4580 */ public Vector4f SpaceMapPosScaler;
        /* 0x4590 */ public Colour SpaceMapAttackColour;
        /* 0x45A0 */ public Colour SpaceMapOtherPlayerColour;
        /* 0x45B0 */ public Colour SpaceMapThreatColour;
        /* 0x45C0 */ public Colour SpaceMapNeutralColour;
        /* 0x45D0 */ public Colour SpaceMapDeathPointColour;
        /* 0x45E0 */ public GcSpaceMapObjectData SpaceMapMarkerData;
        /* 0x4610 */ public GcSpaceMapObjectData SpaceMapPlanetData;
        /* 0x4640 */ public GcSpaceMapObjectData SpaceMapStationData;
        /* 0x4670 */ public GcSpaceMapObjectData SpaceMapShipData;
        /* 0x46A0 */ public GcSpaceMapObjectData SpaceMapFreighterData;
        /* 0x46D0 */ public Vector2f HUDTargetHealthOffset;
        /* 0x46D8 */ public Vector2f HUDTargetHealthSize;
        /* 0x46E0 */ public Vector2f HUDTargetHealthIconOffset;
        /* 0x46E8 */ public float HUDTargetHealthIconSize;
        /* 0x46EC */ public float HUDTargetHealthDangerTime;
        /* 0x46F0 */ public float HUDTargetMarkerOffset;
        /* 0x46F4 */ public float HUDTargetMarkerSize;
        /* 0x46F8 */ public float HUDTargetIconOffset;
        /* 0x46FC */ public float HUDTargetIconSize;
        /* 0x4700 */ public float HUDMarkerOffset;
        /* 0x4710 */ public Colour HUDMarkerColour;

        /* 0x4720 */ public Colour HUDSpaceshipColour;
        /* 0x4730 */ public Colour HUDRelicMarkerColourDiscovered;
        /* 0x4740 */ public Colour HUDRelicMarkerColourUnknown;
        /* 0x4750 */ public Colour HUDOutpostColour;
        /* 0x4760 */ public Vector2f HUDMarkerPrimaryIndicatorOffset;
        /* 0x4768 */ public Vector2f HUDMarkerCompassPrimaryIndicatorOffset;
        [NMS(Size = 0x100)]
        /* 0x4770 */ public string HUDMarkerIcon;
        [NMS(Size = 0x100)]
        /* 0x4870 */ public string HUDMarkerPrimaryIndicatorIcon;
        [NMS(Size = 0x100)]
        /* 0x4970 */ public string HUDMarkerColourIcon;
        [NMS(Size = 0x100)]
        /* 0x4A70 */ public string HUDPointIcon;
        [NMS(Size = 0x100)]
        /* 0x4B70 */ public string HUDSpaceshipIcon;
        [NMS(Size = 0x100)]
        /* 0x4C70 */ public string HUDSaveIcon;
        [NMS(Size = 0x100)]
        /* 0x4D70 */ public string HUDDeathPointIcon;
        [NMS(Size = 0x100)]
        /* 0x4E70 */ public string HUDHexAnimIcon;
        [NMS(Size = 0x100)]
        /* 0x4F70 */ public string HUDCircleAnimIcon;
        /* 0x5070 */ public float HUDMarkerAnimSpeed;
        /* 0x5074 */ public float HUDMarkerAnimScale;
        /* 0x5078 */ public float HUDMarkerAnimOffset;
        /* 0x507C */ public float HUDMarkerAnimLoopTime;
        /* 0x5080 */ public TkCurveType HUDMarkerAnimAlphaCurve;
        /* 0x5084 */ public float HUDMarkerAnimCurve;
        /* 0x5088 */ public float HUDMarkerPrimaryIndicatorSize;

        /* 0x508C */ public float HUDMarkerHoverAngleTest;
        /* 0x5090 */ public float HUDMarkerWideHoverAngleTest;
        /* 0x5094 */ public float HUDMarkerHoverAngleTestShip;
		/* 0x5098 */ public float HUDMarkerShipOffsetMaxDist;
		/* 0x509C */ public float HUDMarkerShipOffsetMinDist;
		/* 0x50A0 */ public float HUDMarkerNearFadeDistance;
		/* 0x50A4 */ public float HUDMarkerNearFadeRange;
		/* 0x50A8 */ public float HUDMarkerFarDistance;
		/* 0x50AC */ public float HUDMarkerFarFadeRange;
		/* 0x50B0 */ public float HUDMarkerScalerMin;
		/* 0x50B4 */ public float HUDMarkerScalerRange;
		/* 0x50B8 */ public float HUDMarkerScalerSizeMin;
		/* 0x50BC */ public float HUDMarkerScalerSizeMax;
		/* 0x50C0 */ public float HUDMarkerHorizonBlendRange;
		/* 0x50C4 */ public float HUDMarkerAlpha;
		/* 0x50C8 */ public float HUDMarkerModelFadeRange;
		/* 0x50CC */ public float HUDMarkerModelFadeMinHeight;
		/* 0x50D0 */ public float HUDMarkerShowActualIconDistance;
		/* 0x50D4 */ public float HUDMarkerShowActualSpaceIconDistance;
		/* 0x50D8 */ public float HUDMarkerActiveTime;
        /* 0x50DC */ public TkCurveType HUDMarkerActiveCurve;
        /* 0x50E0 */ public float AltimeterResolution;
        /* 0x50E4 */ public float AltimeterLineSpacing;
        /* 0x50E8 */ public float AltimeterWidth;
        /* 0x50EC */ public float AltimeterMin;
        /* 0x50F0 */ public float AltimeterMax;
        /* 0x50F4 */ public float AltimeterTextSize;
        /* 0x50F8 */ public float AltimeterMinValue;
        /* 0x5100 */ public Colour AltimeterBandColour1;

        /* 0x5110 */ public Colour AltimeterBandColour2;
        /* 0x5120 */ public Colour AltimeterColour1;
        /* 0x5130 */ public Colour AltimeterColour2;
        /* 0x5140 */ public float LockOnMarkerSize;
        /* 0x5144 */ public float LockOnMarkerSizeLock;
        /* 0x5150 */ public Colour LockOnMarkerActiveColour;

        /* 0x5160 */ public float MissileIconAttackPulseTime;
        /* 0x5164 */ public float MissileIconAttackPulseAmount;
        /* 0x5168 */ public float NGuiModelRotationDegreesX;
        /* 0x516C */ public float NGuiModelRotationDegreesY;
        /* 0x5170 */ public float NGuiModelRotationDegreesZ;
        /* 0x5174 */ public float NGuiModelViewDistanceGlobal;
        /* 0x5178 */ public float NGuiModelViewDistanceSuitPage;
        /* 0x517C */ public float NGuiModelViewDistanceWeaponPage;
        /* 0x5180 */ public float NGuiModelViewDistanceShipPage;
        /* 0x5184 */ public float NGuiModelViewDistanceDiscoveryPage;
        /* 0x5188 */ public float NGuiModelViewFov;
        /* 0x518C */ public float NGuiModelViewCdSmoothTime;
        /* 0x5190 */ public float NGuiAltPlacementDistanceScrollSpeed;
        /* 0x5194 */ public float NGuiPlacementAngleScrollSpeed;
        /* 0x5198 */ public float NGuiModelViewFractionOfBBHeightAboveReflectivePlane;


        [NMS(Size = 0x4, Ignore = true)]
        /* 0x519C */ public byte[] Padding519C;
        /* 0x51A0 */ public Vector4f NGuiModelTranslationFactors;
        /* 0x51B0 */ public Vector4f NGuiModelTranslationFactorsInteraction;
        /* 0x51C0 */ public Vector4f NGuiThumbnailModelTranslationFactors;
        /* 0x51D0 */ public float NGuiThumbnailModelRotationDegreesY;
        /* 0x51D4 */ public float NGuiThumbnailModelViewDistance;
        /* 0x51D8 */ public float NGuiCursorOffsetMultiplier;
        /* 0x51DC */ public float NGuiActiveAreaOffsetTime;
        /* 0x51E0 */ public Vector2f NGuiMin2DParallax;
        /* 0x51E8 */ public Vector2f NGuiMax2DParallax;
        /* 0x51F0 */ public Vector2f NGuiModelParallax;
        /* 0x51F8 */ public Vector2f NGuiShipInteractParallax;
        /* 0x5200 */ public Vector2f InteractionWorldParallax;
        /* 0x5208 */ public float TargetParallaxMouseMultiplier;
        /* 0x520C */ public float TargetParallaxMaintenancePageMultiplier;
        /* 0x5210 */ public float NGuiModelViewFadeInAfterRenderTime;
        /* 0x5214 */ public TkCurveType NGuiModelViewFadeInAfterRenderCurve;
        /* 0x5218 */ public bool NGuiUseSeparateLayersForModelAndReflection;


        [NMS(Size = 0x3, Ignore = true)]
        /* 0x5219 */ public byte[] Padding5219;
        /* 0x521C */ public GcDiscoveryHelperTimings DiscoveryHelperTimings;
        /* 0x5228 */ public GcHUDStartupTable IntroTiming;
        /* 0x52A8 */ public GcInventorySlotActionData InstallTechSlotAction;
        /* 0x52C4 */ public GcInventorySlotActionData BuildProductSlotAction;
        /* 0x52E0 */ public GcInventorySlotActionData ChargeSlotAction;
        /* 0x52FC */ public GcInventorySlotActionData RepairSlotAction;
        /* 0x5318 */ public GcInventorySlotActionData NewSlotRevealAction;
        /* 0x5334 */ public GcInventorySlotActionData NewSlotPulseAction;
        /* 0x5350 */ public float ReportBaseFlashTime;
        /* 0x5354 */ public float ReportBaseFlashIntensity;
        /* 0x5358 */ public float ReportBaseFlashDelay;
        /* 0x535C */ public int ReportBaseTexWidth;
        /* 0x5360 */ public int ReportBaseTexHeight;
        /* 0x5364 */ public float ReportCameraSpeed;
        /* 0x5368 */ public float AmbientModeFadeTime;
        /* 0x536C */ public bool HideQuickMenuControls;
        /* 0x536D */ public bool QuickMenuAllowCycle;
        /* 0x5370 */ public float TextChatMaxDisplayTime;
        /* 0x5374 */ public float TextChatStayBigAfterTextInput;
        /* 0x5378 */ public int BuildingShopMaxItems;
        [NMS(Size = 0x4, Ignore = true)]
        /* 0x537C */ public byte[] EndPadding;
    }
}