using libMBIN.NMS.Toolkit;
using libMBIN.NMS.GameComponents;

namespace libMBIN.NMS.Globals
{
    [NMS(Size = 0x7630, GUID = 0x0107CD7DE6B7F761)]
    public class GcVehicleGlobals : NMSTemplate
    {
        /* 0x000 */ public float VehicleSolarRegenFactor;
        [NMS(Size = 0x4, Ignore = true)]
        /* 0x004 */ public byte[] Padding4;
        [NMS(Size = 0x10)]
        /* 0x008 */ public string VehicleStrongLaser;
        [NMS(Size = 0x10)]
        /* 0x018 */ public string MechStrongLaser;
        /* 0x028 */ public bool UseFirstPersonCamera;
        [NMS(Size = 0x3, Ignore = true)]
        /* 0x029 */ public byte[] Padding29;
        /* 0x02C */ public float LevelVehicleCameraFactor;
        /* 0x030 */ public bool ShowAllCheckpoints;
        [NMS(Size = 0x3, Ignore = true)]
        /* 0x031 */ public byte[] Padding31;
        /* 0x034 */ public float ControlStickRecenterSpeedDegPerSec;
        /* 0x038 */ public float SteeringWheelPushRange;
        /* 0x03C */ public float SteeringWheelPitchAngle;
        /* 0x040 */ public float SteeringWheelSpringBothHands;
        /* 0x044 */ public float SteeringWheelSpringOneHand;
        /* 0x048 */ public float SteeringWheelCentreOffset;
        /* 0x04C */ public TkCurveType SteeringWheelOutputCurve;
        /* 0x050 */ public float RemoteBoostingEffectTimeout;
        /* 0x054 */ public float TestFrictionStat;
        /* 0x058 */ public float TestSkidFrictionStat;
        /* 0x05C */ public bool TestAnims;
        [NMS(Size = 0x3, Ignore = true)]
        /* 0x05D */ public byte[] Padding5D;
        /* 0x060 */ public float TestAnimThrust;
        /* 0x064 */ public float TestAnimBoost;
        /* 0x068 */ public float TestAnimTurn;
        /* 0x06C */ public float VisualTurnUnderwaterSpring;
        /* 0x070 */ public float VisualTurnSpring;
        [NMS(Size = 0xC, Ignore = true)]
        /* 0x074 */ public byte[] Padding74;
        /* 0x080 */ public Colour DefaultBoosterColour;
        /* 0x090 */ public float WheelDustColourLightFactor;
        /* 0x094 */ public Vector2f MechMovementStickSpeedLimit;
        /* 0x09C */ public Vector2f MechLookStickSpeedLimit;
        /* 0x0A4 */ public bool MechAltJumpMode;
        [NMS(Size = 0x3, Ignore = true)]
        /* 0x0A5 */ public byte[] PaddingA5;
        /* 0x0A8 */ public float MechContrailAlpha;
        /* 0x0AC */ public float MechJetpackJetScaleTime;
        [NMS(Size = 0x10)]
        /* 0x0B0 */ public string MechJetpackEffect;
        /* 0x0C0 */ public float MechTurnSpeed;
        /* 0x0C4 */ public float MechJetpackTurnSpeed;
        [NMS(Size = 0x8, Ignore = true)]
        /* 0x0C8 */ public byte[] PaddingC8;
        /* 0x0D0 */ public Vector3f MechTurretAngleLmits;
        /* 0x0E0 */ public float MechTurretTurnTimeGround;
        /* 0x0E4 */ public float MechTurretMaxAngleGround;
        /* 0x0E8 */ public float MechTurretTurnTimeAir;
        /* 0x0EC */ public float MechTurretMaxAngleAir;
        /* 0x0F0 */ public float MechTurretTimeVRModifier;
        [NMS(Size = 0xC, Ignore = true)]
        /* 0x0F4 */ public byte[] PaddingF4;
        /* 0x100 */ public Vector3f MechCrouchOffset;
        /* 0x110 */ public float MechCoGAdjustTimeWindUp;
        /* 0x114 */ public float MechCoGAdjustTimeAir;
        /* 0x118 */ public float MechCoGAdjustTimeLand;
        /* 0x11C */ public float MechCrouchTime;
        /* 0x120 */ public float MechWalkToRunTimeIdle;
        /* 0x124 */ public float MechWalkToRunTimeSkid;
        /* 0x128 */ public float MechArmSwingAngleWalk;
        /* 0x12C */ public float MechArmSwingPhaseWalk;
        /* 0x130 */ public TkCurveType MechArmSwingCurveWalk;
        /* 0x134 */ public float MechArmSwingAngleFastWalk;
        /* 0x138 */ public float MechArmSwingPhaseFastWalk;
        /* 0x13C */ public TkCurveType MechArmSwingCurveFastWalk;
        /* 0x140 */ public float MechLandBrake;
        /* 0x144 */ public float MechJetpackStrafeStrength;
        /* 0x148 */ public float MechJetpackLandTime;
        /* 0x14C */ public float MechJetpackForce;
        /* 0x150 */ public float MechJetpackBrake;
        /* 0x154 */ public float MechJetpackMaxSpeed;
        /* 0x158 */ public float MechJetpackMaxUpSpeed;
        /* 0x15C */ public float MechJetpackUpForce;
        /* 0x160 */ public float MechJetpackAvoidGroundForce;
        /* 0x164 */ public float MechJetpackFallForce;
        /* 0x168 */ public float MechJetpackAvoidGroundProbeLength;
        /* 0x16C */ public float MechJetpackIgnitionForce;
        /* 0x170 */ public float MechJetpackIgnitionTime;
        /* 0x174 */ public float MechJetpackMaxCoGAdjustX;
        /* 0x178 */ public float MechCameraOffsetTime;
        /* 0x17C */ public float MechCameraOffsetAmount;
        /* 0x180 */ public float MechJetpackDrainRate;
        /* 0x184 */ public float MechJetpackFillRate;
        /* 0x188 */ public float MechDefaultBlendTime;
        /* 0x18C */ public float MechSpeedBlendTime;
        /* 0x190 */ public float MechLandBlendTime;
        /* 0x194 */ public float MechJumpBlendTime;
        /* 0x198 */ public float MechJumpFlyBlendTime;
        /* 0x19C */ public float MechJumpDownBlendTime;
        /* 0x1A0 */ public float MechIdleLowBlendTime;
        /* 0x1A4 */ public float MechIdleLowDelay;
        /* 0x1A8 */ public float MechIdleStopDelay;
        /* 0x1AC */ public float MechFirstPersonMaxTurnTurret;
        /* 0x1B0 */ public float MechFirstPersonMaxLookTurret;
        /* 0x1B4 */ public float MechFirstPersonCrouchAmount;
        /* 0x1B8 */ public float MechPowerUpTime;
        /* 0x1BC */ public float MechCockPitBobX;
        /* 0x1C0 */ public float MechCockPitBobY;
        /* 0x1C4 */ public float MechCockPitBobPitch;
        /* 0x1C8 */ public float MechCockPitBobRoll;
        /* 0x1CC */ public float MechCockPitBobYaw;
        /* 0x1D0 */ public float MechCockPowerDownY;
        /* 0x1D4 */ public float MechTitanFallHeight;
        /* 0x1D8 */ public float MechTitanFallTerrainEditSize;
        /* 0x1DC */ public float MechTitanFallTerrainEditOffset;
        /* 0x1E0 */ public float MechTitanFallLandIdleTime;
        /* 0x1E4 */ public float MechTitanFallLandIntroTime;
        /* 0x1E8 */ public float MechTitanFallCameraShakeDist;
        /* 0x1EC */ public float MechLandCameraShakeDist;
        /* 0x1F0 */ public float MechFootprintFadeTime;
        /* 0x1F4 */ public float MechFootprintFadeDist;
        /* 0x1F8 */ public float MechWeaponInterpSpeed;
        /* 0x1FC */ public float WeaponInterpSpeed;
        /* 0x200 */ public float SubmarineMinSummonDepth;
        /* 0x204 */ public float SubmarineEjectRadius;
        /* 0x208 */ public float SubmarineEjectDownOffset;
        /* 0x20C */ public float SubmarineFirstPersonSteeringSensitivity;
        /* 0x210 */ public float FirstPersonSteeringAdditionalForward;
        /* 0x214 */ public float FirstPersonSteeringAdditionalForwardThreshold;
        /* 0x218 */ public float FirstPersonSteeringAdditionalReverseThreshold;
        /* 0x21C */ public float FirstPersonSteeringMinThrottleHardLeftRight;
        /* 0x220 */ public float FirstPersonSteeringLowSpeedTurnDamping;
        [NMS(Size = 0xC, Ignore = true)]
        /* 0x224 */ public byte[] Padding224;
        /* 0x230 */ public Vector3f FirstPersonNonVRCameraOffset;
        /* 0x240 */ public Vector3f FirstPersonNonVRCameraOffsetMech;
        /* 0x250 */ public float UnderwaterBuoyancySurfaceOffset;
        /* 0x254 */ public float UnderwaterBuoyancyRange;
        /* 0x258 */ public float UnderwaterSummonSurfaceOffset;
        /* 0x25C */ public float UnderwaterSurfaceTension;
        /* 0x260 */ public float UnderwaterSurfaceOffset;
        /* 0x264 */ public float UnderwaterSurfaceGravity;
        /* 0x268 */ public float UnderwaterFlattenMinDepth;
        /* 0x26C */ public float UnderwaterFlattenRange;
        /* 0x270 */ public float UnderwaterSurfaceForceFlatteningAngleMin;
        /* 0x274 */ public float UnderwaterSurfaceForceFlatteningAngleRange;
        /* 0x278 */ public float UnderwaterSurfaceSplashdownForce;
        /* 0x27C */ public float UnderwaterSurfaceSplashdownMinSpeed;
        /* 0x280 */ public float UnderwaterJumpForce;
        /* 0x284 */ public GcSpaceshipAvoidanceData UnderwaterAvoidance;
        [NMS(Size = 0x8, Ignore = true)]
        /* 0x2A8 */ public byte[] Padding2A8;
        [NMS(Size = 0x4)]
        /* 0x2B0 */ public Vector3f[] UnderwaterBubbleOffset;
        /* 0x2F0 */ public bool VehicleAltControlScheme;
        [NMS(Size = 0x3, Ignore = true)]
        /* 0x2F1 */ public byte[] Padding2F1;
        /* 0x2F4 */ public float VehicleAltControlStickSmoothInTime;
        /* 0x2F8 */ public float VehicleAltControlStickSmoothOutTime;
        /* 0x2FC */ public float VehicleBoostSpeedMultiplierPercent;
        /* 0x300 */ public float VehicleGarageHologramMinFadeRange;
        /* 0x304 */ public float VehicleGarageHologramFadeRange;
        /* 0x308 */ public float CheckpointPlacementOffset;
        /* 0x30C */ public float CheckpointPlacementRayLength;
        /* 0x310 */ public float CheckpointDeleteDistance;
        /* 0x314 */ public float CheckpointDeleteAngle;
        /* 0x318 */ public float BoostPadTime;
        /* 0x31C */ public float BoostPadStrength;
        /* 0x320 */ public float DisablePhysicsRange;
        /* 0x324 */ public float RaceMultipleStartOffset;
        /* 0x328 */ public float RaceMultipleStartCaptureRange;
        /* 0x32C */ public float MiningLaserDrainSpeed;
        /* 0x330 */ public float ProjectileDrainPerShot;
        /* 0x334 */ public float RaceStartSpawnUpOffset;
        /* 0x338 */ public float RaceInteractRespawnOffset;
        /* 0x33C */ public float RaceInteractRespawnUpOffset;
        /* 0x340 */ public float StickTurnReducer;
        /* 0x344 */ public float StickTurnReducerVR;
        /* 0x348 */ public float StickTurnReducerAlt;
        /* 0x34C */ public float TravelSpeedReportReducer;
        /* 0x350 */ public float HornScareRadius;
        /* 0x354 */ public float HornScareFleeRadius;
        /* 0x358 */ public float HornScareTime;
        /* 0x35C */ public float AttractAmount;
        /* 0x360 */ public float AttractMaxSpeed;
        /* 0x364 */ public float AttractAlign;
        /* 0x368 */ public float AttractDirectionBrakeThresholdSq;
        /* 0x36C */ public float ExitStopTime;
        /* 0x370 */ public float ExitStopForce;
        /* 0x374 */ public float GunFireRate;
        /* 0x378 */ public float SummoningRange;
        /* 0x37C */ public float CheckpointRadius;
        /* 0x380 */ public float RaceCooldown;
        /* 0x384 */ public bool RaceFinishAtStart;
        [NMS(Size = 0x3, Ignore = true)]
        /* 0x385 */ public byte[] Padding385;
        /* 0x388 */ public float RaceResetFlashDuration;
        /* 0x38C */ public float RaceResetFlashIntensity;
        /* 0x390 */ public float CheckpointFlashDuration;
        /* 0x394 */ public float CheckpointFlashIntensity;
        [NMS(Size = 0x8, Ignore = true)]
        /* 0x398 */ public byte[] Padding398;
        /* 0x3A0 */ public Colour CheckpointBeamColourActive;
        /* 0x3B0 */ public Colour CheckpointBeamColourNormal;
        [NMS(Size = 0x1)]
        /* 0x3C0 */ public NMSString0x10[] DefaultBuggyLoadout;
        [NMS(Size = 0x2)]
        /* 0x3D0 */ public NMSString0x10[] DefaultBikeLoadout;
        [NMS(Size = 0x2)]
        /* 0x3F0 */ public NMSString0x10[] DefaultTruckLoadout;
        /* 0x410 */ public float CheckpointBeamSizeNormal;
        /* 0x414 */ public float CheckpointBeamSizeActive;
        /* 0x418 */ public float CheckpointBeamOffset;
        /* 0x41C */ public float SpawnRotation;
        /* 0x420 */ public float MechSpawnRotation;
        /* 0x424 */ public float MiningLaserRadius;
        /* 0x428 */ public int MiningLaserMiningDamage;
        /* 0x42C */ public int MiningLaserDamage;
        /* 0x430 */ public float MiningLaserSpeed;
        /* 0x434 */ public int GunBaseDamage;
        /* 0x438 */ public int GunBaseMiningDamage;
        /* 0x43C */ public float ResourceCollectOffset;
        /* 0x440 */ public float VehicleWheelNoise;
        /* 0x444 */ public float VehicleWheelNoiseScale;
        /* 0x448 */ public float WheelSideVerticalFactor;
        /* 0x44C */ public float SuspensionDamping;
        /* 0x450 */ public float SuspensionDampingAngularFactor;
        /* 0x454 */ public bool ShowTempVehicleMesh;
        /* 0x455 */ public bool ShowVehicleDebugging;
        /* 0x456 */ public bool ShowVehicleWheelGuards;
        /* 0x457 */ public bool ShowVehicleText;
        /* 0x458 */ public float VehicleTextSize;
        /* 0x45C */ public bool ShowVehicleParticleDebug;
        /* 0x45D */ public bool VehicleDrawAudioDebug;
        [NMS(Size = 0x2, Ignore = true)]
        /* 0x45E */ public byte[] Padding45E;
        /* 0x460 */ public float VehicleSuspensionAudioSpacing;
        /* 0x464 */ public float VehicleSuspensionAudioDelay;
        /* 0x468 */ public float VehicleSuspensionAudioScale;
        /* 0x46C */ public float VehicleSuspensionAudioTrigger;
        /* 0x470 */ public float VehicleFadeTime;
        /* 0x474 */ public float VehicleMinSummonDistance;
        /* 0x478 */ public float VehicleMaxSummonDistance;
        /* 0x47C */ public float VehicleMaxSummonDistanceUnderwater;
        /* 0x480 */ public float VehicleDeactivateRange;
        /* 0x484 */ public float VehicleBoostFuelRate;
        /* 0x488 */ public float VehicleBoostFuelRateSurvival;
        /* 0x48C */ public float VehicleFuelRate;
        /* 0x490 */ public float VehicleFuelRateSurvival;
        /* 0x494 */ public float VehicleFuelRateTruckMultiplier;
        /* 0x498 */ public float VehicleJumpTimeMin;
        /* 0x49C */ public float VehicleJumpTimeMax;
        /* 0x4A0 */ public float VehicleJumpCooldown;
        /* 0x4A4 */ public float VehicleMotionDeadZone;
        /* 0x4A8 */ public float WheelForceHalflife;
        /* 0x4AC */ public bool ThrottleButtonCamRelative;
        [NMS(Size = 0x3, Ignore = true)]
        /* 0x4AD */ public byte[] Padding4AD;
        /* 0x4B0 */ public float StickReverseTurnThreshold;
        /* 0x4B4 */ public float StickReverseTurnStiffness;
        /* 0x4B8 */ public GcScanData VehicleScan;
        /* 0x4CC */ public GcScanData VehicleLocalScan;
        [NMS(Size = 0x7, EnumType = typeof(GcVehicleType.VehicleTypeEnum))]
        /* 0x4E0 */ public GcVehicleData[] VehicleDataTable;
    }
}
