// generated by hand
// 
// 

namespace MBINCompiler.Models.Structs
{
    public class GcSpaceshipGlobals : NMSTemplate
    {
        public float Unknown0;     // sz: 4, origin: 0x3DCCCCCD, parsed: 0.1
        public float Unknown4;     // sz: 4, origin: 0x42700000, parsed: 60
        public float Unknown8;     // sz: 4, origin: 0x40800000, parsed: 4     
        public float UnknownC;     // sz: 4, origin: 0x453B8000, parsed: 3000
        public float Unknown10;     // sz: 4, origin: 0x40000000, parsed: 2 
        public float Unknown14;     // sz: 4, origin: 0xC1700000, parsed: -15
        public float Unknown18;     // sz: 4, origin: 0x3F000000, parsed: 0.5
        public float Unknown1C;     // sz: 4, origin: 0xC0A00000, parsed: -5
        public float Unknown20;     // sz: 4, origin: 0x3ECCCCCD, parsed: 0.4
        public float Unknown24;     // sz: 4, origin: 0x40A00000, parsed: 5
        public float Unknown28;     // sz: 4, origin: 0x3DCCCCCD, parsed: 0.1
        public float Unknown2C;     // sz: 4, origin: 0x40900000, parsed: 4.5
        public float Unknown30;     // sz: 4, origin: 0x3FC00000, parsed: 1.5
        public float Unknown34;     // sz: 4, origin: 0x3E99999A, parsed: 0.3
        public float Unknown38;     // sz: 4, origin: 0x3DCCCCCD, parsed: 0.1
        public int Unknown3C;     // sz: 4, origin: 0x0000000D, parsed: 13
        public int Unknown40;     // sz: 4, origin: 0x00000010, parsed: 16
        public float Unknown44;     // sz: 4, origin: 0x00000000, parsed: 0
        public float Unknown48;     // sz: 4, origin: 0x00000000, parsed: 0
        public float Unknown4C;     // sz: 4, origin: 0x00000000, parsed: 0
        public float Unknown50;     // sz: 4, origin: 0x3E2D0E56, parsed: 0.17
        public float Unknown54;     // sz: 4, origin: 0x3F2B020C, parsed: 0.67
        public float Unknown58;     // sz: 4, origin: 0x3F800000, parsed: 1
        public float Unknown5C;     // sz: 4, origin: 0x3F800000, parsed: 1
        public float Unknown60;     // sz: 4, origin: 0x00000000, parsed: 0
        public float Unknown64;     // sz: 4, origin: 0x3E99999A, parsed: 0.3
        public float Unknown68;     // sz: 4, origin: 0xBE4CCCCD, parsed: -0.2
        public float Unknown6C;     // sz: 4, origin: 0x00000000, parsed: 0
        public float Unknown70;     // sz: 4, origin: 0xC0000000, parsed: -2
        public float Unknown74;     // sz: 4, origin: 0xBF800000, parsed: -1
        public float Unknown78;     // sz: 4, origin: 0x3F800000, parsed: 1
        public float Unknown7C;     // sz: 4, origin: 0x00000000, parsed: 0
        public float Unknown80;     // sz: 4, origin: 0x40000000, parsed: 2
        public float Unknown84;     // sz: 4, origin: 0xBF800000, parsed: -1 
        public float Unknown88;     // sz: 4, origin: 0x3F800000, parsed: 1
        public float Unknown8C;     // sz: 4, origin: 0x00000000, parsed: 0
        public float Unknown90;     // sz: 4, origin: 0x40A00000, parsed: 5
        public float Unknown94;     // sz: 4, origin: 0x3F4CCCCD, parsed: 0.8
        public float Unknown98;     // sz: 4, origin: 0x3DCCCCCD, parsed: 0.1
        public int Unknown9C;     // sz: 4, origin: 0x0000000D, parsed: 13
        public int UnknownA0;     // sz: 4, origin: 0x00000010, parsed: 16
		public float UnknownA4;     // sz: 4, origin: 0x00000000, parsed: 0
		public float UnknownA8;     // sz: 4, origin: 0x00000000, parsed: 0
		public float UnknownAC;     // sz: 4, origin: 0x00000000, parsed: 0
		public float UnknownB0;     // sz: 4, origin: 0x3F800000, parsed: 1
		public float UnknownB4;     // sz: 4, origin: 0x3F28F5C3, parsed: 0.66
		public float UnknownB8;     // sz: 4, origin: 0x00000000, parsed: 0
		public float UnknownBC;     // sz: 4, origin: 0x3F800000, parsed: 1
		public float UnknownC0;     // sz: 4, origin: 0x3F800000, parsed: 1
		public float UnknownC4;     // sz: 4, origin: 0x00000000, parsed: 0
		public float UnknownC8;     // sz: 4, origin: 0x00000000, parsed: 0
		public float UnknownCC;     // sz: 4, origin: 0x3F800000, parsed: 1
		public int UnknownD0;     // sz: 4, origin: 0x00000001, parsed: 1
		public float UnknownD4;     // sz: 4, origin: 0x40A00000, parsed: 5
		public float UnknownD8;     // sz: 4, origin: 0x41700000, parsed: 15
		public float UnknownDC;     // sz: 4, origin: 0x3F800000, parsed: 1
		public float UnknownE0;     // sz: 4, origin: 0x40000000, parsed: 2
		public float UnknownE4;     // offset: 0x8, sz: 4, origin: 0x40000000, parsed: 2
		public float MinAutoLiftAltitude;     // offset: 0xC, sz: 4, origin: 0x437A0000, parsed: 250
		public float UnknownEC;     // offset: 0x10, sz: 4, origin: 0x43FA0000, parsed: 500
		public float UnknownF0;     // offset: 0x14, sz: 4, origin: 0x41700000, parsed: 15
		public float UnknownF4;     // offset: 0x18, sz: 4, origin: 0x41700000, parsed: 15
		public float UnknownF8;     // offset: 0x1C, sz: 4, origin: 0x42480000, parsed: 50
		public float UnknownFC;     // offset: 0x20, sz: 4, origin: 0x43160000, parsed: 150
		public float Unknown100;     // offset: 0x24, sz: 4, origin: 0x3F800000, parsed: 1
		public float Unknown104;     // offset: 0x28, sz: 4, origin: 0x42C80000, parsed: 100
		public float Unknown108;     // offset: 0x2C, sz: 4, origin: 0xC1F00000, parsed: -30
		public float Unknown10C;     // offset: 0x30, sz: 4, origin: 0x40000000, parsed: 2
		public float Unknown110;     // offset: 0x34, sz: 4, origin: 0x3F4CCCCD, parsed: 0.8
		public float Unknown114;     // offset: 0x38, sz: 4, origin: 0x41200000, parsed: 10
		public float Unknown118;     // offset: 0x3C, sz: 4, origin: 0x41200000, parsed: 10
		public float Unknown11C;     // offset: 0x44, sz: 4, origin: 0x41200000, parsed: 10
		public float Unknown120;     // offset: 0x48, sz: 4, origin: 0x42700000, parsed: 60
		public float Unknown124;     // offset: 0x4C, sz: 4, origin: 0x3F99999A, parsed: 1.2
		public float Unknown128;     // offset: 0x50, sz: 4, origin: 0x3F000000, parsed: 0.5
		public float Unknown12C;     // offset: 0x54, sz: 4, origin: 0x41F00000, parsed: 30
		public float Unknown130;     // offset: 0x58, sz: 4, origin: 0xC0000000, parsed: -2
		public float Unknown134;     // offset: 0x5C, sz: 4, origin: 0x41200000, parsed: 10
		public float Unknown138;     // offset: 0x60, sz: 4, origin: 0xC0000000, parsed: -2
		public float Unknown13C;     // offset: 0x64, sz: 4, origin: 0x40000000, parsed: 2
		public int   Unknown140;     // offset: 0x68, sz: 4, origin: 4, parsed: 4
		public float Unknown144;     // offset: 0x6C, sz: 4, origin: 0x453B8000, parsed: 3000
		public float Unknown148;     // offset: 0x70, sz: 4, origin: 0x447A0000, parsed: 1000
		public float Unknown14C;     // offset: 0x74, sz: 4, origin: 0x44480000, parsed: 800
		public float Unknown150;     // offset: 0x78, sz: 4, origin: 0x42C80000, parsed: 100
		public float Unknown154;     // offset: 0x7C, sz: 4, origin: 0x43480000, parsed: 200
		public float Unknown158;     // offset: 0x80, sz: 4, origin: 0x459C4000i64, parsed: 5000
		public float Unknown15C;     // offset: 0x84, sz: 4, origin: 0x459C4000i64, parsed: 0
		public float Unknown160;     // offset: 0x88, sz: 4, origin: 0x3F666666, parsed: 0.9
		public float Unknown164;     // offset: 0x8C, sz: 4, origin: 0x00000000, parsed: 0
		public float Unknown168;     // offset: 0x90, sz: 4, origin: 0x00000000, parsed: 0
		public float Unknown16C;     // offset: 0x94, sz: 4, origin: 0x41F00000, parsed: 30
		public float Unknown170;     // offset: 0x98, sz: 4, origin: 0x3F99999A, parsed: 1.2
		public float Unknown174;     // offset: 0x9C, sz: 4, origin: 0x3FA66666, parsed: 1.3
		public float Unknown178;     // offset: 0xA0, sz: 4, origin: 0x3F800000, parsed: 1

// old block offset 0xA4 with new added float
		public GcPlayerSpaceshipControlData Unknown17C; // Models\Structs\GcPlayerSpaceshipControlData.cs 
		//  public GcPlayerSpaceshipEngineData SpaceEngine;
		//      public float ThrustForce;			// offset: 0x17C, sz: 4, origin: 0x42200000, parsed: 40
        //      public float MaxSpeed;				// offset: 0x180, sz: 4, origin: 0x43160000, parsed: 150
        //      public float MinSpeed;				// offset: 0x184, sz: 4, origin: 0x42480000, parsed: 50
        //      public float Falloff;				// offset: 0x188, sz: 4, origin: 0x3F333333, parsed: 0.7
        //      public float BoostThrustForce;		// offset: 0x18C, sz: 4, origin: 0x43FA0000, parsed: 500
        //      public float BoostMaxSpeed;			// offset: 0x190, sz: 4, origin: 0x44BB8000, parsed: 1500
        //      public float BoostFalloff;			// offset: 0x194, sz: 4, origin: 0x3F333333, parsed: 0.7
        //      public float BoostingTurnDamp;		// offset: 0x198, sz: 4, origin: 0x3DCCCCCD, parsed: 0.1
        //      public float DirectionBrakeMin;		// offset: 0x19C, sz: 4, origin: 0x3F800000, parsed: 1
        //      public float DirectionBrake;		// offset: 0x1A0, sz: 4, origin: 0x40000000, parsed: 2
        //      public float ReverseBrake;			// offset: 0x1A4, sz: 4, origin: 0x3F800000, parsed: 1
        //      public float OverspeedBrake;		// offset: 0x1A8, sz: 4, origin: 0x40400000, parsed: 3
        //      public float LowSpeedTurnDamper;	// offset: 0x1AC, sz: 4, origin: 0x3F800000, parsed: 1
        //      public float TurnBrakeMin;			// offset: 0x1B0, sz: 4, origin: 0x3F800000, parsed: 1
        //      public float TurnBrakeMax;			// offset: 0x1B4, sz: 4, origin: 0x40800000, parsed: 4
        //      public float TurnStrength;			// offset: 0x1B8, sz: 4, origin: 0x3F800000, parsed: 1
        //      public float RollAmount;			// offset: 0x1BC, sz: 4, origin: 0x40000000, parsed: 2
        //      public float RollForce;				// offset: 0x1C0, sz: 4, origin: 0x3FA00000, parsed: 1.25
        //      public float RollAutoTime;			// offset: 0x1C4, sz: 4, origin: 0x40000000, parsed: 2
        //      public float BalanceTimeMin;		// offset: 0x1C8, sz: 4, origin: 0x3ECCCCCD, parsed: 0.4
        //      public float BalanceTimeMax;		// offset: 0x1CC, sz: 4, origin: 0x40800000, parsed: 4
		//  public GcPlayerSpaceshipEngineData PlanetEngine;
		//      public float ThrustForce;			// offset: 0x1D0, sz: 4, origin: 0x41200000, parsed: 10
        //      public float MaxSpeed;				// offset: 0x1D4, sz: 4, origin: 0x42FA0000, parsed: 125
        //      public float MinSpeed;				// offset: 0x1D8, sz: 4, origin: 0x420C0000, parsed: 35
        //      public float Falloff;				// offset: 0x1DC, sz: 4, origin: 0x3F000000, parsed: 0.5
        //      public float BoostThrustForce;		// offset: 0x1E0, sz: 4, origin: 0x42480000, parsed: 50
        //      public float BoostMaxSpeed;			// offset: 0x1E4, sz: 4, origin: 0x43160000, parsed: 150
        //      public float BoostFalloff;			// offset: 0x1E8, sz: 4, origin: 0x3F333333, parsed: 0.7
        //      public float BoostingTurnDamp;		// offset: 0x1EC, sz: 4, origin: 0x3DCCCCCD, parsed: 0.1
        //      public float DirectionBrakeMin;		// offset: 0x1F0, sz: 4, origin: 0x40200000, parsed: 2.5
        //      public float DirectionBrake;		// offset: 0x1F4, sz: 4, origin: 0x40400000, parsed: 3
        //      public float ReverseBrake;			// offset: 0x1F8, sz: 4, origin: 0x40200000, parsed: 2.5
        //      public float OverspeedBrake;		// offset: 0x1FC, sz: 4, origin: 0x40400000, parsed: 3
        //      public float LowSpeedTurnDamper;	// offset: 0x200, sz: 4, origin: 0x3F800000, parsed: 1
        //      public float TurnBrakeMin;			// offset: 0x204, sz: 4, origin: 0x3F4CCCCD, parsed: 0.8
        //      public float TurnBrakeMax;			// offset: 0x208, sz: 4, origin: 0x40C00000, parsed: 6
        //      public float TurnStrength;			// offset: 0x20C, sz: 4, origin: 0x40A00000, parsed: 5
        //      public float RollAmount;			// offset: 0x210, sz: 4, origin: 0x40000000, parsed: 2
        //      public float RollForce;				// offset: 0x214, sz: 4, origin: 0x3FA00000, parsed: 1.25
        //      public float RollAutoTime;			// offset: 0x218, sz: 4, origin: 0x40000000, parsed: 2
        //      public float BalanceTimeMin;		// offset: 0x21C, sz: 4, origin: 0x3ECCCCCD, parsed: 0.4
        //      public float BalanceTimeMax;		// offset: 0x220, sz: 4, origin: 0x40800000, parsed: 4

		//      public float ExitHeightFactorMin;			// offset: 0x224, sz: 4, origin: 0x43480000, parsed: 200
        //      public float ExitHeightFactorMax;			// offset: 0x228, sz: 4, origin: 0x44960000, parsed: 1200
        //      public float ExitHeightFactorPlungeMin;		// offset: 0x22C, sz: 4, origin: 0x43FA0000, parsed: 500
        //      public float ExitHeightFactorPlungeMax;		// offset: 0x230, sz: 4, origin: 0x459C4000, parsed: 5000
        //      public float ExitAngleMin;					// offset: 0x234, sz: 4, origin: 0xC1F00000, parsed: -30
        //      public float ExitAngleMax;					// offset: 0x238, sz: 4, origin: 0x41100000, parsed: 9
	// new float
		//      public float SmthNew01;						// offset: 0x23C, sz: 4, origin: 0x42700000, parsed: 60
	// end of new float		
        //      public TkCurveType ExitCurve;				// offset: 0x240, sz: 4, origin: 0x00000019, parsed: 27 //int
        //      public TkCurveType ExitDownCurve;			// offset: 0x244, sz: 4, origin: 0x00000004, parsed: 4  //int

        //      public float AngularFactor;					// offset: 0x248, sz: 4, origin: 0x3DCCCCCD, parsed: 0.1
        //      public float MaxTorque;						// offset: 0x24C, sz: 4, origin: 0x461C4000, parsed: 10000
        //      public float ShipPlanetBrakeMinSpeed;		// offset: 0x250, sz: 4, origin: 0x41200000, parsed: 10
        //      public float ShipPlanetBrakeMaxSpeed;		// offset: 0x254, sz: 4, origin: 0x42B40000, parsed: 90.125
        //      public float ShipPlanetBrakeMinHeight;		// offset: 0x258, sz: 4, origin: 0x43480000, parsed: 200
        //      public float ShipPlanetBrakeMaxHeight;		// offset: 0x25C, sz: 4, origin: 0x459C4000, parsed: 5000
        //      public float ShipPlanetBrakeForce;			// offset: 0x260, sz: 4, origin: 0x42480000, parsed: 50
        //      public float ShipPlanetBrakeAlignMinTime;	// offset: 0x264, sz: 4, origin: 0x3E99999A, parsed: 0.3
        //      public float ShipPlanetBrakeAlignMaxTime;	// offset: 0x268, sz: 4, origin: 0x41000000, parsed: 8

        //      public float ShipMinHeightForce;			// offset: 0x26C, sz: 4, origin: 0x3F800000, parsed: 1
// end of old block offset 0xA4 with new added float

		public float Unknown270;     // offset: 0x194, sz: 4, origin: 0x41700000, parsed: 15 
        public float Unknown274;     // offset: 0x198, sz: 4, origin: 0x43C80000, parsed: 400
        public float Unknown278;     // offset: 0x19C, sz: 4, origin: 0x41000000, parsed: 8
        public float Unknown27C;     // offset: 0x1A0, sz: 4, origin: 0x3F8CCCCD, parsed: 1.1
        public float Unknown280;     // offset: 0x1A4, sz: 4, origin: 0x3F666666, parsed: 0.9
        public float Unknown284;     // offset: 0x1A8, sz: 4, origin: 0x40400000, parsed: 3
        public int Unknown288;     // offset: 0x1AC, sz: 4, origin: 0x00000005, parsed: 5
		public float Unknown28C;     //  offset: 0x1B0, sz: 4, origin: 0x3F4CCCCD, parsed: 0.8
		public float Unknown290;     //  offset: 0x1B4, sz: 4, origin: 0x41000000, parsed: 8
		public float Unknown294;     //  offset: 0x1B8, sz: 4, origin: 0x00000000, parsed: 0
		public float Unknown298;     //  offset: 0x1BC, sz: 4, origin: 0x41200000, parsed: 10
		public float Unknown29C;     //  offset: 0x1C0, sz: 4, origin: 0x00000000, parsed: 0
		public float Unknown2A0;     //  offset: 0x1C4, sz: 4, origin: 0x3F800000, parsed: 1
		public float Unknown2A4;     //  offset: 0x1C8, sz: 4, origin: 0x3F19999A, parsed: 0.6
		public float Unknown2A8;     //  offset: 0x1CC, sz: 4, origin: 0x40200000, parsed: 2.5
		public float Unknown2AC;     //  offset: 0x1D0, sz: 4, origin: 0x00000000, parsed: 0
		public float Unknown2B0;     //  offset: 0x1D4, sz: 4, origin: 0x41200000, parsed: 10
		public float Unknown2B4;     //  offset: 0x1D8, sz: 4, origin: 0x00000000, parsed: 0
		public float Unknown2B8;     //  offset: 0x1DC, sz: 4, origin: 0x3F800000, parsed: 1
		public float Unknown2BC;     //  offset: 0x1E0, sz: 4, origin: 0x3F800000, parsed: 1
		public float Unknown2C0;     //  offset: 0x1E4, sz: 4, origin: 0x40A00000, parsed: 5
		public float Unknown2C4;     //  offset: 0x1E8, sz: 4, origin: 0x00000000, parsed: 0
		public float Unknown2C8;     //  offset: 0x1EC, sz: 4, origin: 0x41200000, parsed: 10
		public float Unknown2CC;     //  offset: 0x1F0, sz: 4, origin: 0x00000000, parsed: 0
		public float Unknown2D0;     //  offset: 0x1F4, sz: 4, origin: 0x3F800000, parsed: 1
		public float Unknown2D4;     //  offset: 0x1F8, sz: 4, origin: 0x00000000, parsed: 0
		public float Unknown2D8;     //  offset: 0x1FC, sz: 4, origin: 0x40A00000, parsed: 5
		public float Unknown2DC;     //  offset: 0x200, sz: 4, origin: 0x3DCCCCCD, parsed: 0.1
		public float Unknown2E0;     //  offset: 0x204, sz: 4, origin: 0x41200000, parsed: 10
		public float Unknown2E4;     //  offset: 0x208, sz: 4, origin: 0x41F00000, parsed: 30
		public float Unknown2E8;     //  offset: 0x20C, sz: 4, origin: 0x42480000, parsed: 50
		public float Unknown2EC;     //  offset: 0x210, sz: 4, origin: 0x43FA0000, parsed: 500
		public float Unknown2F0;     //  offset: 0x214, sz: 4, origin: 0x40400000, parsed: 3
		public float Unknown2F4;     //  offset: 0x218, sz: 4, origin: 0x41000000, parsed: 8
		public float Unknown2F8;     //  offset: 0x21C, sz: 4, origin: 0x40A00000, parsed: 5
		public float Unknown2FC;     //  offset: 0x220, sz: 4, origin: 0x41F00000, parsed: 30
		public float Unknown300;     //  offset: 0x224, sz: 4, origin: 0x42A00000, parsed: 80
		public float Unknown304;     //  offset: 0x228, sz: 4, origin: 0x44480000, parsed: 800
		public float Unknown308;     //  offset: 0x22C, sz: 4, origin: 0x00000000, parsed: 0
		public float Unknown30C;     //  offset: 0x230, sz: 4, origin: 0x40A00000, parsed: 5
		public float Unknown310;     //  offset: 0x234, sz: 4, origin: 0x00000000, parsed: 0
		public float Unknown314;     //  offset: 0x238, sz: 4, origin: 0x41200000, parsed: 10
		public float Unknown318;     //  offset: 0x23C, sz: 4, origin: 0x42C80000, parsed: 100
		public float Unknown31C;     //  offset: 0x240, sz: 4, origin: 0x447A0000, parsed: 1000
		public int Unknown320;     //  offset: 0x244, sz: 4, origin: 0x00000032, parsed: 32
		public float Unknown324;     //  offset: 0x248, sz: 4, origin: 0x00000000, parsed: 0
		public float Unknown328;     //  offset: 0x24C, sz: 4, origin: 0x00000000, parsed: 0
		public float Unknown32C;     //  offset: 0x250, sz: 4, origin: 0x3F800000, parsed: 1
		public float Unknown330;     //  offset: 0x254, sz: 4, origin: 0x40A00000, parsed: 5
		public float Unknown334;     //  offset: 0x258, sz: 4, origin: 0x00000000, parsed: 0
		public float Unknown338;     //  offset: 0x25C, sz: 4, origin: 0x41200000, parsed: 10
		public float Unknown33C;     //  offset: 0x260, sz: 4, origin: 0x00000000, parsed: 0
		public float Unknown340;     //  offset: 0x264, sz: 4, origin: 0x3F800000, parsed: 1
		public float Unknown344;     //  offset: 0x268, sz: 4, origin: 0x40000000, parsed: 2
		public float Unknown348;     //  offset: 0x26C, sz: 4, origin: 0x40400000, parsed: 3
		public float Unknown34C;     //  offset: 0x270, sz: 4, origin: 0x40400000, parsed: 3
		public float Unknown350;     //  offset: 0x274, sz: 4, origin: 0x42480000, parsed: 50
		public float Unknown354;     //  offset: 0x278, sz: 4, origin: 0x43960000, parsed: 300
		public float Unknown358;     //  offset: 0x27C, sz: 4, origin: 0x3F000000, parsed: 0.5
		public float Unknown35C;     //  offset: 0x280, sz: 4, origin: 0x40000000, parsed: 2
        public float Unknown360;     // offset: 0x284, sz: 4, origin: 0x43FA0000, parsed: 500
        public float Unknown364;     // offset: 0x288, sz: 4, origin: 0x442F0000, parsed: 700
        public float Unknown368;     // offset: 0x28C, sz: 4, origin: 0x3F000000, parsed: 0.5
        public float Unknown36C;     // offset: 0x290, sz: 4, origin: 0x40000000, parsed: 2
        public float Unknown370;     // offset: 0x294, sz: 4, origin: 0x40000000, parsed: 2
        public float Unknown374;     // offset: 0x298, sz: 4, origin: 0x469C4000, parsed: 20000
        public float Unknown378;     // offset: 0x29C, sz: 4, origin: 0x3DCCCCCD, parsed: 0.1
        public float Unknown37C;     // offset: 0x2A0, sz: 4, origin: 0x41200000, parsed: 10
        public float Unknown380;     // offset: 0x2A4, sz: 4, origin: 0x40000000, parsed: 2
        public float Unknown384;     // offset: 0x2A8, sz: 4, origin: 0x459C4000, parsed: 5000
        public float Unknown388;     // offset: 0x2AC, sz: 4, origin: 0x44FA0000, parsed: 2000
        public float Unknown38C;     // offset: 0x2B0, sz: 4, origin: 0x451C4000, parsed: 2500
        public float Unknown390;     // offset: 0x2B4, sz: 4, origin: 0x42C80000, parsed: 100
        public float Unknown394;     // offset: 0x2B8, sz: 4, origin: 0x447A0000, parsed: 1000
        public float Unknown398;     // offset: 0x2BC, sz: 4, origin: 0x43FA0000, parsed: 500
        public float Unknown39C;     // offset: 0x2C0, sz: 4, origin: 0x3F000000, parsed: 0.5
		public float Unknown3A0;     // offset: 0x2C4, sz: 4, origin: 0x40A00000, parsed: 5
        public int Unknown3A4;     // offset: 0x2C8, sz: 4, origin: 0x00000001, parsed: 1
        public float Unknown3A8;     // offset: 0x2CC, sz: 4, origin: 0x3F666666, parsed: 0.9
        public float Unknown3AC;     // offset: 0x2D0, sz: 4, origin: 0x3F666666, parsed: 0.9
        public float Unknown3B0;     // offset: 0x2D4, sz: 4, origin: 0x00000000, parsed: 0

// new data
		public float Unknown3B4;  // sz: 4, origin: 0x44BB8000, parsed: 15000
		public float Unknown3B8;  // sz: 4, origin: 0x447A0000, parsed: 1000
// end of new data

        public float Unknown3BC;     // offset: 0x2DC, sz: 4, origin: 0x40A00000, parsed: 5
        public float Unknown3C0;     // offset: 0x2E0, sz: 4, origin: 0x3FC00000, parsed: 1.5
        public float Unknown3C4;     // offset: 0x2E4, sz: 4, origin: 0x3E4CCCCD, parsed: 0.2
        public float Unknown3C8;     // offset: 0x2E8, sz: 4, origin: 0x41200000, parsed: 10
        public float Unknown3CC;     // offset: 0x2EC, sz: 4, origin: 0x3F800000, parsed: 1
        public float Unknown3D0;     // offset: 0x2F0, sz: 4, origin: 0x40A00000, parsed: 5
        public float Unknown3D4;     // offset: 0x2F4, sz: 4, origin: 0x3E19999A, parsed: 0.15
        public float Unknown3D8;     // offset: 0x2F8, sz: 4, origin: 0x40800000, parsed: 4
        public int Unknown3DC;     // offset: 0x2FC, sz: 4, origin: 0x1F4, parsed: 500
        public float Unknown3E0;     // offset: 0x300, sz: 4, origin: 0x00000000, parsed: 0		
        public float Unknown3E4;     // offset: 0x304, sz: 4, origin: 0x41A00000, parsed: 20
        public float Unknown3E8;     // offset: 0x308, sz: 4, origin: 0x41200000, parsed: 10
        public float Unknown3EC;     // offset: 0x30C, sz: 4, origin: 0x42200000, parsed: 40
        public float Unknown3F0;     // offset: 0x310, sz: 4, origin: 0x3ECCCCCD, parsed: 0.4
        public float Unknown3F4;     // offset: 0x314, sz: 4, origin: 0x3FC00000, parsed: 1.5
        public float Unknown3F8;     // offset: 0x318, sz: 4, origin: 0x44FA0000, parsed: 2000
        public float Unknown3FC;     // offset: 0x31C, sz: 4, origin: 0x453B8000, parsed: 3000
        public float Unknown400;     // offset: 0x320, sz: 4, origin: 0x442F0000, parsed: 700
        public float Unknown404;     // offset: 0x324, sz: 4, origin: 0x44480000, parsed: 800
        public float Unknown408;     // offset: 0x328, sz: 4, origin: 0x41200000, parsed: 10
        public float Unknown40C;     // offset: 0x32C, sz: 4, origin: 0x44FA0000, parsed: 2000
        public float Unknown410;     // offset: 0x330, sz: 4, origin: 0x40A00000, parsed: 5        // old value origin: 0x41700000, parsed: 15
        public float Unknown414;     // offset: 0x334, sz: 4, origin: 0x41200000, parsed: 10
        public float Unknown418;     // offset: 0x338, sz: 4, origin: 0x42100000, parsed: 36
        public float Unknown41C;     // offset: 0x33C, sz: 4, origin: 0x3F333333, parsed: 0.7
        public float Unknown420;     // offset: 0x340, sz: 4, origin: 0x437A0000, parsed: 250
        public float Unknown424;     // offset: 0x344, sz: 4, origin: 0x40000000, parsed: 2
        public float Unknown428;     // offset: 0x348, sz: 4, origin: 0x41700000, parsed: 15
        public float Unknown42C;     // offset: 0x34C, sz: 4, origin: 0x40200000, parsed: 2.5
        public float Unknown430;     // offset: 0x350, sz: 4, origin: 0x3F000000, parsed: 0.5
        public float Unknown434;     // offset: 0x354, sz: 4, origin: 0x3F800000, parsed: 1
        public float Unknown438;     // offset: 0x358, sz: 4, origin: 0x3FC00000, parsed: 1.5        // old value origin: 0x3F000000, parsed: 0.5
        public float Unknown43C;     // offset: 0x35C, sz: 4, origin: 0x3F333333, parsed: 0.7
        public float Unknown440;     // offset: 0x360, sz: 4, origin: 0x3E4CCCCD, parsed: 0.2
        public float Unknown444;     // offset: 0x364, sz: 4, origin: 0x40200000, parsed: 2.5
        public float Unknown448;     // offset: 0x368, sz: 4, origin: 0x40200000, parsed: 2.5
        public float Unknown44C;     // offset: 0x36C, sz: 4, origin: 0x3F000000, parsed: 0.5
        public float Unknown450;     // offset: 0x370, sz: 4, origin: 0x3F000000, parsed: 0.5
        public float Unknown454;     // offset: 0x374, sz: 4, origin: 0xC1200000, parsed: -10
        public float LowAltitudeMaxDownwardPitch;     // offset: 0x378, sz: 4, origin: 0x41200000, parsed: 10
        public float Unknown45C;     // offset: 0x37C, sz: 4, origin: 0x3E4CCCCD, parsed: 0.2
        public float Unknown460;     // offset: 0x380, sz: 4, origin: 0x3F800000, parsed: 1
        public float Unknown464;     // offset: 0x384, sz: 4, origin: 0x41000000, parsed: 8
        public float Unknown468;     // offset: 0x388, sz: 4, origin: 0x41200000, parsed: 10
        public float Unknown46C;     // offset: 0x38C, sz: 4, origin: 0x442F0000, parsed: 700
        public int Unknown470;     // offset: 0x390, sz: 4, origin: 0x00000004, parsed: 4
        public float Unknown474;     // offset: 0x394, sz: 4, origin: 0x3F800000, parsed: 1
        public float Unknown478;     // offset: 0x398, sz: 4, origin: 0x3E19999A, parsed: 0.15
        public float Unknown47C;     // offset: 0x39C, sz: 4, origin: 0x3F666666, parsed: 0.9
        public float Unknown480;     // offset: 0x3A0, sz: 4, origin: 0x3FC00000, parsed: 1.5
        public float Unknown484;     // offset: 0x3A4, sz: 4, origin: 0x3F19999A, parsed: 0.6

// new data
        public float Unknown488;     // sz: 4, origin: 0x43480000, parsed: 200
// end of new data
        
		public float Unknown48C;     // offset: 0x3A8, sz: 4, origin: 0x41880000, parsed: 17

// new data
        public float Unknown490;     // sz: 4, origin: 0x40A00000, parsed: 5
		public float Unknown494;     // sz: 4, origin: 0x41A00000, parsed: 20
		public float Unknown498;     // sz: 4, origin: 0x42480000, parsed: 50
		public float Unknown49C;     // sz: 4, origin: 0x3F000000, parsed: 0.5
		public int Unknown4A0;     // sz: 4, origin: 0x00000001, parsed: 1
// end of new data

        public float Unknown4A4;     // offset: 0x3AC, sz: 4, origin: 0x43160000, parsed: 150
        public float Unknown4A8;     // offset: 0x3B0, sz: 4, origin: 0x3FC00000, parsed: 1.5
        public float Unknown4AC;     // offset: 0x3B4, sz: 4, origin: 0x3F19999A, parsed: 0.6
        public int Unknown4B0;     // offset: 0x3B8, sz: 4, origin: 0x0000000D, parsed: 13
        public float Unknown4B4;     // offset: 0x3BC, sz: 4, origin: 0x3F99999A, parsed: 1.2
        public float Unknown4B8;     // offset: 0x3C0, sz: 4, origin: 0x42A00000, parsed: 80
        public float Unknown4BC;     // offset: 0x3C4, sz: 4, origin: 0x420C0000, parsed: 35
        public float Unknown4C0;     // offset: 0x3C8, sz: 4, origin: 0x3EE66666, parsed: 0.45
        public float Unknown4C4;     // offset: 0x3CC, sz: 4, origin: 0x3E99999A, parsed: 0.3
        public float Unknown4C8;     // offset: 0x3D0, sz: 4, origin: 0x3F19999A, parsed: 0.6
        public float Unknown4CC;     // offset: 0x3D4, sz: 4, origin: 0x43960000, parsed: 300
        public float Unknown4D0;     // offset: 0x3D8, sz: 4, origin: 0xC0A00000, parsed: -5
        public float Unknown4D4;     // offset: 0x3DC, sz: 4, origin: 0x41200000, parsed: 10
        public int Unknown4D8;     // offset: 0x3E0, sz: 4, origin: 0x00000007, parsed: 7
        public float MinAltitudeOffset;     // offset: 0x3E4, sz: 4, origin: 0x3ECCCCCD, parsed: 0.4
        public float Unknown4E0;     // offset: 0x3E8, sz: 4, origin: 0x3C23D70A, parsed: 0.01
        public float Unknown4E4;     // offset: 0x3EC, sz: 4, origin: 0x00000000, parsed: 0
        public float Unknown4E8;     // offset: 0x3F0, sz: 4, origin: 0x42A00000, parsed: 80        // old value origin: 0x42C80000, parsed: 100

// new data
        public float Unknown4EC;     // sz: 4, origin: 0x3F000000, parsed: 0.5
		public float Unknown4F0;     // sz: 4, origin: 0x447A0000, parsed: 1000
// end of new data

        public float Unknown4F4;     // offset: 0x3F4, sz: 4, origin: 0x42F00000, parsed: 120
        public float Unknown4F8;     // offset: 0x3F8, sz: 4, origin: 0x3E4CCCCD, parsed: 0.2
        public float Unknown4FC;     // offset: 0x3FC, sz: 4, origin: 0x3F000000, parsed: 0.5
        public float Unknown500;     // offset: 0x400, sz: 4, origin: 0x41A00000, parsed: 20
        public float Unknown504;     // offset: 0x404, sz: 4, origin: 0x00000000, parsed: 0
        public float Unknown508;     // offset: 0x408, sz: 4, origin: 0x00000000, parsed: 0
        public float Unknown50C;     // offset: 0x40C, sz: 4, origin: 0x00000000, parsed: 0
        public float Unknown510;     // offset: 0x410, sz: 4, origin: 0xC0000000, parsed: -2
        public float Unknown514;     // offset: 0x414, sz: 4, origin: 0xC0000000, parsed: -2
        public float Unknown518;     // offset: 0x418, sz: 4, origin: 0x00000000, parsed: 0
		public float Unknown51C;     // offset: 0x41C, sz: 4, origin: 0x00000000, parsed: 0
        public float Unknown520;     // offset: 0x420, sz: 4, origin: 0x40000000, parsed: 2
        public float Unknown524;     // offset: 0x424, sz: 4, origin: 0xC0000000, parsed: -2
        public float Unknown528;     // offset: 0x428, sz: 4, origin: 0x00000000, parsed: 0
		public float Unknown52C;     // offset: 0x42C, sz: 4, origin: 0x00000000, parsed: 0
        public GcPlayerSpaceshipWarpData Unknown530;        // test. Does this look right??
        //public float Unknown530;     // offset: 0x430, sz: 4, origin: 0x3E99999A, parsed: 0.3
        //public int Unknown534;     // offset: 0x434, sz: 4, origin: 0x00000009, parsed: 9
        //public float Unknown538;     // offset: 0x438, sz: 4, origin: 0xC1F00000, parsed: -30
        //public float Unknown53C;     // offset: 0x43C, sz: 4, origin: 0x466A6000, parsed: 15000
        //public float Unknown540;     // offset: 0x440, sz: 4, origin: 0x3DCCCCCD, parsed: 0.1
        //public float Unknown544;     // offset: 0x444, sz: 4, origin: 0x42700000, parsed: 60
        //public float Unknown548;     // offset: 0x448, sz: 4, origin: 0x3E4CCCCD, parsed: 0.2
        //public float Unknown54C;     // offset: 0x44C, sz: 4, origin: 0x40000000, parsed: 2
        //public float Unknown550;     // offset: 0x450, sz: 4, origin: 0x3F000000, parsed: 0.5
        //public int Unknown554;     // offset: 0x454, sz: 4, origin: 0x0000000C, parsed: 12
        //public float Unknown558;     // offset: 0x45*, sz: 4, origin: 0x43C80000, parsed: 400
        //public float Unknown55C;     // offset: 0x45C, sz: 4, origin: 0x468CA000, parsed: 18000
        public float Unknown560;     // offset: 0x460, sz: 4, origin: 0x3F800000, parsed: 1
        public float Unknown564;     // offset: 0x464, sz: 4, origin: 0x41200000, parsed: 10
        public float Unknown568;     // offset: 0x468, sz: 4, origin: 0x3F0CCCCD, parsed: 0.55
        public float Unknown56C;     // offset: 0x46C, sz: 4, origin: 0x3F333333, parsed: 0.7
        public float Unknown570;     // offset: 0x470, sz: 4, origin: 0x3F800000, parsed: 1
        public float Unknown574;     // offset: 0x474, sz: 4, origin: 0x43160000, parsed: 150
        public float Unknown578;     // offset: 0x478, sz: 4, origin: 0x40A00000, parsed: 5
        public float Unknown57C;     // offset: 0x47C, sz: 4, origin: 0x42C80000, parsed: 100
        public float Unknown580;     // offset: 0x480, sz: 4, origin: 0x41A00000, parsed: 20
        public float Unknown584;     // offset: 0x48C, sz: 4, origin: 0x3F4CCCCD, parsed: 0.8
        public float Unknown588;     // offset: 0x490, sz: 4, origin: 0x41A80000, parsed: 21
        public float Unknown58C;     // offset: 0x494, sz: 4, origin: 0x41200000, parsed: 10
        public float Unknown590;     // offset: 0x498, sz: 4, origin: 0x3FE66666, parsed: 1.8
        public float Unknown594;     // offset: 0x49C, sz: 4, origin: 0x41C80000, parsed: 25
        public float Unknown598;     // offset: 0x4A0, sz: 4, origin: 0x3F99999A, parsed: 1.2
        public float Unknown59C;     // offset: 0x4A4, sz: 4, origin: 0x42C80000, parsed: 100
        public float Unknown5A0;     // offset: 0x4A8, sz: 4, origin: 0x49742400, parsed: 1000000
		public float Unknown5A4;	 // offset: 0x4AC, sz: 4, origin: 0x00000000, parsed: 0

// new data
		public float Unknown5A8;  // sz: 4, origin: 0x00000000, parsed: 0
		public float Unknown5AC;  // sz: 4, origin: 0x00000000, parsed: 0
// end of new data		

        public float Unknown5B0;     // offset: 0x4B0, sz: 4, origin: 0x3F800000, parsed: 1
        public float Unknown5B4;     // offset: 0x4B4, sz: 4, origin: 0x3F800000, parsed: 1
        public float Unknown5B8;     // offset: 0x4B8, sz: 4, origin: 0x3F800000, parsed: 1
		public float Unknown5BC;	 // offset: 0x4BC, sz: 4, origin: 0x00000000, parsed: 0
        public float Unknown5C0;     // offset: 0x4C0, sz: 4, origin: 0x3F333333, parsed: 0.7
        public float Unknown5C4;     // offset: 0x4C4, sz: 4, origin: 0x437A0000, parsed: 250
        public float Unknown5C8;     // offset: 0x4C8, sz: 4, origin: 0x3FA66666, parsed: 1.3
        public float Unknown5CC;     // offset: 0x4CC, sz: 4, origin: 0x3ECCCCCD, parsed: 0.4
        public float Unknown5D0;     // offset: 0x4D0, sz: 4, origin: 0x3F333333, parsed: 0.7
        public float Unknown5D4;     // offset: 0x4D4, sz: 4, origin: 0x3E4CCCCD, parsed: 0.2
        public float Unknown5D8;     // offset: 0x4D8, sz: 4, origin: 0x3E800000, parsed: 0.25
        public float Unknown5DC;     // offset: 0x4DC, sz: 4, origin: 0x3F800000, parsed: 1
        public float Unknown5E0;     // offset: 0x4E0, sz: 4, origin: 0x3F800000, parsed: 1
        public float Unknown5E4;     // offset: 0x4E4, sz: 4, origin: 0x40000000, parsed: 2
        public float Unknown5E8;     // offset: 0x4E8, sz: 4, origin: 0x44AF0000, parsed: 1400
        public float Unknown5EC;     // offset: 0x4EC, sz: 4, origin: 0x3F800000, parsed: 1
        public float Unknown5F0;     // offset: 0x4F0, sz: 4, origin: 0x41A00000, parsed: 20
        public float Unknown5F4;     // offset: 0x4F4, sz: 4, origin: 0x41400000, parsed: 12
        public float Unknown5F8;     // offset: 0x4F8, sz: 4, origin: 0x40400000, parsed: 3
        public float Unknown5FC;     // offset: 0x4FC, sz: 4, origin: 0x3F800000, parsed: 1
        public float Unknown600;     // offset: 0x500, sz: 4, origin: 0x40400000, parsed: 3
        public float Unknown604;     // offset: 0x504, sz: 4, origin: 0x00000000, parsed: 0
        public float Unknown608;     // offset: 0x508, sz: 4, origin: 0x42C80000, parsed: 100
        public float Unknown60C;     // offset: 0x50C, sz: 4, origin: 0x3F19999A, parsed: 0.6
        public float Unknown610;     // offset: 0x510, sz: 4, origin: 0x42B40000, parsed: 90
        public float Unknown614;     // offset: 0x514, sz: 4, origin: 0xC2C80000, parsed: -100
        public float Unknown618;     // offset: 0x518, sz: 4, origin: 0x420C0000, parsed: 35
        public float Unknown61C;     // offset: 0x51C, sz: 4, origin: 0x43480000, parsed: 200
        public float Unknown620;     // offset: 0x520, sz: 4, origin: 0x43960000, parsed: 300
        public float Unknown624;     // offset: 0x524, sz: 4, origin: 0x43FA0000, parsed: 500
        public float Unknown628;     // offset: 0x528, sz: 4, origin: 0x42C80000, parsed: 100
        public float Unknown62C;     // offset: 0x52C, sz: 4, origin: 0x3E19999A, parsed: 0.15
        public float Unknown630;     // offset: 0x530, sz: 4, origin: 0x43160000, parsed: 150
        public float Unknown634;     // offset: 0x534, sz: 4, origin: 0x47C35000, parsed: 100000
        public float Unknown638;     // offset: 0x538, sz: 4, origin: 0x44FA0000, parsed: 2000
        public float Unknown63C;     // offset: 0x53C, sz: 4, origin: 0x43160000, parsed: 150
        public float Unknown640;     // offset: 0x540, sz: 4, origin: 0x40800000, parsed: 4
        public float Unknown644;     // offset: 0x544, sz: 4, origin: 0x40E00000, parsed: 7
        public float Unknown648;     // offset: 0x548, sz: 4, origin: 0x41A00000, parsed: 20
        public float Unknown64C;     // offset: 0x54C, sz: 4, origin: 0x3E99999A, parsed: 0.3
        public float Unknown650;     // offset: 0x550, sz: 4, origin: 0x41700000, parsed: 15
        public float Unknown654;     // offset: 0x554, sz: 4, origin: 0x3F400000, parsed: 0.75
        public float Unknown658;     // offset: 0x558, sz: 4, origin: 0x3F4CCCCD, parsed: 0.8
        public float Unknown65C;     // offset: 0x55C, sz: 4, origin: 0x41700000, parsed: 15
        public float Unknown660;     // offset: 0x560, sz: 4, origin: 0x3F000000, parsed: 0.5
        [NMS(Size = 0x80)]
        public string Unknown664;     // offset: 0x564, sz: 128, origin:  "MODELS/COMMON/SPACECRAFT/DROPSHIPS/DROPSHIP_PROC.DAE"        // line:   strncpy((char *)(v1 + 0x564), "MODELS/COMMON/SPACECRAFT/DROPSHIPS/DROPSHIP_PROC.DAE", 0x80ui64);
        // line:   *(_BYTE *)(v1 + 0x5E3) = 0;
        [NMS(Size = 0x80)]
        public string Unknown6E4;     // offset: 0x5E4, sz: 128, origin:  "MODELS/COMMON/SPACECRAFT/FIGHTERS/FIGHTER_PROC.DAE"        // line:   strncpy((char *)(v1 + 0x5E4), "MODELS/COMMON/SPACECRAFT/FIGHTERS/FIGHTER_PROC.DAE", 0x80ui64);
        // line:   *(_BYTE *)(v1 + 0x663) = 0;
        [NMS(Size = 0x80)]
        public string Unknown764;     // offset: 0x664, sz: 128, origin:  "MODELS/COMMON/SPACECRAFT/SCIENTIFIC/SCIENTIFIC_PROC.DAE"        // line:   strncpy((char *)(v1 + 0x664), "MODELS/COMMON/SPACECRAFT/SCIENTIFIC/SCIENTIFIC_PROC.DAE", 0x80ui64);
        // line:   *(_BYTE *)(v1 + 0x6E3) = 0;
        [NMS(Size = 0x80)]
        public string Unknown7E4;     // offset: 0x6E4, sz: 128, origin:  "MODELS/COMMON/SPACECRAFT/SHUTTLE/SHUTTLE_PROC.DAE"        // line:   result = strncpy((char *)(v1 + 0x6E4), "MODELS/COMMON/SPACECRAFT/SHUTTLE/SHUTTLE_PROC.DAE", 0x80ui64);
        // line:   *(_BYTE *)(v1 + 0x763) = 0;
        public float Unknown864;     // offset: 0x764, sz: 4, origin: 0x41200000, parsed: 10

        [NMS(Size = 8, Ignore = true)]
        public byte[] Padding868;
    }
}