// generated by hand
// 
// 

namespace MBINCompiler.Models.Structs
{
    public class GcSpaceshipGlobals : NMSTemplate
    {
        public float Unknown0;
        public float Unknown4;
        public float Unknown8;
        public float UnknownC;
        public float Unknown10;
        public float Unknown14;
        public float Unknown18;
        public float Unknown1C;
        public float Unknown20;
        public float Unknown24;
        public float Unknown28;
        public float Unknown2C;
        public float Unknown30;
        public float Unknown34;
        public float Unknown38;
        public float Unknown3C;
        public float Unknown40;
        public float Unknown44;
        public int UnknownInt48;
        public int UnknownInt4C;
        public float Unknown50;
        public float Unknown54;
        public float Unknown58;
        public Vector2f Unknown5C;
        public float Unknown64;
        public float Unknown68;
        public float Unknown6C;
        public float Unknown70;
        public float Unknown74;
        public float Unknown78;
        public float Unknown7C;
        public float Unknown80;
        public float Unknown84;
        public float Unknown88;
        public float Unknown8C;
        public float Unknown90;
        public float Unknown94;
        public float Unknown98;
        public int UnknownInt9C;
        public int UnknownIntA0;
        public float UnknownA4;     // not used?
        public float UnknownA8;     // not used?
        public float UnknownAC;     // not used?
        public float UnknownB0;
        public float UnknownB4;
        public float UnknownB8;
        public float UnknownBC;
        public float UnknownC0;
        public float UnknownC4;
        public float UnknownC8;
        public float UnknownCC;
        public bool UnknownD0;
        public float UnknownD4;
        public float UnknownD8;
        public float UnknownDC;
        public float UnknownE0;
        public float UnknownE4;
        public float MinAutoLiftAltitude;
        public float UnknownEC;
        public float UnknownF0;
        public Vector2f UnknownF4;
        public float UnknownFC;
        public float Unknown100;
        public float Unknown104;
        public float Unknown108;
        public float Unknown10C;
        public float Unknown110;
        public float Unknown114;
        public float Unknown118;
        public float Unknown11C;
        public float Unknown120;
        public float Unknown124;
        public float Unknown128;
        public float Unknown12C;
        public float Unknown130;
        public float Unknown134;
        public float Unknown138;
        public float Unknown13C;
        public int UnknownInt140;
        public float Unknown144;
        public float Unknown148;
        public float Unknown14C;
        public float Unknown150;
        public float Unknown154;
        public Vector2f Unknown158;
        public float Unknown160;
        public float Unknown164;
        public float Unknown168;
        public float Unknown16C;
        public float Unknown170;
        public float Unknown174;
        public float Unknown178;

        public GcPlayerSpaceshipControlData Unknown17C;

        public float Unknown270;
        public float Unknown274;
        public float Unknown278;
        public float Unknown27C;
        public float Unknown280;
        public float Unknown284;
        public int UnknownInt288;

        public GcPlayerSpaceshipAim Unknnown28C;
        /*public float Unknown28C;
        public float Unknown290;
        public float Unknown294;
        public float Unknown298;
        public float Unknown29C;
        public float Unknown2A0;*/

        public GcPlayerSpaceshipAim Unknown2A4;
        /*public float Unknown2A4;
        public float Unknown2A8;
        public float Unknown2AC;
        public float Unknown2B0;
        public float Unknown2B4;
        public float Unknown2B8;*/

        public GcPlayerSpaceshipAim Unknown2BC;
        /*public float Unknown2BC;
        public float Unknown2C0;
        public float Unknown2C4;
        public float Unknown2C8;
        public float Unknown2CC;
        public float Unknown2D0;*/

        public float Unknown2D4;

        public GcPlayerSpaceshipAim Unknown2D8;
        /*public float Unknown2D8;
        public float Unknown2DC;
        public float Unknown2E0;
        public float Unknown2E4;
        public float Unknown2E8;
        public float Unknown2EC;*/

        public GcPlayerSpaceshipAim Unknown2F0;
        /*public float Unknown2F0;
        public float Unknown2F4;
        public float Unknown2F8;
        public float Unknown2FC;
        public float Unknown300;
        public float Unknown304;*/

        public GcPlayerSpaceshipAim Unknown308;
        /*public float Unknown308;
        public float Unknown30C;
        public float Unknown310;
        public float Unknown314;
        public float Unknown318;
        public float Unknown31C;*/

        public int UnknownInt320;

        public float Unknown324;
        public float Unknown328;

        public GcPlayerSpaceshipAim Unknown32C;
        /*public float Unknown32C;
        public float Unknown330;
        public float Unknown334;
        public float Unknown338;
        public float Unknown33C;
        public float Unknown340;*/

        public float Unknown344;
        public float Unknown348;
        public float Unknown34C;
        public float Unknown350;
        public float Unknown354;
        public float Unknown358;
        public float Unknown35C;
        public float Unknown360;
        public float Unknown364;
        public float Unknown368;
        public float Unknown36C;
        public float Unknown370;
        public float Unknown374;
        public float Unknown378;
        public float Unknown37C;
        public float Unknown380;
        public float Unknown384;
        public float Unknown388;
        public float Unknown38C;
        public float Unknown390;
        public float Unknown394;
        public float Unknown398;
        public float Unknown39C;
        public float Unknown3A0;
        public int UnknownInt3A4;
        public float Unknown3A8;
        public Vector2f Unknown3AC;
        public float Unknown3B4;
        public float Unknown3B8;
        public float Unknown3BC;
        public float Unknown3C0;
        public float Unknown3C4;
        public float Unknown3C8;
        public float Unknown3CC;
        public float Unknown3D0;
        public float Unknown3D4;
        public float Unknown3D8;
        public int UnknownInt3DC;
        public float Unknown3E0;
        public float Unknown3E4;
        public float Unknown3E8;
        public float Unknown3EC;
        public float Unknown3F0;
        public float Unknown3F4;
        public float Unknown3F8;
        public float Unknown3FC;
        public float Unknown400;
        public float Unknown404;
        public float Unknown408;
        public float Unknown40C;
        public float Unknown410;
        public float Unknown414;
        public float Unknown418;
        public float Unknown41C;
        public float Unknown420;
        public float Unknown424;
        public float Unknown428;
        public float Unknown42C;
        public float Unknown430;
        public float Unknown434;
        public float Unknown438;
        public float Unknown43C;
        public float Unknown440;
        public float Unknown444;
        public float Unknown448;
        public float Unknown44C;
        public float Unknown450;
        public float Unknown454;
        public float Unknown458;
        public float Unknown45C;
        public float Unknown460;
        public float Unknown464;
        public float Unknown468;
        public float Unknown46C;
        public float Unknown470;
        public int UnknownInt474;
        public float Unknown478;
        public float Unknown47C;
        public float Unknown480;
        public float Unknown484;
        public float Unknown488;
        public float Unknown48C;
        public float Unknown490;
        public float Unknown494;
        public float Unknown498;
        public float Unknown49C;
        public float Unknown4A0;
        public float Unknown4A4;
        public bool Unknown4A8;
        public float Unknown4AC;
        public float Unknown4B0;
        public float Unknown4B4;
        public int UnknownInt4B8;
        public float Unknown4BC;
        public float Unknown4C0;
        public float Unknown4C4;
        public int UnknownInt4C8;
        public float Unknown4CC;
        public float Unknown4D0;
        public int UnknownInt4D4;
        public float Unknown4D8;
        public float Unknown4DC;
        public float Unknown4E0;
        public float Unknown4E4;
        public float Unknown4E8;
        public float Unknown4EC;
        public int UnknownInt4F0;
        public float Unknown4F4;
        public float Unknown4F8;
        public float Unknown4FC;
        public float Unknown500;
        public float Unknown504;
        public float Unknown508;
        public float Unknown50C;
        public float Unknown510;
        public float Unknown514;
        public float Unknown518;
        public float Unknown51C;
        public float Unknown520;
        public float Unknown524;
        public float Unknown528;        // [rdi+528h], edx   probably padding along with next line?
        public float Unknown52C;
        public float Unknown530;
        public float Unknown534;
        public float Unknown538;        // [rdi+538h], edx   probably padding along with next line?
        public float Unknown53C;
        public GcPlayerSpaceshipWarpData Unknown540;
        public float Unknown570;
        public float Unknown574;
        public float Unknown578;
        public float Unknown57C;
        public float Unknown580;
        public float Unknown584;
        public float Unknown588;
        public float Unknown58C;
        public float Unknown590;
        public float Unknown594;
        public float Unknown598;
        public float Unknown59C;
        public float Unknown5A0;
        public float Unknown5A4;
        public float Unknown5A8;
        public float Unknown5AC;
        public float Unknown5B0;
        public float Unknown5B4;
        public float Unknown5B8;
        public float Unknown5BC;
        public float Unknown5C0;
        public float Unknown5C4;
        public float Unknown5C8;
        public float Unknown5CC;
        public float Unknown5D0;
        public float Unknown5D4;
        public float Unknown5D8;
        public float Unknown5DC;
        public float Unknown5E0;
        public float Unknown5E4;
        public float Unknown5E8;
        public float Unknown5EC;
        public float Unknown5F0;
        public float Unknown5F4;
        public float Unknown5F8;
        public float Unknown5FC;
        public float Unknown600;
        public float Unknown604;
        public float Unknown608;
        public float Unknown60C;
        public float Unknown610;
        public float Unknown614;
        public float Unknown618;
        public float Unknown61C;
        public float Unknown620;
        public float Unknown624;
        public float Unknown628;
        public float Unknown62C;
        public float Unknown630;
        public float Unknown634;
        public float Unknown638;
        public float Unknown63C;
        public float Unknown640;
        public float Unknown644;
        public float Unknown648;
        public float Unknown64C;
        public float Unknown650;
        public float Unknown654;
        public float Unknown658;
        public float Unknown65C;
        public float Unknown660;
        public float Unknown664;
        public float Unknown668;
        public float Unknown66C;
        public float Unknown670;

        [NMS(Size = 0x80)]
        public string DropshipScenePath;     // offset: 0x564, sz: 128, origin:  "MODELS/COMMON/SPACECRAFT/DROPSHIPS/DROPSHIP_PROC.DAE"        // line:   strncpy((char *)(v1 + 0x564), "MODELS/COMMON/SPACECRAFT/DROPSHIPS/DROPSHIP_PROC.DAE", 0x80ui64);
        // line:   *(_BYTE *)(v1 + 0x5E3) = 0;
        [NMS(Size = 0x80)]
        public string FighterScenePath;     // offset: 0x5E4, sz: 128, origin:  "MODELS/COMMON/SPACECRAFT/FIGHTERS/FIGHTER_PROC.DAE"        // line:   strncpy((char *)(v1 + 0x5E4), "MODELS/COMMON/SPACECRAFT/FIGHTERS/FIGHTER_PROC.DAE", 0x80ui64);
        // line:   *(_BYTE *)(v1 + 0x663) = 0;
        [NMS(Size = 0x80)]
        public string ScientificScenePath;     // offset: 0x664, sz: 128, origin:  "MODELS/COMMON/SPACECRAFT/SCIENTIFIC/SCIENTIFIC_PROC.DAE"        // line:   strncpy((char *)(v1 + 0x664), "MODELS/COMMON/SPACECRAFT/SCIENTIFIC/SCIENTIFIC_PROC.DAE", 0x80ui64);
        // line:   *(_BYTE *)(v1 + 0x6E3) = 0;
        [NMS(Size = 0x80)]
        public string ShuttleScenePath;     // offset: 0x6E4, sz: 128, origin:  "MODELS/COMMON/SPACECRAFT/SHUTTLE/SHUTTLE_PROC.DAE"        // line:   result = strncpy((char *)(v1 + 0x6E4), "MODELS/COMMON/SPACECRAFT/SHUTTLE/SHUTTLE_PROC.DAE", 0x80ui64);
        // line:   *(_BYTE *)(v1 + 0x763) = 0;
        public float Unknown874;     // offset: 0x764, sz: 4, origin: 0x41200000, parsed: 10

        [NMS(Size = 8, Ignore = true)]
        public byte[] Padding878;
    }
}